//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class FieldSet : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _autoEl_default = "\'fieldset\'";
        
        public string _baseCls_default = "\'x-fieldset\'";
        
        public string _checkboxToggle_default = "false";
        
        public string _collapsed_default = "false";
        
        public string _collapsible_default = "false";
        
        public string _componentLayout_default = "\'fieldset\'";
        
        public string _layout_default = "\'anchor\'";
        
        public string _renderTpl_default = "[\'{%this.renderLegend(out,values);%}\', \'<div id=\"{id}-body\" class=\"{baseCls}-body" +
            " {bodyTargetCls}\"<tpl if=\"bodyStyle\"> style=\"{bodyStyle}\"</tpl>>\', \'{%this.rende" +
            "rContainer(out,values);%}\', \'</div>\']";
        
        public string _stateEvents_default = "[\'collapse\', \'expand\']";
        
        public string _toggleOnTitleClick_default = "true";
        
        public object autoEl
        {
            get
            {
                return this.attributes["autoEl"];
            }
            set
            {
                this.attributes["autoEl"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object checkboxName
        {
            get
            {
                return this.attributes["checkboxName"];
            }
            set
            {
                this.attributes["checkboxName"] = value;
            }
        }
        
        public object checkboxToggle
        {
            get
            {
                return this.attributes["checkboxToggle"];
            }
            set
            {
                this.attributes["checkboxToggle"] = value;
            }
        }
        
        public object collapsed
        {
            get
            {
                return this.attributes["collapsed"];
            }
            set
            {
                this.attributes["collapsed"] = value;
            }
        }
        
        public object collapsible
        {
            get
            {
                return this.attributes["collapsible"];
            }
            set
            {
                this.attributes["collapsible"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object stateEvents
        {
            get
            {
                return this.attributes["stateEvents"];
            }
            set
            {
                this.attributes["stateEvents"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public object toggleOnTitleClick
        {
            get
            {
                return this.attributes["toggleOnTitleClick"];
            }
            set
            {
                this.attributes["toggleOnTitleClick"] = value;
            }
        }
        
        public class MultiType_autoEl
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_checkboxName
        {
        }
        
        public class MultiType_checkboxToggle
        {
        }
        
        public class MultiType_collapsed
        {
        }
        
        public class MultiType_collapsible
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_stateEvents
        {
        }
        
        public class MultiType_title
        {
        }
        
        public class MultiType_toggleOnTitleClick
        {
        }
    }
}
