//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.header
{
    using System;
    
    
    public partial class Container : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'grid-header-ct\'";
        
        public string _border_default = "true";
        
        public string _defaultType_default = "\'gridcolumn\'";
        
        public string _defaultWidth_default = "100";
        
        public string _detachOnRemove_default = "false";
        
        public string _enableColumnHide_default = "true";
        
        public string _sealed_default = "false";
        
        public string _sortable_default = "true";
        
        public string _weight_default = "100";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object border
        {
            get
            {
                return this.attributes["border"];
            }
            set
            {
                this.attributes["border"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object defaultWidth
        {
            get
            {
                return this.attributes["defaultWidth"];
            }
            set
            {
                this.attributes["defaultWidth"] = value;
            }
        }
        
        public object detachOnRemove
        {
            get
            {
                return this.attributes["detachOnRemove"];
            }
            set
            {
                this.attributes["detachOnRemove"] = value;
            }
        }
        
        public object enableColumnHide
        {
            get
            {
                return this.attributes["enableColumnHide"];
            }
            set
            {
                this.attributes["enableColumnHide"] = value;
            }
        }
        
        public object _sealed
        {
            get
            {
                return this.attributes["sealed"];
            }
            set
            {
                this.attributes["sealed"] = value;
            }
        }
        
        public object sortable
        {
            get
            {
                return this.attributes["sortable"];
            }
            set
            {
                this.attributes["sortable"] = value;
            }
        }
        
        public object weight
        {
            get
            {
                return this.attributes["weight"];
            }
            set
            {
                this.attributes["weight"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_border
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_defaultWidth
        {
        }
        
        public class MultiType_detachOnRemove
        {
        }
        
        public class MultiType_enableColumnHide
        {
        }
        
        public class MultiType_sealed
        {
        }
        
        public class MultiType_sortable
        {
        }
        
        public class MultiType_weight
        {
        }
    }
}
