//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tree
{
    using System;
    
    
    public partial class View : zzProject.ExtJSNet.ExtJS.Classes.Ext.view.Table
    {
        
        public string _blockRefresh_default = "true";
        
        public string _deferInitialRefresh_default = "false";
        
        public string _loadMask_default = "false";
        
        public string _loadingCls_default = "Ext.baseCSSPrefix + \'grid-tree-loading\'";
        
        public string _rootVisible_default = "true";
        
        public string _stripeRows_default = "false";
        
        public object animate
        {
            get
            {
                return this.attributes["animate"];
            }
            set
            {
                this.attributes["animate"] = value;
            }
        }
        
        public object blockRefresh
        {
            get
            {
                return this.attributes["blockRefresh"];
            }
            set
            {
                this.attributes["blockRefresh"] = value;
            }
        }
        
        public object deferInitialRefresh
        {
            get
            {
                return this.attributes["deferInitialRefresh"];
            }
            set
            {
                this.attributes["deferInitialRefresh"] = value;
            }
        }
        
        public object loadMask
        {
            get
            {
                return this.attributes["loadMask"];
            }
            set
            {
                this.attributes["loadMask"] = value;
            }
        }
        
        public object loadingCls
        {
            get
            {
                return this.attributes["loadingCls"];
            }
            set
            {
                this.attributes["loadingCls"] = value;
            }
        }
        
        public object rootVisible
        {
            get
            {
                return this.attributes["rootVisible"];
            }
            set
            {
                this.attributes["rootVisible"] = value;
            }
        }
        
        public object stripeRows
        {
            get
            {
                return this.attributes["stripeRows"];
            }
            set
            {
                this.attributes["stripeRows"] = value;
            }
        }
        
        public class MultiType_animate
        {
        }
        
        public class MultiType_blockRefresh
        {
        }
        
        public class MultiType_deferInitialRefresh
        {
        }
        
        public class MultiType_loadMask
        {
        }
        
        public class MultiType_loadingCls
        {
        }
        
        public class MultiType_rootVisible
        {
        }
        
        public class MultiType_stripeRows
        {
        }
    }
}
