//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.app
{
    using System;
    
    
    public partial class Application : zzProject.ExtJSNet.ExtJS.Classes.Ext.app.Controller
    {
        
        public string _appFolder_default = "\'app\'";
        
        public string _appProperty_default = "\'app\'";
        
        public string _autoCreateViewport_default = "false";
        
        public string _enableQuickTips_default = "true";
        
        public string _namespaces_default = "[]";
        
        public object appFolder
        {
            get
            {
                return this.attributes["appFolder"];
            }
            set
            {
                this.attributes["appFolder"] = value;
            }
        }
        
        public object appProperty
        {
            get
            {
                return this.attributes["appProperty"];
            }
            set
            {
                this.attributes["appProperty"] = value;
            }
        }
        
        public object autoCreateViewport
        {
            get
            {
                return this.attributes["autoCreateViewport"];
            }
            set
            {
                this.attributes["autoCreateViewport"] = value;
            }
        }
        
        public object controllers
        {
            get
            {
                return this.attributes["controllers"];
            }
            set
            {
                this.attributes["controllers"] = value;
            }
        }
        
        public object enableQuickTips
        {
            get
            {
                return this.attributes["enableQuickTips"];
            }
            set
            {
                this.attributes["enableQuickTips"] = value;
            }
        }
        
        public object name
        {
            get
            {
                return this.attributes["name"];
            }
            set
            {
                this.attributes["name"] = value;
            }
        }
        
        public object namespaces
        {
            get
            {
                return this.attributes["namespaces"];
            }
            set
            {
                this.attributes["namespaces"] = value;
            }
        }
        
        public object paths
        {
            get
            {
                return this.attributes["paths"];
            }
            set
            {
                this.attributes["paths"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public class MultiType_appFolder
        {
        }
        
        public class MultiType_appProperty
        {
        }
        
        public class MultiType_autoCreateViewport
        {
        }
        
        public class MultiType_controllers
        {
        }
        
        public class MultiType_enableQuickTips
        {
        }
        
        public class MultiType_name
        {
        }
        
        public class MultiType_namespaces
        {
        }
        
        public class MultiType_paths
        {
        }
        
        public class MultiType_scope
        {
        }
    }
}
