//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class Operation : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _synchronous_default = "true";
        
        public object action
        {
            get
            {
                return this.attributes["action"];
            }
            set
            {
                this.attributes["action"] = value;
            }
        }
        
        public object batch
        {
            get
            {
                return this.attributes["batch"];
            }
            set
            {
                this.attributes["batch"] = value;
            }
        }
        
        public object callback
        {
            get
            {
                return this.attributes["callback"];
            }
            set
            {
                this.attributes["callback"] = value;
            }
        }
        
        public object filters
        {
            get
            {
                return this.attributes["filters"];
            }
            set
            {
                this.attributes["filters"] = value;
            }
        }
        
        public object groupers
        {
            get
            {
                return this.attributes["groupers"];
            }
            set
            {
                this.attributes["groupers"] = value;
            }
        }
        
        public object limit
        {
            get
            {
                return this.attributes["limit"];
            }
            set
            {
                this.attributes["limit"] = value;
            }
        }
        
        public object _params
        {
            get
            {
                return this.attributes["params"];
            }
            set
            {
                this.attributes["params"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object sorters
        {
            get
            {
                return this.attributes["sorters"];
            }
            set
            {
                this.attributes["sorters"] = value;
            }
        }
        
        public object start
        {
            get
            {
                return this.attributes["start"];
            }
            set
            {
                this.attributes["start"] = value;
            }
        }
        
        public object synchronous
        {
            get
            {
                return this.attributes["synchronous"];
            }
            set
            {
                this.attributes["synchronous"] = value;
            }
        }
        
        public class MultiType_action
        {
        }
        
        public class MultiType_batch
        {
        }
        
        public class MultiType_callback
        {
        }
        
        public class MultiType_filters
        {
        }
        
        public class MultiType_groupers
        {
        }
        
        public class MultiType_limit
        {
        }
        
        public class MultiType_params
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_sorters
        {
        }
        
        public class MultiType_start
        {
        }
        
        public class MultiType_synchronous
        {
        }
    }
}
