//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.state
{
    using System;
    
    
    public partial class Stateful : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _saveDelay_default = "100";
        
        public string _stateful_default = "false";
        
        public object saveDelay
        {
            get
            {
                return this.attributes["saveDelay"];
            }
            set
            {
                this.attributes["saveDelay"] = value;
            }
        }
        
        public object stateEvents
        {
            get
            {
                return this.attributes["stateEvents"];
            }
            set
            {
                this.attributes["stateEvents"] = value;
            }
        }
        
        public object stateId
        {
            get
            {
                return this.attributes["stateId"];
            }
            set
            {
                this.attributes["stateId"] = value;
            }
        }
        
        public object stateful
        {
            get
            {
                return this.attributes["stateful"];
            }
            set
            {
                this.attributes["stateful"] = value;
            }
        }
        
        public class MultiType_saveDelay
        {
        }
        
        public class MultiType_stateEvents
        {
        }
        
        public class MultiType_stateId
        {
        }
        
        public class MultiType_stateful
        {
        }
    }
}
