//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class LoadMask : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'mask-msg\'";
        
        public string _maskCls_default = "\"x-mask\"";
        
        public string _msg_default = "\"Loading...\"";
        
        public string _msgCls_default = "\"x-mask-loading\"";
        
        public string _renderTpl_default = "[\'<div id=\"{id}-msgEl\" class=\"{[values.$comp.msgCls]} \', Ext.baseCSSPrefix, \'mask" +
            "-msg-inner{childElCls}\">\', \'<div id=\"{id}-msgTextEl\" class=\"\', Ext.baseCSSPrefix" +
            ", \'mask-msg-text\', \'{childElCls}\"></div>\', \'</div>\']";
        
        public string _useMsg_default = "true";
        
        public string _useTargetEl_default = "false";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object maskCls
        {
            get
            {
                return this.attributes["maskCls"];
            }
            set
            {
                this.attributes["maskCls"] = value;
            }
        }
        
        public object msg
        {
            get
            {
                return this.attributes["msg"];
            }
            set
            {
                this.attributes["msg"] = value;
            }
        }
        
        public object msgCls
        {
            get
            {
                return this.attributes["msgCls"];
            }
            set
            {
                this.attributes["msgCls"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object store
        {
            get
            {
                return this.attributes["store"];
            }
            set
            {
                this.attributes["store"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public object useMsg
        {
            get
            {
                return this.attributes["useMsg"];
            }
            set
            {
                this.attributes["useMsg"] = value;
            }
        }
        
        public object useTargetEl
        {
            get
            {
                return this.attributes["useTargetEl"];
            }
            set
            {
                this.attributes["useTargetEl"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_maskCls
        {
        }
        
        public class MultiType_msg
        {
        }
        
        public class MultiType_msgCls
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_store
        {
        }
        
        public class MultiType_target
        {
        }
        
        public class MultiType_useMsg
        {
        }
        
        public class MultiType_useTargetEl
        {
        }
    }
}
