//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.dd
{
    using System;
    
    
    public partial class StatusProxy : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _dropAllowed_default = "Ext.baseCSSPrefix + \'dd-drop-ok\'";
        
        public string _dropNotAllowed_default = "Ext.baseCSSPrefix + \'dd-drop-nodrop\'";
        
        public string _renderTpl_default = "[\'<div class=\"\' + Ext.baseCSSPrefix + \'dd-drop-icon\"></div>\' + \'<div id=\"{id}-gho" +
            "st\" class=\"\' + Ext.baseCSSPrefix + \'dd-drag-ghost\"></div>\']";
        
        public object dropAllowed
        {
            get
            {
                return this.attributes["dropAllowed"];
            }
            set
            {
                this.attributes["dropAllowed"] = value;
            }
        }
        
        public object dropNotAllowed
        {
            get
            {
                return this.attributes["dropNotAllowed"];
            }
            set
            {
                this.attributes["dropNotAllowed"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public class MultiType_dropAllowed
        {
        }
        
        public class MultiType_dropNotAllowed
        {
        }
        
        public class MultiType_renderTpl
        {
        }
    }
}
