//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis
{
    using System;
    
    
    public partial class Abstract : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object fields
        {
            get
            {
                return this.attributes["fields"];
            }
            set
            {
                this.attributes["fields"] = value;
            }
        }
        
        public object label
        {
            get
            {
                return this.attributes["label"];
            }
            set
            {
                this.attributes["label"] = value;
            }
        }
        
        public class MultiType_fields
        {
        }
        
        public class MultiType_label
        {
        }
    }
}
