//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.draw
{
    using System;
    
    
    public partial class Component : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _autoSize_default = "false";
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'surface\'";
        
        public string _componentLayout_default = "\'draw\'";
        
        public string _enginePriority_default = "[\'Svg\', \'Vml\']";
        
        public string _shrinkWrap_default = "3";
        
        public string _viewBox_default = "true";
        
        public object autoSize
        {
            get
            {
                return this.attributes["autoSize"];
            }
            set
            {
                this.attributes["autoSize"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object enginePriority
        {
            get
            {
                return this.attributes["enginePriority"];
            }
            set
            {
                this.attributes["enginePriority"] = value;
            }
        }
        
        public object gradients
        {
            get
            {
                return this.attributes["gradients"];
            }
            set
            {
                this.attributes["gradients"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object shrinkWrap
        {
            get
            {
                return this.attributes["shrinkWrap"];
            }
            set
            {
                this.attributes["shrinkWrap"] = value;
            }
        }
        
        public object viewBox
        {
            get
            {
                return this.attributes["viewBox"];
            }
            set
            {
                this.attributes["viewBox"] = value;
            }
        }
        
        public class MultiType_autoSize
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_enginePriority
        {
        }
        
        public class MultiType_gradients
        {
        }
        
        public class MultiType_items
        {
        }
        
        public class MultiType_shrinkWrap
        {
        }
        
        public class MultiType_viewBox
        {
        }
    }
}
