//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.direct
{
    using System;
    
    
    public partial class PollingProvider : zzProject.ExtJSNet.ExtJS.Classes.Ext.direct.JsonProvider
    {
        
        public string _interval_default = "3000";
        
        public object baseParams
        {
            get
            {
                return this.attributes["baseParams"];
            }
            set
            {
                this.attributes["baseParams"] = value;
            }
        }
        
        public object interval
        {
            get
            {
                return this.attributes["interval"];
            }
            set
            {
                this.attributes["interval"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public class MultiType_baseParams
        {
        }
        
        public class MultiType_interval
        {
        }
        
        public class MultiType_url
        {
        }
    }
}
