//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class ResultSet : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _count_default = "0";
        
        public string _loaded_default = "true";
        
        public string _success_default = "false";
        
        public string _total_default = "0";
        
        public object count
        {
            get
            {
                return this.attributes["count"];
            }
            set
            {
                this.attributes["count"] = value;
            }
        }
        
        public object loaded
        {
            get
            {
                return this.attributes["loaded"];
            }
            set
            {
                this.attributes["loaded"] = value;
            }
        }
        
        public object records
        {
            get
            {
                return this.attributes["records"];
            }
            set
            {
                this.attributes["records"] = value;
            }
        }
        
        public object success
        {
            get
            {
                return this.attributes["success"];
            }
            set
            {
                this.attributes["success"] = value;
            }
        }
        
        public object total
        {
            get
            {
                return this.attributes["total"];
            }
            set
            {
                this.attributes["total"] = value;
            }
        }
        
        public class MultiType_count
        {
        }
        
        public class MultiType_loaded
        {
        }
        
        public class MultiType_records
        {
        }
        
        public class MultiType_success
        {
        }
        
        public class MultiType_total
        {
        }
    }
}
