//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.writer
{
    using System;
    
    
    public partial class Json : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.writer.Writer
    {
        
        public string _allowSingle_default = "true";
        
        public string _encode_default = "false";
        
        public string _expandData_default = "false";
        
        public object allowSingle
        {
            get
            {
                return this.attributes["allowSingle"];
            }
            set
            {
                this.attributes["allowSingle"] = value;
            }
        }
        
        public object encode
        {
            get
            {
                return this.attributes["encode"];
            }
            set
            {
                this.attributes["encode"] = value;
            }
        }
        
        public object expandData
        {
            get
            {
                return this.attributes["expandData"];
            }
            set
            {
                this.attributes["expandData"] = value;
            }
        }
        
        public object root
        {
            get
            {
                return this.attributes["root"];
            }
            set
            {
                this.attributes["root"] = value;
            }
        }
        
        public class MultiType_allowSingle
        {
        }
        
        public class MultiType_encode
        {
        }
        
        public class MultiType_expandData
        {
        }
        
        public class MultiType_root
        {
        }
    }
}
