//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.container
{
    using System;
    
    
    public partial class AbstractContainer : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _autoDestroy_default = "true";
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'container\'";
        
        public string _defaultType_default = "\"panel\"";
        
        public string _detachOnRemove_default = "true";
        
        public string _renderTpl_default = "\'{%this.renderContainer(out,values)%}\'";
        
        public string _suspendLayout_default = "false";
        
        public object activeItem
        {
            get
            {
                return this.attributes["activeItem"];
            }
            set
            {
                this.attributes["activeItem"] = value;
            }
        }
        
        public object autoDestroy
        {
            get
            {
                return this.attributes["autoDestroy"];
            }
            set
            {
                this.attributes["autoDestroy"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object bubbleEvents
        {
            get
            {
                return this.attributes["bubbleEvents"];
            }
            set
            {
                this.attributes["bubbleEvents"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object defaults
        {
            get
            {
                return this.attributes["defaults"];
            }
            set
            {
                this.attributes["defaults"] = value;
            }
        }
        
        public object detachOnRemove
        {
            get
            {
                return this.attributes["detachOnRemove"];
            }
            set
            {
                this.attributes["detachOnRemove"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object suspendLayout
        {
            get
            {
                return this.attributes["suspendLayout"];
            }
            set
            {
                this.attributes["suspendLayout"] = value;
            }
        }
        
        public class MultiType_activeItem
        {
        }
        
        public class MultiType_autoDestroy
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_bubbleEvents
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_defaults
        {
        }
        
        public class MultiType_detachOnRemove
        {
        }
        
        public class MultiType_items
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_suspendLayout
        {
        }
    }
}
