//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class Label : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _autoEl_default = "\'label\'";
        
        public string _html_default = "\'\'";
        
        public string _text_default = "\'\'";
        
        public object autoEl
        {
            get
            {
                return this.attributes["autoEl"];
            }
            set
            {
                this.attributes["autoEl"] = value;
            }
        }
        
        public object forId
        {
            get
            {
                return this.attributes["forId"];
            }
            set
            {
                this.attributes["forId"] = value;
            }
        }
        
        public object html
        {
            get
            {
                return this.attributes["html"];
            }
            set
            {
                this.attributes["html"] = value;
            }
        }
        
        public object text
        {
            get
            {
                return this.attributes["text"];
            }
            set
            {
                this.attributes["text"] = value;
            }
        }
        
        public class MultiType_autoEl
        {
        }
        
        public class MultiType_forId
        {
        }
        
        public class MultiType_html
        {
        }
        
        public class MultiType_text
        {
        }
    }
}
