//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.picker
{
    using System;
    
    
    public partial class Time : zzProject.ExtJSNet.ExtJS.Classes.Ext.view.BoundList
    {
        
        public string _componentCls_default = "Ext.baseCSSPrefix + \'timepicker\'";
        
        public string _format_default = "undefined";
        
        public string _increment_default = "15";
        
        public object componentCls
        {
            get
            {
                return this.attributes["componentCls"];
            }
            set
            {
                this.attributes["componentCls"] = value;
            }
        }
        
        public object format
        {
            get
            {
                return this.attributes["format"];
            }
            set
            {
                this.attributes["format"] = value;
            }
        }
        
        public object increment
        {
            get
            {
                return this.attributes["increment"];
            }
            set
            {
                this.attributes["increment"] = value;
            }
        }
        
        public object maxValue
        {
            get
            {
                return this.attributes["maxValue"];
            }
            set
            {
                this.attributes["maxValue"] = value;
            }
        }
        
        public object minValue
        {
            get
            {
                return this.attributes["minValue"];
            }
            set
            {
                this.attributes["minValue"] = value;
            }
        }
        
        public class MultiType_componentCls
        {
        }
        
        public class MultiType_format
        {
        }
        
        public class MultiType_increment
        {
        }
        
        public class MultiType_maxValue
        {
        }
        
        public class MultiType_minValue
        {
        }
    }
}
