//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.view
{
    using System;
    
    
    public partial class AbstractView : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _blockRefresh_default = "false";
        
        public string _deferEmptyText_default = "true";
        
        public string _deferInitialRefresh_default = "true";
        
        public string _emptyText_default = "\"\"";
        
        public string _itemCls_default = "Ext.baseCSSPrefix + \'dataview-item\'";
        
        public string _loadMask_default = "true";
        
        public string _loadingText_default = "\'Loading...\'";
        
        public string _multiSelect_default = "false";
        
        public string _preserveScrollOnRefresh_default = "false";
        
        public string _selectedItemCls_default = "Ext.baseCSSPrefix + \'item-selected\'";
        
        public string _simpleSelect_default = "false";
        
        public string _trackOver_default = "false";
        
        public object blockRefresh
        {
            get
            {
                return this.attributes["blockRefresh"];
            }
            set
            {
                this.attributes["blockRefresh"] = value;
            }
        }
        
        public object deferEmptyText
        {
            get
            {
                return this.attributes["deferEmptyText"];
            }
            set
            {
                this.attributes["deferEmptyText"] = value;
            }
        }
        
        public object deferInitialRefresh
        {
            get
            {
                return this.attributes["deferInitialRefresh"];
            }
            set
            {
                this.attributes["deferInitialRefresh"] = value;
            }
        }
        
        public object disableSelection
        {
            get
            {
                return this.attributes["disableSelection"];
            }
            set
            {
                this.attributes["disableSelection"] = value;
            }
        }
        
        public object emptyText
        {
            get
            {
                return this.attributes["emptyText"];
            }
            set
            {
                this.attributes["emptyText"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object itemSelector
        {
            get
            {
                return this.attributes["itemSelector"];
            }
            set
            {
                this.attributes["itemSelector"] = value;
            }
        }
        
        public object itemTpl
        {
            get
            {
                return this.attributes["itemTpl"];
            }
            set
            {
                this.attributes["itemTpl"] = value;
            }
        }
        
        public object loadMask
        {
            get
            {
                return this.attributes["loadMask"];
            }
            set
            {
                this.attributes["loadMask"] = value;
            }
        }
        
        public object loadingCls
        {
            get
            {
                return this.attributes["loadingCls"];
            }
            set
            {
                this.attributes["loadingCls"] = value;
            }
        }
        
        public object loadingHeight
        {
            get
            {
                return this.attributes["loadingHeight"];
            }
            set
            {
                this.attributes["loadingHeight"] = value;
            }
        }
        
        public object loadingText
        {
            get
            {
                return this.attributes["loadingText"];
            }
            set
            {
                this.attributes["loadingText"] = value;
            }
        }
        
        public object multiSelect
        {
            get
            {
                return this.attributes["multiSelect"];
            }
            set
            {
                this.attributes["multiSelect"] = value;
            }
        }
        
        public object overItemCls
        {
            get
            {
                return this.attributes["overItemCls"];
            }
            set
            {
                this.attributes["overItemCls"] = value;
            }
        }
        
        public object preserveScrollOnRefresh
        {
            get
            {
                return this.attributes["preserveScrollOnRefresh"];
            }
            set
            {
                this.attributes["preserveScrollOnRefresh"] = value;
            }
        }
        
        public object selectedItemCls
        {
            get
            {
                return this.attributes["selectedItemCls"];
            }
            set
            {
                this.attributes["selectedItemCls"] = value;
            }
        }
        
        public object simpleSelect
        {
            get
            {
                return this.attributes["simpleSelect"];
            }
            set
            {
                this.attributes["simpleSelect"] = value;
            }
        }
        
        public object singleSelect
        {
            get
            {
                return this.attributes["singleSelect"];
            }
            set
            {
                this.attributes["singleSelect"] = value;
            }
        }
        
        public object store
        {
            get
            {
                return this.attributes["store"];
            }
            set
            {
                this.attributes["store"] = value;
            }
        }
        
        public object tpl
        {
            get
            {
                return this.attributes["tpl"];
            }
            set
            {
                this.attributes["tpl"] = value;
            }
        }
        
        public object trackOver
        {
            get
            {
                return this.attributes["trackOver"];
            }
            set
            {
                this.attributes["trackOver"] = value;
            }
        }
        
        public class MultiType_blockRefresh
        {
        }
        
        public class MultiType_deferEmptyText
        {
        }
        
        public class MultiType_deferInitialRefresh
        {
        }
        
        public class MultiType_disableSelection
        {
        }
        
        public class MultiType_emptyText
        {
        }
        
        public class MultiType_itemCls
        {
        }
        
        public class MultiType_itemSelector
        {
        }
        
        public class MultiType_itemTpl
        {
        }
        
        public class MultiType_loadMask
        {
        }
        
        public class MultiType_loadingCls
        {
        }
        
        public class MultiType_loadingHeight
        {
        }
        
        public class MultiType_loadingText
        {
        }
        
        public class MultiType_multiSelect
        {
        }
        
        public class MultiType_overItemCls
        {
        }
        
        public class MultiType_preserveScrollOnRefresh
        {
        }
        
        public class MultiType_selectedItemCls
        {
        }
        
        public class MultiType_simpleSelect
        {
        }
        
        public class MultiType_singleSelect
        {
        }
        
        public class MultiType_store
        {
        }
        
        public class MultiType_tpl
        {
        }
        
        public class MultiType_trackOver
        {
        }
    }
}
