//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class Time : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field.ComboBox
    {
        
        public string _altFormats_default = "\"g:ia|g:iA|g:i a|g:i A|h:i|g:i|H:i|ga|ha|gA|h a|g a|g A|gi|hi|gia|hia|g|H|gi a|hi" +
            " a|giA|hiA|gi A|hi A\"";
        
        public string _displayField_default = "\'disp\'";
        
        public string _format_default = "undefined";
        
        public string _increment_default = "15";
        
        public string _invalidText_default = "\"{0} is not a valid time\"";
        
        public string _maxText_default = "\"The time in this field must be equal to or before {0}\"";
        
        public string _minText_default = "\"The time in this field must be equal to or after {0}\"";
        
        public string _pickerMaxHeight_default = "300";
        
        public string _queryMode_default = "\'local\'";
        
        public string _selectOnTab_default = "true";
        
        public string _snapToIncrement_default = "false";
        
        public string _submitFormat_default = "undefined";
        
        public string _triggerCls_default = "\'x-form-time-trigger\'";
        
        public string _valueField_default = "\'date\'";
        
        public object altFormats
        {
            get
            {
                return this.attributes["altFormats"];
            }
            set
            {
                this.attributes["altFormats"] = value;
            }
        }
        
        public object displayField
        {
            get
            {
                return this.attributes["displayField"];
            }
            set
            {
                this.attributes["displayField"] = value;
            }
        }
        
        public object format
        {
            get
            {
                return this.attributes["format"];
            }
            set
            {
                this.attributes["format"] = value;
            }
        }
        
        public object increment
        {
            get
            {
                return this.attributes["increment"];
            }
            set
            {
                this.attributes["increment"] = value;
            }
        }
        
        public object invalidText
        {
            get
            {
                return this.attributes["invalidText"];
            }
            set
            {
                this.attributes["invalidText"] = value;
            }
        }
        
        public object maxText
        {
            get
            {
                return this.attributes["maxText"];
            }
            set
            {
                this.attributes["maxText"] = value;
            }
        }
        
        public object maxValue
        {
            get
            {
                return this.attributes["maxValue"];
            }
            set
            {
                this.attributes["maxValue"] = value;
            }
        }
        
        public object minText
        {
            get
            {
                return this.attributes["minText"];
            }
            set
            {
                this.attributes["minText"] = value;
            }
        }
        
        public object minValue
        {
            get
            {
                return this.attributes["minValue"];
            }
            set
            {
                this.attributes["minValue"] = value;
            }
        }
        
        public object pickerMaxHeight
        {
            get
            {
                return this.attributes["pickerMaxHeight"];
            }
            set
            {
                this.attributes["pickerMaxHeight"] = value;
            }
        }
        
        public object queryMode
        {
            get
            {
                return this.attributes["queryMode"];
            }
            set
            {
                this.attributes["queryMode"] = value;
            }
        }
        
        public object selectOnTab
        {
            get
            {
                return this.attributes["selectOnTab"];
            }
            set
            {
                this.attributes["selectOnTab"] = value;
            }
        }
        
        public object snapToIncrement
        {
            get
            {
                return this.attributes["snapToIncrement"];
            }
            set
            {
                this.attributes["snapToIncrement"] = value;
            }
        }
        
        public object submitFormat
        {
            get
            {
                return this.attributes["submitFormat"];
            }
            set
            {
                this.attributes["submitFormat"] = value;
            }
        }
        
        public object triggerCls
        {
            get
            {
                return this.attributes["triggerCls"];
            }
            set
            {
                this.attributes["triggerCls"] = value;
            }
        }
        
        public object valueField
        {
            get
            {
                return this.attributes["valueField"];
            }
            set
            {
                this.attributes["valueField"] = value;
            }
        }
        
        public class MultiType_altFormats
        {
        }
        
        public class MultiType_displayField
        {
        }
        
        public class MultiType_format
        {
        }
        
        public class MultiType_increment
        {
        }
        
        public class MultiType_invalidText
        {
        }
        
        public class MultiType_maxText
        {
        }
        
        public class MultiType_maxValue
        {
        }
        
        public class MultiType_minText
        {
        }
        
        public class MultiType_minValue
        {
        }
        
        public class MultiType_pickerMaxHeight
        {
        }
        
        public class MultiType_queryMode
        {
        }
        
        public class MultiType_selectOnTab
        {
        }
        
        public class MultiType_snapToIncrement
        {
        }
        
        public class MultiType_submitFormat
        {
        }
        
        public class MultiType_triggerCls
        {
        }
        
        public class MultiType_valueField
        {
        }
    }
}
