//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Cartesian : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series.Series
    {
        
        public string _axis_default = "\'left\'";
        
        public object axis
        {
            get
            {
                return this.attributes["axis"];
            }
            set
            {
                this.attributes["axis"] = value;
            }
        }
        
        public object xField
        {
            get
            {
                return this.attributes["xField"];
            }
            set
            {
                this.attributes["xField"] = value;
            }
        }
        
        public object yField
        {
            get
            {
                return this.attributes["yField"];
            }
            set
            {
                this.attributes["yField"] = value;
            }
        }
        
        public class MultiType_axis
        {
        }
        
        public class MultiType_xField
        {
        }
        
        public class MultiType_yField
        {
        }
    }
}
