//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis
{
    using System;
    
    
    public partial class Gauge : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis.Abstract
    {
        
        public string _margin_default = "10";
        
        public object margin
        {
            get
            {
                return this.attributes["margin"];
            }
            set
            {
                this.attributes["margin"] = value;
            }
        }
        
        public object maximum
        {
            get
            {
                return this.attributes["maximum"];
            }
            set
            {
                this.attributes["maximum"] = value;
            }
        }
        
        public object minimum
        {
            get
            {
                return this.attributes["minimum"];
            }
            set
            {
                this.attributes["minimum"] = value;
            }
        }
        
        public object steps
        {
            get
            {
                return this.attributes["steps"];
            }
            set
            {
                this.attributes["steps"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public class MultiType_margin
        {
        }
        
        public class MultiType_maximum
        {
        }
        
        public class MultiType_minimum
        {
        }
        
        public class MultiType_steps
        {
        }
        
        public class MultiType_title
        {
        }
    }
}
