//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tree
{
    using System;
    
    
    public partial class ViewDropZone : zzProject.ExtJSNet.ExtJS.Classes.Ext.view.DropZone
    {
        
        public string _allowParentInserts_default = "false";
        
        public string _appendOnly_default = "false";
        
        public string _expandDelay_default = "500";
        
        public object allowContainerDrop
        {
            get
            {
                return this.attributes["allowContainerDrop"];
            }
            set
            {
                this.attributes["allowContainerDrop"] = value;
            }
        }
        
        public object allowParentInserts
        {
            get
            {
                return this.attributes["allowParentInserts"];
            }
            set
            {
                this.attributes["allowParentInserts"] = value;
            }
        }
        
        public object appendOnly
        {
            get
            {
                return this.attributes["appendOnly"];
            }
            set
            {
                this.attributes["appendOnly"] = value;
            }
        }
        
        public object expandDelay
        {
            get
            {
                return this.attributes["expandDelay"];
            }
            set
            {
                this.attributes["expandDelay"] = value;
            }
        }
        
        public class MultiType_allowContainerDrop
        {
        }
        
        public class MultiType_allowParentInserts
        {
        }
        
        public class MultiType_appendOnly
        {
        }
        
        public class MultiType_expandDelay
        {
        }
    }
}
