//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class KeyNav : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _defaultEventAction_default = "\"stopEvent\"";
        
        public string _disabled_default = "false";
        
        public string _eventName_default = "\'keypress\'";
        
        public string _forceKeyDown_default = "false";
        
        public string _ignoreInputFields_default = "false";
        
        public string _processEventScope_default = "this";
        
        public object defaultEventAction
        {
            get
            {
                return this.attributes["defaultEventAction"];
            }
            set
            {
                this.attributes["defaultEventAction"] = value;
            }
        }
        
        public object disabled
        {
            get
            {
                return this.attributes["disabled"];
            }
            set
            {
                this.attributes["disabled"] = value;
            }
        }
        
        public object eventName
        {
            get
            {
                return this.attributes["eventName"];
            }
            set
            {
                this.attributes["eventName"] = value;
            }
        }
        
        public object forceKeyDown
        {
            get
            {
                return this.attributes["forceKeyDown"];
            }
            set
            {
                this.attributes["forceKeyDown"] = value;
            }
        }
        
        public object ignoreInputFields
        {
            get
            {
                return this.attributes["ignoreInputFields"];
            }
            set
            {
                this.attributes["ignoreInputFields"] = value;
            }
        }
        
        public object keyMap
        {
            get
            {
                return this.attributes["keyMap"];
            }
            set
            {
                this.attributes["keyMap"] = value;
            }
        }
        
        public object processEvent
        {
            get
            {
                return this.attributes["processEvent"];
            }
            set
            {
                this.attributes["processEvent"] = value;
            }
        }
        
        public object processEventScope
        {
            get
            {
                return this.attributes["processEventScope"];
            }
            set
            {
                this.attributes["processEventScope"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public class MultiType_defaultEventAction
        {
        }
        
        public class MultiType_disabled
        {
        }
        
        public class MultiType_eventName
        {
        }
        
        public class MultiType_forceKeyDown
        {
        }
        
        public class MultiType_ignoreInputFields
        {
        }
        
        public class MultiType_keyMap
        {
        }
        
        public class MultiType_processEvent
        {
        }
        
        public class MultiType_processEventScope
        {
        }
        
        public class MultiType_target
        {
        }
    }
}
