//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.direct
{
    using System;
    
    
    public partial class RemotingProvider : zzProject.ExtJSNet.ExtJS.Classes.Ext.direct.JsonProvider
    {
        
        public string _disableNestedActions_default = "false";
        
        public string _enableBuffer_default = "10";
        
        public string _enableUrlEncode_default = "data";
        
        public string _maxRetries_default = "1";
        
        public object actions
        {
            get
            {
                return this.attributes["actions"];
            }
            set
            {
                this.attributes["actions"] = value;
            }
        }
        
        public object disableNestedActions
        {
            get
            {
                return this.attributes["disableNestedActions"];
            }
            set
            {
                this.attributes["disableNestedActions"] = value;
            }
        }
        
        public object enableBuffer
        {
            get
            {
                return this.attributes["enableBuffer"];
            }
            set
            {
                this.attributes["enableBuffer"] = value;
            }
        }
        
        public object enableUrlEncode
        {
            get
            {
                return this.attributes["enableUrlEncode"];
            }
            set
            {
                this.attributes["enableUrlEncode"] = value;
            }
        }
        
        public object maxRetries
        {
            get
            {
                return this.attributes["maxRetries"];
            }
            set
            {
                this.attributes["maxRetries"] = value;
            }
        }
        
        public object _namespace
        {
            get
            {
                return this.attributes["namespace"];
            }
            set
            {
                this.attributes["namespace"] = value;
            }
        }
        
        public object timeout
        {
            get
            {
                return this.attributes["timeout"];
            }
            set
            {
                this.attributes["timeout"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public class MultiType_actions
        {
        }
        
        public class MultiType_disableNestedActions
        {
        }
        
        public class MultiType_enableBuffer
        {
        }
        
        public class MultiType_enableUrlEncode
        {
        }
        
        public class MultiType_maxRetries
        {
        }
        
        public class MultiType_namespace
        {
        }
        
        public class MultiType_timeout
        {
        }
        
        public class MultiType_url
        {
        }
    }
}
