//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class RadioGroup : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.CheckboxGroup
    {
        
        public string _allowBlank_default = "true";
        
        public string _blankText_default = "\'You must select one item in this group\'";
        
        public string _defaultType_default = "\'radiofield\'";
        
        public object allowBlank
        {
            get
            {
                return this.attributes["allowBlank"];
            }
            set
            {
                this.attributes["allowBlank"] = value;
            }
        }
        
        public object blankText
        {
            get
            {
                return this.attributes["blankText"];
            }
            set
            {
                this.attributes["blankText"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public class MultiType_allowBlank
        {
        }
        
        public class MultiType_blankText
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_items
        {
        }
    }
}
