//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class Editor : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _alignment_default = "\'c-c?\'";
        
        public string _allowBlur_default = "true";
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'editor\'";
        
        public string _cancelOnEsc_default = "true";
        
        public string _completeOnEnter_default = "true";
        
        public string _constrain_default = "false";
        
        public string _focusOnToFront_default = "false";
        
        public string _hidden_default = "true";
        
        public string _hideEl_default = "true";
        
        public string _ignoreNoChange_default = "false";
        
        public string _layout_default = "\'editor\'";
        
        public string _offsets_default = "[0, 0]";
        
        public string _parentEl_default = "document.body";
        
        public string _revertInvalid_default = "true";
        
        public string _shadow_default = "\'frame\'";
        
        public string _swallowKeys_default = "true";
        
        public string _updateEl_default = "false";
        
        public string _value_default = "\'\'";
        
        public object alignment
        {
            get
            {
                return this.attributes["alignment"];
            }
            set
            {
                this.attributes["alignment"] = value;
            }
        }
        
        public object allowBlur
        {
            get
            {
                return this.attributes["allowBlur"];
            }
            set
            {
                this.attributes["allowBlur"] = value;
            }
        }
        
        public object autoSize
        {
            get
            {
                return this.attributes["autoSize"];
            }
            set
            {
                this.attributes["autoSize"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object cancelOnEsc
        {
            get
            {
                return this.attributes["cancelOnEsc"];
            }
            set
            {
                this.attributes["cancelOnEsc"] = value;
            }
        }
        
        public object completeOnEnter
        {
            get
            {
                return this.attributes["completeOnEnter"];
            }
            set
            {
                this.attributes["completeOnEnter"] = value;
            }
        }
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object field
        {
            get
            {
                return this.attributes["field"];
            }
            set
            {
                this.attributes["field"] = value;
            }
        }
        
        public object focusOnToFront
        {
            get
            {
                return this.attributes["focusOnToFront"];
            }
            set
            {
                this.attributes["focusOnToFront"] = value;
            }
        }
        
        public object hidden
        {
            get
            {
                return this.attributes["hidden"];
            }
            set
            {
                this.attributes["hidden"] = value;
            }
        }
        
        public object hideEl
        {
            get
            {
                return this.attributes["hideEl"];
            }
            set
            {
                this.attributes["hideEl"] = value;
            }
        }
        
        public object ignoreNoChange
        {
            get
            {
                return this.attributes["ignoreNoChange"];
            }
            set
            {
                this.attributes["ignoreNoChange"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object offsets
        {
            get
            {
                return this.attributes["offsets"];
            }
            set
            {
                this.attributes["offsets"] = value;
            }
        }
        
        public object parentEl
        {
            get
            {
                return this.attributes["parentEl"];
            }
            set
            {
                this.attributes["parentEl"] = value;
            }
        }
        
        public object revertInvalid
        {
            get
            {
                return this.attributes["revertInvalid"];
            }
            set
            {
                this.attributes["revertInvalid"] = value;
            }
        }
        
        public object shadow
        {
            get
            {
                return this.attributes["shadow"];
            }
            set
            {
                this.attributes["shadow"] = value;
            }
        }
        
        public object swallowKeys
        {
            get
            {
                return this.attributes["swallowKeys"];
            }
            set
            {
                this.attributes["swallowKeys"] = value;
            }
        }
        
        public object updateEl
        {
            get
            {
                return this.attributes["updateEl"];
            }
            set
            {
                this.attributes["updateEl"] = value;
            }
        }
        
        public object value
        {
            get
            {
                return this.attributes["value"];
            }
            set
            {
                this.attributes["value"] = value;
            }
        }
        
        public class MultiType_alignment
        {
        }
        
        public class MultiType_allowBlur
        {
        }
        
        public class MultiType_autoSize
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_cancelOnEsc
        {
        }
        
        public class MultiType_completeOnEnter
        {
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_field
        {
        }
        
        public class MultiType_focusOnToFront
        {
        }
        
        public class MultiType_hidden
        {
        }
        
        public class MultiType_hideEl
        {
        }
        
        public class MultiType_ignoreNoChange
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_offsets
        {
        }
        
        public class MultiType_parentEl
        {
        }
        
        public class MultiType_revertInvalid
        {
        }
        
        public class MultiType_shadow
        {
        }
        
        public class MultiType_swallowKeys
        {
        }
        
        public class MultiType_updateEl
        {
        }
        
        public class MultiType_value
        {
        }
    }
}
