//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.toolbar
{
    using System;
    
    
    public partial class Toolbar : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'toolbar\'";
        
        public string _defaultType_default = "\'button\'";
        
        public string _enableOverflow_default = "false";
        
        public string _menuTriggerCls_default = "Ext.baseCSSPrefix + \'toolbar-more-icon\'";
        
        public string _vertical_default = "false";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object defaultButtonUI
        {
            get
            {
                return this.attributes["defaultButtonUI"];
            }
            set
            {
                this.attributes["defaultButtonUI"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object enableOverflow
        {
            get
            {
                return this.attributes["enableOverflow"];
            }
            set
            {
                this.attributes["enableOverflow"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object menuTriggerCls
        {
            get
            {
                return this.attributes["menuTriggerCls"];
            }
            set
            {
                this.attributes["menuTriggerCls"] = value;
            }
        }
        
        public object vertical
        {
            get
            {
                return this.attributes["vertical"];
            }
            set
            {
                this.attributes["vertical"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_defaultButtonUI
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_enableOverflow
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_menuTriggerCls
        {
        }
        
        public class MultiType_vertical
        {
        }
    }
}
