//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class Img : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _alt_default = "\'\'";
        
        public string _autoEl_default = "\'img\'";
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'img\'";
        
        public string _imgCls_default = "\'\'";
        
        public string _src_default = "\'\'";
        
        public string _title_default = "\'\'";
        
        public object alt
        {
            get
            {
                return this.attributes["alt"];
            }
            set
            {
                this.attributes["alt"] = value;
            }
        }
        
        public object autoEl
        {
            get
            {
                return this.attributes["autoEl"];
            }
            set
            {
                this.attributes["autoEl"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object glyph
        {
            get
            {
                return this.attributes["glyph"];
            }
            set
            {
                this.attributes["glyph"] = value;
            }
        }
        
        public object imgCls
        {
            get
            {
                return this.attributes["imgCls"];
            }
            set
            {
                this.attributes["imgCls"] = value;
            }
        }
        
        public object src
        {
            get
            {
                return this.attributes["src"];
            }
            set
            {
                this.attributes["src"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public class MultiType_alt
        {
        }
        
        public class MultiType_autoEl
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_glyph
        {
        }
        
        public class MultiType_imgCls
        {
        }
        
        public class MultiType_src
        {
        }
        
        public class MultiType_title
        {
        }
    }
}
