//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.window
{
    using System;
    
    
    public partial class Window : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Panel
    {
        
        public string _animateTarget_default = "null";
        
        public string _autoRender_default = "true";
        
        public string _baseCls_default = "\'x-window\'";
        
        public string _closable_default = "true";
        
        public string _collapsed_default = "false";
        
        public string _collapsible_default = "false";
        
        public string _constrain_default = "false";
        
        public string _constrainHeader_default = "false";
        
        public string _draggable_default = "true";
        
        public string _expandOnShow_default = "true";
        
        public string _hidden_default = "true";
        
        public string _hideMode_default = "\'offsets\'";
        
        public string _hideShadowOnDeactivate_default = "false";
        
        public string _maximizable_default = "false";
        
        public string _maximized_default = "false";
        
        public string _minHeight_default = "50";
        
        public string _minWidth_default = "50";
        
        public string _minimizable_default = "false";
        
        public string _modal_default = "false";
        
        public string _overlapHeader_default = "true";
        
        public string _plain_default = "false";
        
        public string _resizable_default = "true";
        
        public object animateTarget
        {
            get
            {
                return this.attributes["animateTarget"];
            }
            set
            {
                this.attributes["animateTarget"] = value;
            }
        }
        
        public object autoRender
        {
            get
            {
                return this.attributes["autoRender"];
            }
            set
            {
                this.attributes["autoRender"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object closable
        {
            get
            {
                return this.attributes["closable"];
            }
            set
            {
                this.attributes["closable"] = value;
            }
        }
        
        public object collapsed
        {
            get
            {
                return this.attributes["collapsed"];
            }
            set
            {
                this.attributes["collapsed"] = value;
            }
        }
        
        public object collapsible
        {
            get
            {
                return this.attributes["collapsible"];
            }
            set
            {
                this.attributes["collapsible"] = value;
            }
        }
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object constrainHeader
        {
            get
            {
                return this.attributes["constrainHeader"];
            }
            set
            {
                this.attributes["constrainHeader"] = value;
            }
        }
        
        public object defaultFocus
        {
            get
            {
                return this.attributes["defaultFocus"];
            }
            set
            {
                this.attributes["defaultFocus"] = value;
            }
        }
        
        public object draggable
        {
            get
            {
                return this.attributes["draggable"];
            }
            set
            {
                this.attributes["draggable"] = value;
            }
        }
        
        public object expandOnShow
        {
            get
            {
                return this.attributes["expandOnShow"];
            }
            set
            {
                this.attributes["expandOnShow"] = value;
            }
        }
        
        public object ghost
        {
            get
            {
                return this.attributes["ghost"];
            }
            set
            {
                this.attributes["ghost"] = value;
            }
        }
        
        public object hidden
        {
            get
            {
                return this.attributes["hidden"];
            }
            set
            {
                this.attributes["hidden"] = value;
            }
        }
        
        public object hideMode
        {
            get
            {
                return this.attributes["hideMode"];
            }
            set
            {
                this.attributes["hideMode"] = value;
            }
        }
        
        public object hideShadowOnDeactivate
        {
            get
            {
                return this.attributes["hideShadowOnDeactivate"];
            }
            set
            {
                this.attributes["hideShadowOnDeactivate"] = value;
            }
        }
        
        public object maximizable
        {
            get
            {
                return this.attributes["maximizable"];
            }
            set
            {
                this.attributes["maximizable"] = value;
            }
        }
        
        public object maximized
        {
            get
            {
                return this.attributes["maximized"];
            }
            set
            {
                this.attributes["maximized"] = value;
            }
        }
        
        public object minHeight
        {
            get
            {
                return this.attributes["minHeight"];
            }
            set
            {
                this.attributes["minHeight"] = value;
            }
        }
        
        public object minWidth
        {
            get
            {
                return this.attributes["minWidth"];
            }
            set
            {
                this.attributes["minWidth"] = value;
            }
        }
        
        public object minimizable
        {
            get
            {
                return this.attributes["minimizable"];
            }
            set
            {
                this.attributes["minimizable"] = value;
            }
        }
        
        public object modal
        {
            get
            {
                return this.attributes["modal"];
            }
            set
            {
                this.attributes["modal"] = value;
            }
        }
        
        public object onEsc
        {
            get
            {
                return this.attributes["onEsc"];
            }
            set
            {
                this.attributes["onEsc"] = value;
            }
        }
        
        public object overlapHeader
        {
            get
            {
                return this.attributes["overlapHeader"];
            }
            set
            {
                this.attributes["overlapHeader"] = value;
            }
        }
        
        public object plain
        {
            get
            {
                return this.attributes["plain"];
            }
            set
            {
                this.attributes["plain"] = value;
            }
        }
        
        public object resizable
        {
            get
            {
                return this.attributes["resizable"];
            }
            set
            {
                this.attributes["resizable"] = value;
            }
        }
        
        public object x
        {
            get
            {
                return this.attributes["x"];
            }
            set
            {
                this.attributes["x"] = value;
            }
        }
        
        public object y
        {
            get
            {
                return this.attributes["y"];
            }
            set
            {
                this.attributes["y"] = value;
            }
        }
        
        public class MultiType_animateTarget
        {
        }
        
        public class MultiType_autoRender
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_closable
        {
        }
        
        public class MultiType_collapsed
        {
        }
        
        public class MultiType_collapsible
        {
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_constrainHeader
        {
        }
        
        public class MultiType_defaultFocus
        {
        }
        
        public class MultiType_draggable
        {
        }
        
        public class MultiType_expandOnShow
        {
        }
        
        public class MultiType_ghost
        {
        }
        
        public class MultiType_hidden
        {
        }
        
        public class MultiType_hideMode
        {
        }
        
        public class MultiType_hideShadowOnDeactivate
        {
        }
        
        public class MultiType_maximizable
        {
        }
        
        public class MultiType_maximized
        {
        }
        
        public class MultiType_minHeight
        {
        }
        
        public class MultiType_minWidth
        {
        }
        
        public class MultiType_minimizable
        {
        }
        
        public class MultiType_modal
        {
        }
        
        public class MultiType_onEsc
        {
        }
        
        public class MultiType_overlapHeader
        {
        }
        
        public class MultiType_plain
        {
        }
        
        public class MultiType_resizable
        {
        }
        
        public class MultiType_x
        {
        }
        
        public class MultiType_y
        {
        }
    }
}
