//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.app
{
    using System;
    
    
    public partial class Controller : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object id
        {
            get
            {
                return this.attributes["id"];
            }
            set
            {
                this.attributes["id"] = value;
            }
        }
        
        public object models
        {
            get
            {
                return this.attributes["models"];
            }
            set
            {
                this.attributes["models"] = value;
            }
        }
        
        public object refs
        {
            get
            {
                return this.attributes["refs"];
            }
            set
            {
                this.attributes["refs"] = value;
            }
        }
        
        public object stores
        {
            get
            {
                return this.attributes["stores"];
            }
            set
            {
                this.attributes["stores"] = value;
            }
        }
        
        public object views
        {
            get
            {
                return this.attributes["views"];
            }
            set
            {
                this.attributes["views"] = value;
            }
        }
        
        public class MultiType_id
        {
        }
        
        public class MultiType_models
        {
        }
        
        public class MultiType_refs
        {
        }
        
        public class MultiType_stores
        {
        }
        
        public class MultiType_views
        {
        }
    }
}
