//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class Action : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _disabled_default = "false";
        
        public string _hidden_default = "false";
        
        public string _iconCls_default = "\'\'";
        
        public string _text_default = "\'\'";
        
        public object disabled
        {
            get
            {
                return this.attributes["disabled"];
            }
            set
            {
                this.attributes["disabled"] = value;
            }
        }
        
        public object handler
        {
            get
            {
                return this.attributes["handler"];
            }
            set
            {
                this.attributes["handler"] = value;
            }
        }
        
        public object hidden
        {
            get
            {
                return this.attributes["hidden"];
            }
            set
            {
                this.attributes["hidden"] = value;
            }
        }
        
        public object iconCls
        {
            get
            {
                return this.attributes["iconCls"];
            }
            set
            {
                this.attributes["iconCls"] = value;
            }
        }
        
        public object itemId
        {
            get
            {
                return this.attributes["itemId"];
            }
            set
            {
                this.attributes["itemId"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object text
        {
            get
            {
                return this.attributes["text"];
            }
            set
            {
                this.attributes["text"] = value;
            }
        }
        
        public class MultiType_disabled
        {
        }
        
        public class MultiType_handler
        {
        }
        
        public class MultiType_hidden
        {
        }
        
        public class MultiType_iconCls
        {
        }
        
        public class MultiType_itemId
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_text
        {
        }
    }
}
