//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class Model : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _defaultProxyType_default = "\'ajax\'";
        
        public string _idProperty_default = "\'id\'";
        
        public string _persistenceProperty_default = "\'data\'";
        
        public object associations
        {
            get
            {
                return this.attributes["associations"];
            }
            set
            {
                this.attributes["associations"] = value;
            }
        }
        
        public object belongsTo
        {
            get
            {
                return this.attributes["belongsTo"];
            }
            set
            {
                this.attributes["belongsTo"] = value;
            }
        }
        
        public object clientIdProperty
        {
            get
            {
                return this.attributes["clientIdProperty"];
            }
            set
            {
                this.attributes["clientIdProperty"] = value;
            }
        }
        
        public object defaultProxyType
        {
            get
            {
                return this.attributes["defaultProxyType"];
            }
            set
            {
                this.attributes["defaultProxyType"] = value;
            }
        }
        
        public object fields
        {
            get
            {
                return this.attributes["fields"];
            }
            set
            {
                this.attributes["fields"] = value;
            }
        }
        
        public object hasMany
        {
            get
            {
                return this.attributes["hasMany"];
            }
            set
            {
                this.attributes["hasMany"] = value;
            }
        }
        
        public object idProperty
        {
            get
            {
                return this.attributes["idProperty"];
            }
            set
            {
                this.attributes["idProperty"] = value;
            }
        }
        
        public object idgen
        {
            get
            {
                return this.attributes["idgen"];
            }
            set
            {
                this.attributes["idgen"] = value;
            }
        }
        
        public object persistenceProperty
        {
            get
            {
                return this.attributes["persistenceProperty"];
            }
            set
            {
                this.attributes["persistenceProperty"] = value;
            }
        }
        
        public object proxy
        {
            get
            {
                return this.attributes["proxy"];
            }
            set
            {
                this.attributes["proxy"] = value;
            }
        }
        
        public object validations
        {
            get
            {
                return this.attributes["validations"];
            }
            set
            {
                this.attributes["validations"] = value;
            }
        }
        
        public class MultiType_associations
        {
        }
        
        public class MultiType_belongsTo
        {
        }
        
        public class MultiType_clientIdProperty
        {
        }
        
        public class MultiType_defaultProxyType
        {
        }
        
        public class MultiType_fields
        {
        }
        
        public class MultiType_hasMany
        {
        }
        
        public class MultiType_idProperty
        {
        }
        
        public class MultiType_idgen
        {
        }
        
        public class MultiType_persistenceProperty
        {
        }
        
        public class MultiType_proxy
        {
        }
        
        public class MultiType_validations
        {
        }
    }
}
