//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class XTemplate : zzProject.ExtJSNet.ExtJS.Classes.Ext.Template
    {
        
        public object definitions
        {
            get
            {
                return this.attributes["definitions"];
            }
            set
            {
                this.attributes["definitions"] = value;
            }
        }
        
        public class MultiType_definitions
        {
        }
    }
}
