//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.feature
{
    using System;
    
    
    public partial class Grouping : zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.feature.Feature
    {
        
        public string _collapsible_default = "true";
        
        public string _depthToIndent_default = "17";
        
        public string _enableGroupingMenu_default = "true";
        
        public string _enableNoGroups_default = "true";
        
        public string _groupByText_default = "\"Group by this field\"";
        
        public string _groupHeaderTpl_default = "\'{columnName}: {name}\'";
        
        public string _hideGroupedHeader_default = "false";
        
        public string _showGroupsText_default = "\"Show in groups\"";
        
        public string _showSummaryRow_default = "false";
        
        public string _startCollapsed_default = "false";
        
        public object collapsible
        {
            get
            {
                return this.attributes["collapsible"];
            }
            set
            {
                this.attributes["collapsible"] = value;
            }
        }
        
        public object depthToIndent
        {
            get
            {
                return this.attributes["depthToIndent"];
            }
            set
            {
                this.attributes["depthToIndent"] = value;
            }
        }
        
        public object enableGroupingMenu
        {
            get
            {
                return this.attributes["enableGroupingMenu"];
            }
            set
            {
                this.attributes["enableGroupingMenu"] = value;
            }
        }
        
        public object enableNoGroups
        {
            get
            {
                return this.attributes["enableNoGroups"];
            }
            set
            {
                this.attributes["enableNoGroups"] = value;
            }
        }
        
        public object groupByText
        {
            get
            {
                return this.attributes["groupByText"];
            }
            set
            {
                this.attributes["groupByText"] = value;
            }
        }
        
        public object groupHeaderTpl
        {
            get
            {
                return this.attributes["groupHeaderTpl"];
            }
            set
            {
                this.attributes["groupHeaderTpl"] = value;
            }
        }
        
        public object hideGroupedHeader
        {
            get
            {
                return this.attributes["hideGroupedHeader"];
            }
            set
            {
                this.attributes["hideGroupedHeader"] = value;
            }
        }
        
        public object showGroupsText
        {
            get
            {
                return this.attributes["showGroupsText"];
            }
            set
            {
                this.attributes["showGroupsText"] = value;
            }
        }
        
        public object showSummaryRow
        {
            get
            {
                return this.attributes["showSummaryRow"];
            }
            set
            {
                this.attributes["showSummaryRow"] = value;
            }
        }
        
        public object startCollapsed
        {
            get
            {
                return this.attributes["startCollapsed"];
            }
            set
            {
                this.attributes["startCollapsed"] = value;
            }
        }
        
        public class MultiType_collapsible
        {
        }
        
        public class MultiType_depthToIndent
        {
        }
        
        public class MultiType_enableGroupingMenu
        {
        }
        
        public class MultiType_enableNoGroups
        {
        }
        
        public class MultiType_groupByText
        {
        }
        
        public class MultiType_groupHeaderTpl
        {
        }
        
        public class MultiType_hideGroupedHeader
        {
        }
        
        public class MultiType_showGroupsText
        {
        }
        
        public class MultiType_showSummaryRow
        {
        }
        
        public class MultiType_startCollapsed
        {
        }
    }
}
