//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class Radio : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field.Checkbox
    {
        
        public string _focusCls_default = "\'x-form-radio-focus\'";
        
        public string _inputType_default = "\'radio\'";
        
        public object focusCls
        {
            get
            {
                return this.attributes["focusCls"];
            }
            set
            {
                this.attributes["focusCls"] = value;
            }
        }
        
        public object inputType
        {
            get
            {
                return this.attributes["inputType"];
            }
            set
            {
                this.attributes["inputType"] = value;
            }
        }
        
        public class MultiType_focusCls
        {
        }
        
        public class MultiType_inputType
        {
        }
    }
}
