//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.plugin
{
    using System;
    
    
    public partial class DragDrop : zzProject.ExtJSNet.ExtJS.Classes.Ext.AbstractPlugin
    {
        
        public string _containerScroll_default = "false";
        
        public string _ddGroup_default = "\"GridDD\"";
        
        public string _dragText_default = "\'{0} selected row{1}\'";
        
        public string _enableDrag_default = "true";
        
        public string _enableDrop_default = "true";
        
        public object containerScroll
        {
            get
            {
                return this.attributes["containerScroll"];
            }
            set
            {
                this.attributes["containerScroll"] = value;
            }
        }
        
        public object ddGroup
        {
            get
            {
                return this.attributes["ddGroup"];
            }
            set
            {
                this.attributes["ddGroup"] = value;
            }
        }
        
        public object dragGroup
        {
            get
            {
                return this.attributes["dragGroup"];
            }
            set
            {
                this.attributes["dragGroup"] = value;
            }
        }
        
        public object dragText
        {
            get
            {
                return this.attributes["dragText"];
            }
            set
            {
                this.attributes["dragText"] = value;
            }
        }
        
        public object dropGroup
        {
            get
            {
                return this.attributes["dropGroup"];
            }
            set
            {
                this.attributes["dropGroup"] = value;
            }
        }
        
        public object enableDrag
        {
            get
            {
                return this.attributes["enableDrag"];
            }
            set
            {
                this.attributes["enableDrag"] = value;
            }
        }
        
        public object enableDrop
        {
            get
            {
                return this.attributes["enableDrop"];
            }
            set
            {
                this.attributes["enableDrop"] = value;
            }
        }
        
        public class MultiType_containerScroll
        {
        }
        
        public class MultiType_ddGroup
        {
        }
        
        public class MultiType_dragGroup
        {
        }
        
        public class MultiType_dragText
        {
        }
        
        public class MultiType_dropGroup
        {
        }
        
        public class MultiType_enableDrag
        {
        }
        
        public class MultiType_enableDrop
        {
        }
    }
}
