//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.panel
{
    using System;
    
    
    public partial class Table : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Panel
    {
        
        public string _allowDeselect_default = "false";
        
        public string _disableSelection_default = "false";
        
        public string _enableColumnHide_default = "true";
        
        public string _enableColumnMove_default = "true";
        
        public string _enableColumnResize_default = "true";
        
        public string _enableLocking_default = "false";
        
        public string _hideHeaders_default = "false";
        
        public string _layout_default = "\'fit\'";
        
        public string _multiSelect_default = "false";
        
        public string _rowLines_default = "true";
        
        public string _scroll_default = "true";
        
        public string _sealedColumns_default = "false";
        
        public string _selType_default = "\'rowmodel\'";
        
        public string _simpleSelect_default = "false";
        
        public string _sortableColumns_default = "true";
        
        public object allowDeselect
        {
            get
            {
                return this.attributes["allowDeselect"];
            }
            set
            {
                this.attributes["allowDeselect"] = value;
            }
        }
        
        public object columnLines
        {
            get
            {
                return this.attributes["columnLines"];
            }
            set
            {
                this.attributes["columnLines"] = value;
            }
        }
        
        public object columns
        {
            get
            {
                return this.attributes["columns"];
            }
            set
            {
                this.attributes["columns"] = value;
            }
        }
        
        public object deferRowRender
        {
            get
            {
                return this.attributes["deferRowRender"];
            }
            set
            {
                this.attributes["deferRowRender"] = value;
            }
        }
        
        public object disableSelection
        {
            get
            {
                return this.attributes["disableSelection"];
            }
            set
            {
                this.attributes["disableSelection"] = value;
            }
        }
        
        public object emptyText
        {
            get
            {
                return this.attributes["emptyText"];
            }
            set
            {
                this.attributes["emptyText"] = value;
            }
        }
        
        public object enableColumnHide
        {
            get
            {
                return this.attributes["enableColumnHide"];
            }
            set
            {
                this.attributes["enableColumnHide"] = value;
            }
        }
        
        public object enableColumnMove
        {
            get
            {
                return this.attributes["enableColumnMove"];
            }
            set
            {
                this.attributes["enableColumnMove"] = value;
            }
        }
        
        public object enableColumnResize
        {
            get
            {
                return this.attributes["enableColumnResize"];
            }
            set
            {
                this.attributes["enableColumnResize"] = value;
            }
        }
        
        public object enableLocking
        {
            get
            {
                return this.attributes["enableLocking"];
            }
            set
            {
                this.attributes["enableLocking"] = value;
            }
        }
        
        public object features
        {
            get
            {
                return this.attributes["features"];
            }
            set
            {
                this.attributes["features"] = value;
            }
        }
        
        public object forceFit
        {
            get
            {
                return this.attributes["forceFit"];
            }
            set
            {
                this.attributes["forceFit"] = value;
            }
        }
        
        public object hideHeaders
        {
            get
            {
                return this.attributes["hideHeaders"];
            }
            set
            {
                this.attributes["hideHeaders"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object multiSelect
        {
            get
            {
                return this.attributes["multiSelect"];
            }
            set
            {
                this.attributes["multiSelect"] = value;
            }
        }
        
        public object rowLines
        {
            get
            {
                return this.attributes["rowLines"];
            }
            set
            {
                this.attributes["rowLines"] = value;
            }
        }
        
        public object scroll
        {
            get
            {
                return this.attributes["scroll"];
            }
            set
            {
                this.attributes["scroll"] = value;
            }
        }
        
        public object sealedColumns
        {
            get
            {
                return this.attributes["sealedColumns"];
            }
            set
            {
                this.attributes["sealedColumns"] = value;
            }
        }
        
        public object selModel
        {
            get
            {
                return this.attributes["selModel"];
            }
            set
            {
                this.attributes["selModel"] = value;
            }
        }
        
        public object selType
        {
            get
            {
                return this.attributes["selType"];
            }
            set
            {
                this.attributes["selType"] = value;
            }
        }
        
        public object simpleSelect
        {
            get
            {
                return this.attributes["simpleSelect"];
            }
            set
            {
                this.attributes["simpleSelect"] = value;
            }
        }
        
        public object sortableColumns
        {
            get
            {
                return this.attributes["sortableColumns"];
            }
            set
            {
                this.attributes["sortableColumns"] = value;
            }
        }
        
        public object store
        {
            get
            {
                return this.attributes["store"];
            }
            set
            {
                this.attributes["store"] = value;
            }
        }
        
        public object verticalScroller
        {
            get
            {
                return this.attributes["verticalScroller"];
            }
            set
            {
                this.attributes["verticalScroller"] = value;
            }
        }
        
        public object view
        {
            get
            {
                return this.attributes["view"];
            }
            set
            {
                this.attributes["view"] = value;
            }
        }
        
        public object viewConfig
        {
            get
            {
                return this.attributes["viewConfig"];
            }
            set
            {
                this.attributes["viewConfig"] = value;
            }
        }
        
        public object viewType
        {
            get
            {
                return this.attributes["viewType"];
            }
            set
            {
                this.attributes["viewType"] = value;
            }
        }
        
        public class MultiType_allowDeselect
        {
        }
        
        public class MultiType_columnLines
        {
        }
        
        public class MultiType_columns
        {
        }
        
        public class MultiType_deferRowRender
        {
        }
        
        public class MultiType_disableSelection
        {
        }
        
        public class MultiType_emptyText
        {
        }
        
        public class MultiType_enableColumnHide
        {
        }
        
        public class MultiType_enableColumnMove
        {
        }
        
        public class MultiType_enableColumnResize
        {
        }
        
        public class MultiType_enableLocking
        {
        }
        
        public class MultiType_features
        {
        }
        
        public class MultiType_forceFit
        {
        }
        
        public class MultiType_hideHeaders
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_multiSelect
        {
        }
        
        public class MultiType_rowLines
        {
        }
        
        public class MultiType_scroll
        {
        }
        
        public class MultiType_sealedColumns
        {
        }
        
        public class MultiType_selModel
        {
        }
        
        public class MultiType_selType
        {
        }
        
        public class MultiType_simpleSelect
        {
        }
        
        public class MultiType_sortableColumns
        {
        }
        
        public class MultiType_store
        {
        }
        
        public class MultiType_verticalScroller
        {
        }
        
        public class MultiType_view
        {
        }
        
        public class MultiType_viewConfig
        {
        }
        
        public class MultiType_viewType
        {
        }
    }
}
