//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext
{
    using System;
    
    
    public partial class Component : zzProject.ExtJSNet.ExtJS.Classes.Ext.AbstractComponent
    {
        
        public string _autoScroll_default = "false";
        
        public string _columnWidth_default = "undefined";
        
        public string _defaultAlign_default = "\"tl-bl?\"";
        
        public string _draggable_default = "false";
        
        public string _floating_default = "false";
        
        public string _formBind_default = "false";
        
        public string _region_default = "undefined";
        
        public string _resizeHandles_default = "\'all\'";
        
        public string _toFrontOnShow_default = "true";
        
        public object autoScroll
        {
            get
            {
                return this.attributes["autoScroll"];
            }
            set
            {
                this.attributes["autoScroll"] = value;
            }
        }
        
        public object columnWidth
        {
            get
            {
                return this.attributes["columnWidth"];
            }
            set
            {
                this.attributes["columnWidth"] = value;
            }
        }
        
        public object constrainTo
        {
            get
            {
                return this.attributes["constrainTo"];
            }
            set
            {
                this.attributes["constrainTo"] = value;
            }
        }
        
        public object constraintInsets
        {
            get
            {
                return this.attributes["constraintInsets"];
            }
            set
            {
                this.attributes["constraintInsets"] = value;
            }
        }
        
        public object defaultAlign
        {
            get
            {
                return this.attributes["defaultAlign"];
            }
            set
            {
                this.attributes["defaultAlign"] = value;
            }
        }
        
        public object draggable
        {
            get
            {
                return this.attributes["draggable"];
            }
            set
            {
                this.attributes["draggable"] = value;
            }
        }
        
        public object floating
        {
            get
            {
                return this.attributes["floating"];
            }
            set
            {
                this.attributes["floating"] = value;
            }
        }
        
        public object formBind
        {
            get
            {
                return this.attributes["formBind"];
            }
            set
            {
                this.attributes["formBind"] = value;
            }
        }
        
        public object overflowX
        {
            get
            {
                return this.attributes["overflowX"];
            }
            set
            {
                this.attributes["overflowX"] = value;
            }
        }
        
        public object overflowY
        {
            get
            {
                return this.attributes["overflowY"];
            }
            set
            {
                this.attributes["overflowY"] = value;
            }
        }
        
        public object region
        {
            get
            {
                return this.attributes["region"];
            }
            set
            {
                this.attributes["region"] = value;
            }
        }
        
        public object resizable
        {
            get
            {
                return this.attributes["resizable"];
            }
            set
            {
                this.attributes["resizable"] = value;
            }
        }
        
        public object resizeHandles
        {
            get
            {
                return this.attributes["resizeHandles"];
            }
            set
            {
                this.attributes["resizeHandles"] = value;
            }
        }
        
        public object toFrontOnShow
        {
            get
            {
                return this.attributes["toFrontOnShow"];
            }
            set
            {
                this.attributes["toFrontOnShow"] = value;
            }
        }
        
        public class MultiType_autoScroll
        {
        }
        
        public class MultiType_columnWidth
        {
        }
        
        public class MultiType_constrainTo
        {
        }
        
        public class MultiType_constraintInsets
        {
        }
        
        public class MultiType_defaultAlign
        {
        }
        
        public class MultiType_draggable
        {
        }
        
        public class MultiType_floating
        {
        }
        
        public class MultiType_formBind
        {
        }
        
        public class MultiType_overflowX
        {
        }
        
        public class MultiType_overflowY
        {
        }
        
        public class MultiType_region
        {
        }
        
        public class MultiType_resizable
        {
        }
        
        public class MultiType_resizeHandles
        {
        }
        
        public class MultiType_toFrontOnShow
        {
        }
    }
}
