//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class Basic : zzProject.ExtJSNet.ExtJS.Classes.Ext.util.Observable
    {
        
        public string _paramsAsHash_default = "false";
        
        public string _timeout_default = "30";
        
        public string _trackResetOnLoad_default = "false";
        
        public string _waitTitle_default = "\'Please Wait...\'";
        
        public object api
        {
            get
            {
                return this.attributes["api"];
            }
            set
            {
                this.attributes["api"] = value;
            }
        }
        
        public object baseParams
        {
            get
            {
                return this.attributes["baseParams"];
            }
            set
            {
                this.attributes["baseParams"] = value;
            }
        }
        
        public object errorReader
        {
            get
            {
                return this.attributes["errorReader"];
            }
            set
            {
                this.attributes["errorReader"] = value;
            }
        }
        
        public object jsonSubmit
        {
            get
            {
                return this.attributes["jsonSubmit"];
            }
            set
            {
                this.attributes["jsonSubmit"] = value;
            }
        }
        
        public object method
        {
            get
            {
                return this.attributes["method"];
            }
            set
            {
                this.attributes["method"] = value;
            }
        }
        
        public object paramOrder
        {
            get
            {
                return this.attributes["paramOrder"];
            }
            set
            {
                this.attributes["paramOrder"] = value;
            }
        }
        
        public object paramsAsHash
        {
            get
            {
                return this.attributes["paramsAsHash"];
            }
            set
            {
                this.attributes["paramsAsHash"] = value;
            }
        }
        
        public object reader
        {
            get
            {
                return this.attributes["reader"];
            }
            set
            {
                this.attributes["reader"] = value;
            }
        }
        
        public object standardSubmit
        {
            get
            {
                return this.attributes["standardSubmit"];
            }
            set
            {
                this.attributes["standardSubmit"] = value;
            }
        }
        
        public object timeout
        {
            get
            {
                return this.attributes["timeout"];
            }
            set
            {
                this.attributes["timeout"] = value;
            }
        }
        
        public object trackResetOnLoad
        {
            get
            {
                return this.attributes["trackResetOnLoad"];
            }
            set
            {
                this.attributes["trackResetOnLoad"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public object waitMsgTarget
        {
            get
            {
                return this.attributes["waitMsgTarget"];
            }
            set
            {
                this.attributes["waitMsgTarget"] = value;
            }
        }
        
        public object waitTitle
        {
            get
            {
                return this.attributes["waitTitle"];
            }
            set
            {
                this.attributes["waitTitle"] = value;
            }
        }
        
        public class MultiType_api
        {
        }
        
        public class MultiType_baseParams
        {
        }
        
        public class MultiType_errorReader
        {
        }
        
        public class MultiType_jsonSubmit
        {
        }
        
        public class MultiType_method
        {
        }
        
        public class MultiType_paramOrder
        {
        }
        
        public class MultiType_paramsAsHash
        {
        }
        
        public class MultiType_reader
        {
        }
        
        public class MultiType_standardSubmit
        {
        }
        
        public class MultiType_timeout
        {
        }
        
        public class MultiType_trackResetOnLoad
        {
        }
        
        public class MultiType_url
        {
        }
        
        public class MultiType_waitMsgTarget
        {
        }
        
        public class MultiType_waitTitle
        {
        }
    }
}
