//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.window
{
    using System;
    
    
    public partial class MessageBox : zzProject.ExtJSNet.ExtJS.Classes.Ext.window.Window
    {
        
        public string _closeAction_default = "\'hide\'";
        
        public string _cls_default = "[Ext.baseCSSPrefix + \'message-box\', Ext.baseCSSPrefix + \'hide-offsets\']";
        
        public string _constrain_default = "true";
        
        public string _hideMode_default = "\'offsets\'";
        
        public string _layout_default = "{type: \'vbox\', align: \'stretch\'}";
        
        public string _minHeight_default = "50";
        
        public string _minWidth_default = "50";
        
        public string _resizable_default = "false";
        
        public string _shrinkWrapDock_default = "true";
        
        public string _title_default = "\'&#160;\'";
        
        public object closeAction
        {
            get
            {
                return this.attributes["closeAction"];
            }
            set
            {
                this.attributes["closeAction"] = value;
            }
        }
        
        public object cls
        {
            get
            {
                return this.attributes["cls"];
            }
            set
            {
                this.attributes["cls"] = value;
            }
        }
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object hideMode
        {
            get
            {
                return this.attributes["hideMode"];
            }
            set
            {
                this.attributes["hideMode"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object maxHeight
        {
            get
            {
                return this.attributes["maxHeight"];
            }
            set
            {
                this.attributes["maxHeight"] = value;
            }
        }
        
        public object maxWidth
        {
            get
            {
                return this.attributes["maxWidth"];
            }
            set
            {
                this.attributes["maxWidth"] = value;
            }
        }
        
        public object minHeight
        {
            get
            {
                return this.attributes["minHeight"];
            }
            set
            {
                this.attributes["minHeight"] = value;
            }
        }
        
        public object minWidth
        {
            get
            {
                return this.attributes["minWidth"];
            }
            set
            {
                this.attributes["minWidth"] = value;
            }
        }
        
        public object resizable
        {
            get
            {
                return this.attributes["resizable"];
            }
            set
            {
                this.attributes["resizable"] = value;
            }
        }
        
        public object shrinkWrapDock
        {
            get
            {
                return this.attributes["shrinkWrapDock"];
            }
            set
            {
                this.attributes["shrinkWrapDock"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public class MultiType_closeAction
        {
        }
        
        public class MultiType_cls
        {
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_hideMode
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_maxHeight
        {
        }
        
        public class MultiType_maxWidth
        {
        }
        
        public class MultiType_minHeight
        {
        }
        
        public class MultiType_minWidth
        {
        }
        
        public class MultiType_resizable
        {
        }
        
        public class MultiType_shrinkWrapDock
        {
        }
        
        public class MultiType_title
        {
        }
    }
}
