//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.toolbar
{
    using System;
    
    
    public partial class Paging : zzProject.ExtJSNet.ExtJS.Classes.Ext.toolbar.Toolbar
    {
        
        public string _afterPageText_default = "\'of {0}\'";
        
        public string _beforePageText_default = "\'Page\'";
        
        public string _displayInfo_default = "false";
        
        public string _displayMsg_default = "\'Displaying {0} - {1} of {2}\'";
        
        public string _emptyMsg_default = "\'No data to display\'";
        
        public string _firstText_default = "\'First Page\'";
        
        public string _inputItemWidth_default = "30";
        
        public string _lastText_default = "\'Last Page\'";
        
        public string _nextText_default = "\'Next Page\'";
        
        public string _prependButtons_default = "false";
        
        public string _prevText_default = "\'Previous Page\'";
        
        public string _refreshText_default = "\'Refresh\'";
        
        public object afterPageText
        {
            get
            {
                return this.attributes["afterPageText"];
            }
            set
            {
                this.attributes["afterPageText"] = value;
            }
        }
        
        public object beforePageText
        {
            get
            {
                return this.attributes["beforePageText"];
            }
            set
            {
                this.attributes["beforePageText"] = value;
            }
        }
        
        public object displayInfo
        {
            get
            {
                return this.attributes["displayInfo"];
            }
            set
            {
                this.attributes["displayInfo"] = value;
            }
        }
        
        public object displayMsg
        {
            get
            {
                return this.attributes["displayMsg"];
            }
            set
            {
                this.attributes["displayMsg"] = value;
            }
        }
        
        public object emptyMsg
        {
            get
            {
                return this.attributes["emptyMsg"];
            }
            set
            {
                this.attributes["emptyMsg"] = value;
            }
        }
        
        public object firstText
        {
            get
            {
                return this.attributes["firstText"];
            }
            set
            {
                this.attributes["firstText"] = value;
            }
        }
        
        public object inputItemWidth
        {
            get
            {
                return this.attributes["inputItemWidth"];
            }
            set
            {
                this.attributes["inputItemWidth"] = value;
            }
        }
        
        public object lastText
        {
            get
            {
                return this.attributes["lastText"];
            }
            set
            {
                this.attributes["lastText"] = value;
            }
        }
        
        public object nextText
        {
            get
            {
                return this.attributes["nextText"];
            }
            set
            {
                this.attributes["nextText"] = value;
            }
        }
        
        public object prependButtons
        {
            get
            {
                return this.attributes["prependButtons"];
            }
            set
            {
                this.attributes["prependButtons"] = value;
            }
        }
        
        public object prevText
        {
            get
            {
                return this.attributes["prevText"];
            }
            set
            {
                this.attributes["prevText"] = value;
            }
        }
        
        public object refreshText
        {
            get
            {
                return this.attributes["refreshText"];
            }
            set
            {
                this.attributes["refreshText"] = value;
            }
        }
        
        public object store
        {
            get
            {
                return this.attributes["store"];
            }
            set
            {
                this.attributes["store"] = value;
            }
        }
        
        public class MultiType_afterPageText
        {
        }
        
        public class MultiType_beforePageText
        {
        }
        
        public class MultiType_displayInfo
        {
        }
        
        public class MultiType_displayMsg
        {
        }
        
        public class MultiType_emptyMsg
        {
        }
        
        public class MultiType_firstText
        {
        }
        
        public class MultiType_inputItemWidth
        {
        }
        
        public class MultiType_lastText
        {
        }
        
        public class MultiType_nextText
        {
        }
        
        public class MultiType_prependButtons
        {
        }
        
        public class MultiType_prevText
        {
        }
        
        public class MultiType_refreshText
        {
        }
        
        public class MultiType_store
        {
        }
    }
}
