//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.column
{
    using System;
    
    
    public partial class Date : zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.column.Column
    {
        
        public object format
        {
            get
            {
                return this.attributes["format"];
            }
            set
            {
                this.attributes["format"] = value;
            }
        }
        
        public class MultiType_format
        {
        }
    }
}
