//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.selection
{
    using System;
    
    
    public partial class CheckboxModel : zzProject.ExtJSNet.ExtJS.Classes.Ext.selection.RowModel
    {
        
        public string _checkOnly_default = "false";
        
        public string _checkSelector_default = "\"x-grid-row-checker\"";
        
        public string _injectCheckbox_default = "0";
        
        public string _mode_default = "\'MULTI\'";
        
        public object checkOnly
        {
            get
            {
                return this.attributes["checkOnly"];
            }
            set
            {
                this.attributes["checkOnly"] = value;
            }
        }
        
        public object checkSelector
        {
            get
            {
                return this.attributes["checkSelector"];
            }
            set
            {
                this.attributes["checkSelector"] = value;
            }
        }
        
        public object injectCheckbox
        {
            get
            {
                return this.attributes["injectCheckbox"];
            }
            set
            {
                this.attributes["injectCheckbox"] = value;
            }
        }
        
        public object mode
        {
            get
            {
                return this.attributes["mode"];
            }
            set
            {
                this.attributes["mode"] = value;
            }
        }
        
        public object showHeaderCheckbox
        {
            get
            {
                return this.attributes["showHeaderCheckbox"];
            }
            set
            {
                this.attributes["showHeaderCheckbox"] = value;
            }
        }
        
        public class MultiType_checkOnly
        {
        }
        
        public class MultiType_checkSelector
        {
        }
        
        public class MultiType_injectCheckbox
        {
        }
        
        public class MultiType_mode
        {
        }
        
        public class MultiType_showHeaderCheckbox
        {
        }
    }
}
