//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class TextArea : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field.Text
    {
        
        public string _cols_default = "20";
        
        public string _componentLayout_default = "\'textareafield\'";
        
        public string _enterIsSpecial_default = "false";
        
        public string _growAppend_default = "\'\\n-\'";
        
        public string _growMax_default = "1000";
        
        public string _growMin_default = "60";
        
        public string _preventScrollbars_default = "false";
        
        public string _rows_default = "4";
        
        public object cols
        {
            get
            {
                return this.attributes["cols"];
            }
            set
            {
                this.attributes["cols"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object enterIsSpecial
        {
            get
            {
                return this.attributes["enterIsSpecial"];
            }
            set
            {
                this.attributes["enterIsSpecial"] = value;
            }
        }
        
        public object growAppend
        {
            get
            {
                return this.attributes["growAppend"];
            }
            set
            {
                this.attributes["growAppend"] = value;
            }
        }
        
        public object growMax
        {
            get
            {
                return this.attributes["growMax"];
            }
            set
            {
                this.attributes["growMax"] = value;
            }
        }
        
        public object growMin
        {
            get
            {
                return this.attributes["growMin"];
            }
            set
            {
                this.attributes["growMin"] = value;
            }
        }
        
        public object preventScrollbars
        {
            get
            {
                return this.attributes["preventScrollbars"];
            }
            set
            {
                this.attributes["preventScrollbars"] = value;
            }
        }
        
        public object rows
        {
            get
            {
                return this.attributes["rows"];
            }
            set
            {
                this.attributes["rows"] = value;
            }
        }
        
        public class MultiType_cols
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_enterIsSpecial
        {
        }
        
        public class MultiType_growAppend
        {
        }
        
        public class MultiType_growMax
        {
        }
        
        public class MultiType_growMin
        {
        }
        
        public class MultiType_preventScrollbars
        {
        }
        
        public class MultiType_rows
        {
        }
    }
}
