//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class KeyMap : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _eventName_default = "\'keydown\'";
        
        public string _ignoreInputFields_default = "false";
        
        public string _processEventScope_default = "this";
        
        public object binding
        {
            get
            {
                return this.attributes["binding"];
            }
            set
            {
                this.attributes["binding"] = value;
            }
        }
        
        public object eventName
        {
            get
            {
                return this.attributes["eventName"];
            }
            set
            {
                this.attributes["eventName"] = value;
            }
        }
        
        public object ignoreInputFields
        {
            get
            {
                return this.attributes["ignoreInputFields"];
            }
            set
            {
                this.attributes["ignoreInputFields"] = value;
            }
        }
        
        public object processEvent
        {
            get
            {
                return this.attributes["processEvent"];
            }
            set
            {
                this.attributes["processEvent"] = value;
            }
        }
        
        public object processEventScope
        {
            get
            {
                return this.attributes["processEventScope"];
            }
            set
            {
                this.attributes["processEventScope"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public class MultiType_binding
        {
        }
        
        public class MultiType_eventName
        {
        }
        
        public class MultiType_ignoreInputFields
        {
        }
        
        public class MultiType_processEvent
        {
        }
        
        public class MultiType_processEventScope
        {
        }
        
        public class MultiType_target
        {
        }
    }
}
