//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.panel
{
    using System;
    
    
    public partial class AbstractPanel : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _baseCls_default = "x-panel";
        
        public string _border_default = "true";
        
        public string _componentLayout_default = "\'dock\'";
        
        public string _renderTpl_default = "\'{%this.renderContent(out,values)%}\'";
        
        public string _shrinkWrapDock_default = "false";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object bodyBorder
        {
            get
            {
                return this.attributes["bodyBorder"];
            }
            set
            {
                this.attributes["bodyBorder"] = value;
            }
        }
        
        public object bodyCls
        {
            get
            {
                return this.attributes["bodyCls"];
            }
            set
            {
                this.attributes["bodyCls"] = value;
            }
        }
        
        public object bodyPadding
        {
            get
            {
                return this.attributes["bodyPadding"];
            }
            set
            {
                this.attributes["bodyPadding"] = value;
            }
        }
        
        public object bodyStyle
        {
            get
            {
                return this.attributes["bodyStyle"];
            }
            set
            {
                this.attributes["bodyStyle"] = value;
            }
        }
        
        public object border
        {
            get
            {
                return this.attributes["border"];
            }
            set
            {
                this.attributes["border"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object dockedItems
        {
            get
            {
                return this.attributes["dockedItems"];
            }
            set
            {
                this.attributes["dockedItems"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object shrinkWrapDock
        {
            get
            {
                return this.attributes["shrinkWrapDock"];
            }
            set
            {
                this.attributes["shrinkWrapDock"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_bodyBorder
        {
        }
        
        public class MultiType_bodyCls
        {
        }
        
        public class MultiType_bodyPadding
        {
        }
        
        public class MultiType_bodyStyle
        {
        }
        
        public class MultiType_border
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_dockedItems
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_shrinkWrapDock
        {
        }
    }
}
