//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid
{
    using System;
    
    
    public partial class RowEditor : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.Panel
    {
        
        public string _border_default = "false";
        
        public string _hideMode_default = "\'offsets\'";
        
        public object border
        {
            get
            {
                return this.attributes["border"];
            }
            set
            {
                this.attributes["border"] = value;
            }
        }
        
        public object hideMode
        {
            get
            {
                return this.attributes["hideMode"];
            }
            set
            {
                this.attributes["hideMode"] = value;
            }
        }
        
        public class MultiType_border
        {
        }
        
        public class MultiType_hideMode
        {
        }
    }
}
