//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid
{
    using System;
    
    
    public partial class CellEditor : zzProject.ExtJSNet.ExtJS.Classes.Ext.Editor
    {
        
        public string _alignment_default = "\"l-l\"";
        
        public string _cls_default = "Ext.baseCSSPrefix + \'small-editor \' + Ext.baseCSSPrefix + \'grid-editor \' + Ext.ba" +
            "seCSSPrefix + \'grid-cell-editor\'";
        
        public string _hideEl_default = "false";
        
        public string _shadow_default = "false";
        
        public object alignment
        {
            get
            {
                return this.attributes["alignment"];
            }
            set
            {
                this.attributes["alignment"] = value;
            }
        }
        
        public object cls
        {
            get
            {
                return this.attributes["cls"];
            }
            set
            {
                this.attributes["cls"] = value;
            }
        }
        
        public object hideEl
        {
            get
            {
                return this.attributes["hideEl"];
            }
            set
            {
                this.attributes["hideEl"] = value;
            }
        }
        
        public object shadow
        {
            get
            {
                return this.attributes["shadow"];
            }
            set
            {
                this.attributes["shadow"] = value;
            }
        }
        
        public class MultiType_alignment
        {
        }
        
        public class MultiType_cls
        {
        }
        
        public class MultiType_hideEl
        {
        }
        
        public class MultiType_shadow
        {
        }
    }
}
