//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.flash
{
    using System;
    
    
    public partial class Component : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _backgroundColor_default = "\"#ffffff\"";
        
        public string _expressInstall_default = "false";
        
        public string _flashVersion_default = "\"9.0.115\"";
        
        public string _renderTpl_default = "[\'<div id=\"{swfId}\"></div>\']";
        
        public string _swfHeight_default = "\"100%\"";
        
        public string _swfWidth_default = "\"100%\"";
        
        public string _wmode_default = "\"opaque\"";
        
        public object backgroundColor
        {
            get
            {
                return this.attributes["backgroundColor"];
            }
            set
            {
                this.attributes["backgroundColor"] = value;
            }
        }
        
        public object expressInstall
        {
            get
            {
                return this.attributes["expressInstall"];
            }
            set
            {
                this.attributes["expressInstall"] = value;
            }
        }
        
        public object flashAttributes
        {
            get
            {
                return this.attributes["flashAttributes"];
            }
            set
            {
                this.attributes["flashAttributes"] = value;
            }
        }
        
        public object flashParams
        {
            get
            {
                return this.attributes["flashParams"];
            }
            set
            {
                this.attributes["flashParams"] = value;
            }
        }
        
        public object flashVars
        {
            get
            {
                return this.attributes["flashVars"];
            }
            set
            {
                this.attributes["flashVars"] = value;
            }
        }
        
        public object flashVersion
        {
            get
            {
                return this.attributes["flashVersion"];
            }
            set
            {
                this.attributes["flashVersion"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object swfHeight
        {
            get
            {
                return this.attributes["swfHeight"];
            }
            set
            {
                this.attributes["swfHeight"] = value;
            }
        }
        
        public object swfWidth
        {
            get
            {
                return this.attributes["swfWidth"];
            }
            set
            {
                this.attributes["swfWidth"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public object wmode
        {
            get
            {
                return this.attributes["wmode"];
            }
            set
            {
                this.attributes["wmode"] = value;
            }
        }
        
        public class MultiType_backgroundColor
        {
        }
        
        public class MultiType_expressInstall
        {
        }
        
        public class MultiType_flashAttributes
        {
        }
        
        public class MultiType_flashParams
        {
        }
        
        public class MultiType_flashVars
        {
        }
        
        public class MultiType_flashVersion
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_swfHeight
        {
        }
        
        public class MultiType_swfWidth
        {
        }
        
        public class MultiType_url
        {
        }
        
        public class MultiType_wmode
        {
        }
    }
}
