//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.fx
{
    using System;
    
    
    public partial class Manager : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _forceJS_default = "true";
        
        public string _interval_default = "16";
        
        public object forceJS
        {
            get
            {
                return this.attributes["forceJS"];
            }
            set
            {
                this.attributes["forceJS"] = value;
            }
        }
        
        public object interval
        {
            get
            {
                return this.attributes["interval"];
            }
            set
            {
                this.attributes["interval"] = value;
            }
        }
        
        public class MultiType_forceJS
        {
        }
        
        public class MultiType_interval
        {
        }
    }
}
