//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class Labelable : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _autoFitErrors_default = "true";
        
        public string _baseBodyCls_default = "Ext.baseCSSPrefix + \'form-item-body\'";
        
        public string _clearCls_default = "Ext.baseCSSPrefix + \'clear\'";
        
        public string _errorMsgCls_default = "Ext.baseCSSPrefix + \'form-error-msg\'";
        
        public string _fieldBodyCls_default = "\'\'";
        
        public string _formItemCls_default = "Ext.baseCSSPrefix + \'form-item\'";
        
        public string _hideEmptyLabel_default = "true";
        
        public string _hideLabel_default = "false";
        
        public string _invalidCls_default = "Ext.baseCSSPrefix + \'form-invalid\'";
        
        public string _labelAlign_default = "\'left\'";
        
        public string _labelCls_default = "Ext.baseCSSPrefix + \'form-item-label\'";
        
        public string _labelPad_default = "5";
        
        public string _labelSeparator_default = "\':\'";
        
        public string _labelWidth_default = "100";
        
        public string _msgTarget_default = "\'qtip\'";
        
        public string _preventMark_default = "false";
        
        public object activeError
        {
            get
            {
                return this.attributes["activeError"];
            }
            set
            {
                this.attributes["activeError"] = value;
            }
        }
        
        public object activeErrorsTpl
        {
            get
            {
                return this.attributes["activeErrorsTpl"];
            }
            set
            {
                this.attributes["activeErrorsTpl"] = value;
            }
        }
        
        public object afterBodyEl
        {
            get
            {
                return this.attributes["afterBodyEl"];
            }
            set
            {
                this.attributes["afterBodyEl"] = value;
            }
        }
        
        public object afterLabelTextTpl
        {
            get
            {
                return this.attributes["afterLabelTextTpl"];
            }
            set
            {
                this.attributes["afterLabelTextTpl"] = value;
            }
        }
        
        public object afterLabelTpl
        {
            get
            {
                return this.attributes["afterLabelTpl"];
            }
            set
            {
                this.attributes["afterLabelTpl"] = value;
            }
        }
        
        public object afterSubTpl
        {
            get
            {
                return this.attributes["afterSubTpl"];
            }
            set
            {
                this.attributes["afterSubTpl"] = value;
            }
        }
        
        public object autoFitErrors
        {
            get
            {
                return this.attributes["autoFitErrors"];
            }
            set
            {
                this.attributes["autoFitErrors"] = value;
            }
        }
        
        public object baseBodyCls
        {
            get
            {
                return this.attributes["baseBodyCls"];
            }
            set
            {
                this.attributes["baseBodyCls"] = value;
            }
        }
        
        public object beforeBodyEl
        {
            get
            {
                return this.attributes["beforeBodyEl"];
            }
            set
            {
                this.attributes["beforeBodyEl"] = value;
            }
        }
        
        public object beforeLabelTextTpl
        {
            get
            {
                return this.attributes["beforeLabelTextTpl"];
            }
            set
            {
                this.attributes["beforeLabelTextTpl"] = value;
            }
        }
        
        public object beforeLabelTpl
        {
            get
            {
                return this.attributes["beforeLabelTpl"];
            }
            set
            {
                this.attributes["beforeLabelTpl"] = value;
            }
        }
        
        public object beforeSubTpl
        {
            get
            {
                return this.attributes["beforeSubTpl"];
            }
            set
            {
                this.attributes["beforeSubTpl"] = value;
            }
        }
        
        public object clearCls
        {
            get
            {
                return this.attributes["clearCls"];
            }
            set
            {
                this.attributes["clearCls"] = value;
            }
        }
        
        public object errorMsgCls
        {
            get
            {
                return this.attributes["errorMsgCls"];
            }
            set
            {
                this.attributes["errorMsgCls"] = value;
            }
        }
        
        public object fieldBodyCls
        {
            get
            {
                return this.attributes["fieldBodyCls"];
            }
            set
            {
                this.attributes["fieldBodyCls"] = value;
            }
        }
        
        public object fieldLabel
        {
            get
            {
                return this.attributes["fieldLabel"];
            }
            set
            {
                this.attributes["fieldLabel"] = value;
            }
        }
        
        public object formItemCls
        {
            get
            {
                return this.attributes["formItemCls"];
            }
            set
            {
                this.attributes["formItemCls"] = value;
            }
        }
        
        public object hideEmptyLabel
        {
            get
            {
                return this.attributes["hideEmptyLabel"];
            }
            set
            {
                this.attributes["hideEmptyLabel"] = value;
            }
        }
        
        public object hideLabel
        {
            get
            {
                return this.attributes["hideLabel"];
            }
            set
            {
                this.attributes["hideLabel"] = value;
            }
        }
        
        public object invalidCls
        {
            get
            {
                return this.attributes["invalidCls"];
            }
            set
            {
                this.attributes["invalidCls"] = value;
            }
        }
        
        public object labelAlign
        {
            get
            {
                return this.attributes["labelAlign"];
            }
            set
            {
                this.attributes["labelAlign"] = value;
            }
        }
        
        public object labelAttrTpl
        {
            get
            {
                return this.attributes["labelAttrTpl"];
            }
            set
            {
                this.attributes["labelAttrTpl"] = value;
            }
        }
        
        public object labelCls
        {
            get
            {
                return this.attributes["labelCls"];
            }
            set
            {
                this.attributes["labelCls"] = value;
            }
        }
        
        public object labelClsExtra
        {
            get
            {
                return this.attributes["labelClsExtra"];
            }
            set
            {
                this.attributes["labelClsExtra"] = value;
            }
        }
        
        public object labelPad
        {
            get
            {
                return this.attributes["labelPad"];
            }
            set
            {
                this.attributes["labelPad"] = value;
            }
        }
        
        public object labelSeparator
        {
            get
            {
                return this.attributes["labelSeparator"];
            }
            set
            {
                this.attributes["labelSeparator"] = value;
            }
        }
        
        public object labelStyle
        {
            get
            {
                return this.attributes["labelStyle"];
            }
            set
            {
                this.attributes["labelStyle"] = value;
            }
        }
        
        public object labelWidth
        {
            get
            {
                return this.attributes["labelWidth"];
            }
            set
            {
                this.attributes["labelWidth"] = value;
            }
        }
        
        public object msgTarget
        {
            get
            {
                return this.attributes["msgTarget"];
            }
            set
            {
                this.attributes["msgTarget"] = value;
            }
        }
        
        public object preventMark
        {
            get
            {
                return this.attributes["preventMark"];
            }
            set
            {
                this.attributes["preventMark"] = value;
            }
        }
        
        public class MultiType_activeError
        {
        }
        
        public class MultiType_activeErrorsTpl
        {
        }
        
        public class MultiType_afterBodyEl
        {
        }
        
        public class MultiType_afterLabelTextTpl
        {
        }
        
        public class MultiType_afterLabelTpl
        {
        }
        
        public class MultiType_afterSubTpl
        {
        }
        
        public class MultiType_autoFitErrors
        {
        }
        
        public class MultiType_baseBodyCls
        {
        }
        
        public class MultiType_beforeBodyEl
        {
        }
        
        public class MultiType_beforeLabelTextTpl
        {
        }
        
        public class MultiType_beforeLabelTpl
        {
        }
        
        public class MultiType_beforeSubTpl
        {
        }
        
        public class MultiType_clearCls
        {
        }
        
        public class MultiType_errorMsgCls
        {
        }
        
        public class MultiType_fieldBodyCls
        {
        }
        
        public class MultiType_fieldLabel
        {
        }
        
        public class MultiType_formItemCls
        {
        }
        
        public class MultiType_hideEmptyLabel
        {
        }
        
        public class MultiType_hideLabel
        {
        }
        
        public class MultiType_invalidCls
        {
        }
        
        public class MultiType_labelAlign
        {
        }
        
        public class MultiType_labelAttrTpl
        {
        }
        
        public class MultiType_labelCls
        {
        }
        
        public class MultiType_labelClsExtra
        {
        }
        
        public class MultiType_labelPad
        {
        }
        
        public class MultiType_labelSeparator
        {
        }
        
        public class MultiType_labelStyle
        {
        }
        
        public class MultiType_labelWidth
        {
        }
        
        public class MultiType_msgTarget
        {
        }
        
        public class MultiType_preventMark
        {
        }
    }
}
