//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class Checkbox : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field.Base
    {
        
        public string _boxLabelAlign_default = "\'after\'";
        
        public string _boxLabelCls_default = "\'x-form-cb-label\'";
        
        public string _checkChangeEvents_default = "[]";
        
        public string _checked_default = "false";
        
        public string _checkedCls_default = "\'x-form-cb-checked\'";
        
        public string _componentLayout_default = "\'field\'";
        
        public string _fieldCls_default = "\'x-form-field\'";
        
        public string _focusCls_default = "\'x-form-checkbox-focus\'";
        
        public string _inputType_default = "\'checkbox\'";
        
        public string _inputValue_default = "\'on\'";
        
        public object afterBoxLabelTextTpl
        {
            get
            {
                return this.attributes["afterBoxLabelTextTpl"];
            }
            set
            {
                this.attributes["afterBoxLabelTextTpl"] = value;
            }
        }
        
        public object afterBoxLabelTpl
        {
            get
            {
                return this.attributes["afterBoxLabelTpl"];
            }
            set
            {
                this.attributes["afterBoxLabelTpl"] = value;
            }
        }
        
        public object beforeBoxLabelTextTpl
        {
            get
            {
                return this.attributes["beforeBoxLabelTextTpl"];
            }
            set
            {
                this.attributes["beforeBoxLabelTextTpl"] = value;
            }
        }
        
        public object beforeBoxLabelTpl
        {
            get
            {
                return this.attributes["beforeBoxLabelTpl"];
            }
            set
            {
                this.attributes["beforeBoxLabelTpl"] = value;
            }
        }
        
        public object boxLabel
        {
            get
            {
                return this.attributes["boxLabel"];
            }
            set
            {
                this.attributes["boxLabel"] = value;
            }
        }
        
        public object boxLabelAlign
        {
            get
            {
                return this.attributes["boxLabelAlign"];
            }
            set
            {
                this.attributes["boxLabelAlign"] = value;
            }
        }
        
        public object boxLabelAttrTpl
        {
            get
            {
                return this.attributes["boxLabelAttrTpl"];
            }
            set
            {
                this.attributes["boxLabelAttrTpl"] = value;
            }
        }
        
        public object boxLabelCls
        {
            get
            {
                return this.attributes["boxLabelCls"];
            }
            set
            {
                this.attributes["boxLabelCls"] = value;
            }
        }
        
        public object checkChangeEvents
        {
            get
            {
                return this.attributes["checkChangeEvents"];
            }
            set
            {
                this.attributes["checkChangeEvents"] = value;
            }
        }
        
        public object _checked
        {
            get
            {
                return this.attributes["checked"];
            }
            set
            {
                this.attributes["checked"] = value;
            }
        }
        
        public object checkedCls
        {
            get
            {
                return this.attributes["checkedCls"];
            }
            set
            {
                this.attributes["checkedCls"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object fieldCls
        {
            get
            {
                return this.attributes["fieldCls"];
            }
            set
            {
                this.attributes["fieldCls"] = value;
            }
        }
        
        public object focusCls
        {
            get
            {
                return this.attributes["focusCls"];
            }
            set
            {
                this.attributes["focusCls"] = value;
            }
        }
        
        public object handler
        {
            get
            {
                return this.attributes["handler"];
            }
            set
            {
                this.attributes["handler"] = value;
            }
        }
        
        public object inputType
        {
            get
            {
                return this.attributes["inputType"];
            }
            set
            {
                this.attributes["inputType"] = value;
            }
        }
        
        public object inputValue
        {
            get
            {
                return this.attributes["inputValue"];
            }
            set
            {
                this.attributes["inputValue"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object uncheckedValue
        {
            get
            {
                return this.attributes["uncheckedValue"];
            }
            set
            {
                this.attributes["uncheckedValue"] = value;
            }
        }
        
        public class MultiType_afterBoxLabelTextTpl
        {
        }
        
        public class MultiType_afterBoxLabelTpl
        {
        }
        
        public class MultiType_beforeBoxLabelTextTpl
        {
        }
        
        public class MultiType_beforeBoxLabelTpl
        {
        }
        
        public class MultiType_boxLabel
        {
        }
        
        public class MultiType_boxLabelAlign
        {
        }
        
        public class MultiType_boxLabelAttrTpl
        {
        }
        
        public class MultiType_boxLabelCls
        {
        }
        
        public class MultiType_checkChangeEvents
        {
        }
        
        public class MultiType_checked
        {
        }
        
        public class MultiType_checkedCls
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_fieldCls
        {
        }
        
        public class MultiType_focusCls
        {
        }
        
        public class MultiType_handler
        {
        }
        
        public class MultiType_inputType
        {
        }
        
        public class MultiType_inputValue
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_uncheckedValue
        {
        }
    }
}
