//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis
{
    using System;
    
    
    public partial class Time : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis.Numeric
    {
        
        public string _constrain_default = "false";
        
        public string _dateFormat_default = "false";
        
        public string _fromDate_default = "false";
        
        public string _toDate_default = "false";
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object dateFormat
        {
            get
            {
                return this.attributes["dateFormat"];
            }
            set
            {
                this.attributes["dateFormat"] = value;
            }
        }
        
        public object fromDate
        {
            get
            {
                return this.attributes["fromDate"];
            }
            set
            {
                this.attributes["fromDate"] = value;
            }
        }
        
        public object step
        {
            get
            {
                return this.attributes["step"];
            }
            set
            {
                this.attributes["step"] = value;
            }
        }
        
        public object toDate
        {
            get
            {
                return this.attributes["toDate"];
            }
            set
            {
                this.attributes["toDate"] = value;
            }
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_dateFormat
        {
        }
        
        public class MultiType_fromDate
        {
        }
        
        public class MultiType_step
        {
        }
        
        public class MultiType_toDate
        {
        }
    }
}
