//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tree
{
    using System;
    
    
    public partial class Column : zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.column.Column
    {
        
        public string _hideable_default = "false";
        
        public string _lockable_default = "false";
        
        public string _tdCls_default = "Ext.baseCSSPrefix + \'grid-cell-treecolumn\'";
        
        public object hideable
        {
            get
            {
                return this.attributes["hideable"];
            }
            set
            {
                this.attributes["hideable"] = value;
            }
        }
        
        public object lockable
        {
            get
            {
                return this.attributes["lockable"];
            }
            set
            {
                this.attributes["lockable"] = value;
            }
        }
        
        public object tdCls
        {
            get
            {
                return this.attributes["tdCls"];
            }
            set
            {
                this.attributes["tdCls"] = value;
            }
        }
        
        public class MultiType_hideable
        {
        }
        
        public class MultiType_lockable
        {
        }
        
        public class MultiType_tdCls
        {
        }
    }
}
