//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.direct
{
    using System;
    
    
    public partial class Provider : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object id
        {
            get
            {
                return this.attributes["id"];
            }
            set
            {
                this.attributes["id"] = value;
            }
        }
        
        public object relayedEvents
        {
            get
            {
                return this.attributes["relayedEvents"];
            }
            set
            {
                this.attributes["relayedEvents"] = value;
            }
        }
        
        public class MultiType_id
        {
        }
        
        public class MultiType_relayedEvents
        {
        }
    }
}
