//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class Floating : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _constrain_default = "false";
        
        public string _fixed_default = "false";
        
        public string _focusOnToFront_default = "true";
        
        public string _shadow_default = "\'sides\'";
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object _fixed
        {
            get
            {
                return this.attributes["fixed"];
            }
            set
            {
                this.attributes["fixed"] = value;
            }
        }
        
        public object focusOnToFront
        {
            get
            {
                return this.attributes["focusOnToFront"];
            }
            set
            {
                this.attributes["focusOnToFront"] = value;
            }
        }
        
        public object shadow
        {
            get
            {
                return this.attributes["shadow"];
            }
            set
            {
                this.attributes["shadow"] = value;
            }
        }
        
        public object shadowOffset
        {
            get
            {
                return this.attributes["shadowOffset"];
            }
            set
            {
                this.attributes["shadowOffset"] = value;
            }
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_fixed
        {
        }
        
        public class MultiType_focusOnToFront
        {
        }
        
        public class MultiType_shadow
        {
        }
        
        public class MultiType_shadowOffset
        {
        }
    }
}
