//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class Filter : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _anyMatch_default = "false";
        
        public string _caseSensitive_default = "false";
        
        public string _exactMatch_default = "false";
        
        public object anyMatch
        {
            get
            {
                return this.attributes["anyMatch"];
            }
            set
            {
                this.attributes["anyMatch"] = value;
            }
        }
        
        public object caseSensitive
        {
            get
            {
                return this.attributes["caseSensitive"];
            }
            set
            {
                this.attributes["caseSensitive"] = value;
            }
        }
        
        public object exactMatch
        {
            get
            {
                return this.attributes["exactMatch"];
            }
            set
            {
                this.attributes["exactMatch"] = value;
            }
        }
        
        public object filterFn
        {
            get
            {
                return this.attributes["filterFn"];
            }
            set
            {
                this.attributes["filterFn"] = value;
            }
        }
        
        public object id
        {
            get
            {
                return this.attributes["id"];
            }
            set
            {
                this.attributes["id"] = value;
            }
        }
        
        public object _operator
        {
            get
            {
                return this.attributes["operator"];
            }
            set
            {
                this.attributes["operator"] = value;
            }
        }
        
        public object property
        {
            get
            {
                return this.attributes["property"];
            }
            set
            {
                this.attributes["property"] = value;
            }
        }
        
        public object root
        {
            get
            {
                return this.attributes["root"];
            }
            set
            {
                this.attributes["root"] = value;
            }
        }
        
        public object value
        {
            get
            {
                return this.attributes["value"];
            }
            set
            {
                this.attributes["value"] = value;
            }
        }
        
        public class MultiType_anyMatch
        {
        }
        
        public class MultiType_caseSensitive
        {
        }
        
        public class MultiType_exactMatch
        {
        }
        
        public class MultiType_filterFn
        {
        }
        
        public class MultiType_id
        {
        }
        
        public class MultiType_operator
        {
        }
        
        public class MultiType_property
        {
        }
        
        public class MultiType_root
        {
        }
        
        public class MultiType_value
        {
        }
    }
}
