//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tab
{
    using System;
    
    
    public partial class Panel : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Panel
    {
        
        public string _deferredRender_default = "true";
        
        public string _itemCls_default = "\'x-tabpanel-child\'";
        
        public string _plain_default = "false";
        
        public string _removePanelHeader_default = "true";
        
        public string _tabPosition_default = "\'top\'";
        
        public object activeItem
        {
            get
            {
                return this.attributes["activeItem"];
            }
            set
            {
                this.attributes["activeItem"] = value;
            }
        }
        
        public object activeTab
        {
            get
            {
                return this.attributes["activeTab"];
            }
            set
            {
                this.attributes["activeTab"] = value;
            }
        }
        
        public object deferredRender
        {
            get
            {
                return this.attributes["deferredRender"];
            }
            set
            {
                this.attributes["deferredRender"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object maxTabWidth
        {
            get
            {
                return this.attributes["maxTabWidth"];
            }
            set
            {
                this.attributes["maxTabWidth"] = value;
            }
        }
        
        public object minTabWidth
        {
            get
            {
                return this.attributes["minTabWidth"];
            }
            set
            {
                this.attributes["minTabWidth"] = value;
            }
        }
        
        public object plain
        {
            get
            {
                return this.attributes["plain"];
            }
            set
            {
                this.attributes["plain"] = value;
            }
        }
        
        public object removePanelHeader
        {
            get
            {
                return this.attributes["removePanelHeader"];
            }
            set
            {
                this.attributes["removePanelHeader"] = value;
            }
        }
        
        public object tabBar
        {
            get
            {
                return this.attributes["tabBar"];
            }
            set
            {
                this.attributes["tabBar"] = value;
            }
        }
        
        public object tabPosition
        {
            get
            {
                return this.attributes["tabPosition"];
            }
            set
            {
                this.attributes["tabPosition"] = value;
            }
        }
        
        public class MultiType_activeItem
        {
        }
        
        public class MultiType_activeTab
        {
        }
        
        public class MultiType_deferredRender
        {
        }
        
        public class MultiType_itemCls
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_maxTabWidth
        {
        }
        
        public class MultiType_minTabWidth
        {
        }
        
        public class MultiType_plain
        {
        }
        
        public class MultiType_removePanelHeader
        {
        }
        
        public class MultiType_tabBar
        {
        }
        
        public class MultiType_tabPosition
        {
        }
    }
}
