//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.menu
{
    using System;
    
    
    public partial class Menu : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Panel
    {
        
        public string _allowOtherMenus_default = "false";
        
        public string _enableKeyNav_default = "true";
        
        public string _floating_default = "true";
        
        public string _hidden_default = "undefined";
        
        public string _hideMode_default = "\'visibility\'";
        
        public string _ignoreParentClicks_default = "false";
        
        public string _minWidth_default = "120";
        
        public string _plain_default = "false";
        
        public string _showSeparator_default = "true";
        
        public object allowOtherMenus
        {
            get
            {
                return this.attributes["allowOtherMenus"];
            }
            set
            {
                this.attributes["allowOtherMenus"] = value;
            }
        }
        
        public object enableKeyNav
        {
            get
            {
                return this.attributes["enableKeyNav"];
            }
            set
            {
                this.attributes["enableKeyNav"] = value;
            }
        }
        
        public object floating
        {
            get
            {
                return this.attributes["floating"];
            }
            set
            {
                this.attributes["floating"] = value;
            }
        }
        
        public object hidden
        {
            get
            {
                return this.attributes["hidden"];
            }
            set
            {
                this.attributes["hidden"] = value;
            }
        }
        
        public object hideMode
        {
            get
            {
                return this.attributes["hideMode"];
            }
            set
            {
                this.attributes["hideMode"] = value;
            }
        }
        
        public object ignoreParentClicks
        {
            get
            {
                return this.attributes["ignoreParentClicks"];
            }
            set
            {
                this.attributes["ignoreParentClicks"] = value;
            }
        }
        
        public object minWidth
        {
            get
            {
                return this.attributes["minWidth"];
            }
            set
            {
                this.attributes["minWidth"] = value;
            }
        }
        
        public object plain
        {
            get
            {
                return this.attributes["plain"];
            }
            set
            {
                this.attributes["plain"] = value;
            }
        }
        
        public object showSeparator
        {
            get
            {
                return this.attributes["showSeparator"];
            }
            set
            {
                this.attributes["showSeparator"] = value;
            }
        }
        
        public class MultiType_allowOtherMenus
        {
        }
        
        public class MultiType_enableKeyNav
        {
        }
        
        public class MultiType_floating
        {
        }
        
        public class MultiType_hidden
        {
        }
        
        public class MultiType_hideMode
        {
        }
        
        public class MultiType_ignoreParentClicks
        {
        }
        
        public class MultiType_minWidth
        {
        }
        
        public class MultiType_plain
        {
        }
        
        public class MultiType_showSeparator
        {
        }
    }
}
