//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.association
{
    using System;
    
    
    public partial class HasMany : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.association.Association
    {
        
        public object autoLoad
        {
            get
            {
                return this.attributes["autoLoad"];
            }
            set
            {
                this.attributes["autoLoad"] = value;
            }
        }
        
        public object filterProperty
        {
            get
            {
                return this.attributes["filterProperty"];
            }
            set
            {
                this.attributes["filterProperty"] = value;
            }
        }
        
        public object foreignKey
        {
            get
            {
                return this.attributes["foreignKey"];
            }
            set
            {
                this.attributes["foreignKey"] = value;
            }
        }
        
        public object name
        {
            get
            {
                return this.attributes["name"];
            }
            set
            {
                this.attributes["name"] = value;
            }
        }
        
        public object storeConfig
        {
            get
            {
                return this.attributes["storeConfig"];
            }
            set
            {
                this.attributes["storeConfig"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public class MultiType_autoLoad
        {
        }
        
        public class MultiType_filterProperty
        {
        }
        
        public class MultiType_foreignKey
        {
        }
        
        public class MultiType_name
        {
        }
        
        public class MultiType_storeConfig
        {
        }
        
        public class MultiType_type
        {
        }
    }
}
