//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container
{
    using System;
    
    
    public partial class Box : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.Container
    {
        
        public string _defaultMargins_default = "{top: 0, right: 0, bottom: 0, left: 0}";
        
        public string _itemCls_default = "Ext.baseCSSPrefix + \'box-item\'";
        
        public string _pack_default = "\'start\'";
        
        public string _padding_default = "0";
        
        public object defaultMargins
        {
            get
            {
                return this.attributes["defaultMargins"];
            }
            set
            {
                this.attributes["defaultMargins"] = value;
            }
        }
        
        public object flex
        {
            get
            {
                return this.attributes["flex"];
            }
            set
            {
                this.attributes["flex"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object pack
        {
            get
            {
                return this.attributes["pack"];
            }
            set
            {
                this.attributes["pack"] = value;
            }
        }
        
        public object padding
        {
            get
            {
                return this.attributes["padding"];
            }
            set
            {
                this.attributes["padding"] = value;
            }
        }
        
        public object stretchMaxPartner
        {
            get
            {
                return this.attributes["stretchMaxPartner"];
            }
            set
            {
                this.attributes["stretchMaxPartner"] = value;
            }
        }
        
        public class MultiType_defaultMargins
        {
        }
        
        public class MultiType_flex
        {
        }
        
        public class MultiType_itemCls
        {
        }
        
        public class MultiType_pack
        {
        }
        
        public class MultiType_padding
        {
        }
        
        public class MultiType_stretchMaxPartner
        {
        }
    }
}
