//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis
{
    using System;
    
    
    public partial class Axis : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis.Abstract
    {
        
        public string _adjustEnd_default = "true";
        
        public string _dashSize_default = "3";
        
        public string _hidden_default = "false";
        
        public string _length_default = "0";
        
        public string _position_default = "\'bottom\'";
        
        public string _width_default = "0";
        
        public object adjustEnd
        {
            get
            {
                return this.attributes["adjustEnd"];
            }
            set
            {
                this.attributes["adjustEnd"] = value;
            }
        }
        
        public object dashSize
        {
            get
            {
                return this.attributes["dashSize"];
            }
            set
            {
                this.attributes["dashSize"] = value;
            }
        }
        
        public object grid
        {
            get
            {
                return this.attributes["grid"];
            }
            set
            {
                this.attributes["grid"] = value;
            }
        }
        
        public object hidden
        {
            get
            {
                return this.attributes["hidden"];
            }
            set
            {
                this.attributes["hidden"] = value;
            }
        }
        
        public object length
        {
            get
            {
                return this.attributes["length"];
            }
            set
            {
                this.attributes["length"] = value;
            }
        }
        
        public object majorTickSteps
        {
            get
            {
                return this.attributes["majorTickSteps"];
            }
            set
            {
                this.attributes["majorTickSteps"] = value;
            }
        }
        
        public object minorTickSteps
        {
            get
            {
                return this.attributes["minorTickSteps"];
            }
            set
            {
                this.attributes["minorTickSteps"] = value;
            }
        }
        
        public object position
        {
            get
            {
                return this.attributes["position"];
            }
            set
            {
                this.attributes["position"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public object width
        {
            get
            {
                return this.attributes["width"];
            }
            set
            {
                this.attributes["width"] = value;
            }
        }
        
        public class MultiType_adjustEnd
        {
        }
        
        public class MultiType_dashSize
        {
        }
        
        public class MultiType_grid
        {
        }
        
        public class MultiType_hidden
        {
        }
        
        public class MultiType_length
        {
        }
        
        public class MultiType_majorTickSteps
        {
        }
        
        public class MultiType_minorTickSteps
        {
        }
        
        public class MultiType_position
        {
        }
        
        public class MultiType_title
        {
        }
        
        public class MultiType_width
        {
        }
    }
}
