//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart
{
    using System;
    
    
    public partial class Chart : zzProject.ExtJSNet.ExtJS.Classes.Ext.draw.Component
    {
        
        public string _animate_default = "false";
        
        public string _background_default = "false";
        
        public string _insetPadding_default = "10";
        
        public string _legend_default = "false";
        
        public object animate
        {
            get
            {
                return this.attributes["animate"];
            }
            set
            {
                this.attributes["animate"] = value;
            }
        }
        
        public object axes
        {
            get
            {
                return this.attributes["axes"];
            }
            set
            {
                this.attributes["axes"] = value;
            }
        }
        
        public object background
        {
            get
            {
                return this.attributes["background"];
            }
            set
            {
                this.attributes["background"] = value;
            }
        }
        
        public object gradients
        {
            get
            {
                return this.attributes["gradients"];
            }
            set
            {
                this.attributes["gradients"] = value;
            }
        }
        
        public object insetPadding
        {
            get
            {
                return this.attributes["insetPadding"];
            }
            set
            {
                this.attributes["insetPadding"] = value;
            }
        }
        
        public object legend
        {
            get
            {
                return this.attributes["legend"];
            }
            set
            {
                this.attributes["legend"] = value;
            }
        }
        
        public object series
        {
            get
            {
                return this.attributes["series"];
            }
            set
            {
                this.attributes["series"] = value;
            }
        }
        
        public object store
        {
            get
            {
                return this.attributes["store"];
            }
            set
            {
                this.attributes["store"] = value;
            }
        }
        
        public object theme
        {
            get
            {
                return this.attributes["theme"];
            }
            set
            {
                this.attributes["theme"] = value;
            }
        }
        
        public class MultiType_animate
        {
        }
        
        public class MultiType_axes
        {
        }
        
        public class MultiType_background
        {
        }
        
        public class MultiType_gradients
        {
        }
        
        public class MultiType_insetPadding
        {
        }
        
        public class MultiType_legend
        {
        }
        
        public class MultiType_series
        {
        }
        
        public class MultiType_store
        {
        }
        
        public class MultiType_theme
        {
        }
    }
}
