//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class ClickRepeater : zzProject.ExtJSNet.ExtJS.Classes.Ext.util.Observable
    {
        
        public string _delay_default = "250";
        
        public string _interval_default = "20";
        
        public string _preventDefault_default = "true";
        
        public string _stopDefault_default = "false";
        
        public object accelerate
        {
            get
            {
                return this.attributes["accelerate"];
            }
            set
            {
                this.attributes["accelerate"] = value;
            }
        }
        
        public object delay
        {
            get
            {
                return this.attributes["delay"];
            }
            set
            {
                this.attributes["delay"] = value;
            }
        }
        
        public object el
        {
            get
            {
                return this.attributes["el"];
            }
            set
            {
                this.attributes["el"] = value;
            }
        }
        
        public object interval
        {
            get
            {
                return this.attributes["interval"];
            }
            set
            {
                this.attributes["interval"] = value;
            }
        }
        
        public object pressedCls
        {
            get
            {
                return this.attributes["pressedCls"];
            }
            set
            {
                this.attributes["pressedCls"] = value;
            }
        }
        
        public object preventDefault
        {
            get
            {
                return this.attributes["preventDefault"];
            }
            set
            {
                this.attributes["preventDefault"] = value;
            }
        }
        
        public object stopDefault
        {
            get
            {
                return this.attributes["stopDefault"];
            }
            set
            {
                this.attributes["stopDefault"] = value;
            }
        }
        
        public class MultiType_accelerate
        {
        }
        
        public class MultiType_delay
        {
        }
        
        public class MultiType_el
        {
        }
        
        public class MultiType_interval
        {
        }
        
        public class MultiType_pressedCls
        {
        }
        
        public class MultiType_preventDefault
        {
        }
        
        public class MultiType_stopDefault
        {
        }
    }
}
