//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class Request : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _method_default = "\'GET\'";
        
        public object action
        {
            get
            {
                return this.attributes["action"];
            }
            set
            {
                this.attributes["action"] = value;
            }
        }
        
        public object method
        {
            get
            {
                return this.attributes["method"];
            }
            set
            {
                this.attributes["method"] = value;
            }
        }
        
        public object _params
        {
            get
            {
                return this.attributes["params"];
            }
            set
            {
                this.attributes["params"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public class MultiType_action
        {
        }
        
        public class MultiType_method
        {
        }
        
        public class MultiType_params
        {
        }
        
        public class MultiType_url
        {
        }
    }
}
