//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.reader
{
    using System;
    
    
    public partial class Json : zzProject.ExtJSNet.ExtJS.Classes.Ext.data.reader.Reader
    {
        
        public string _metaProperty_default = "\"metaData\"";
        
        public string _root_default = "\'\'";
        
        public string _useSimpleAccessors_default = "false";
        
        public object metaProperty
        {
            get
            {
                return this.attributes["metaProperty"];
            }
            set
            {
                this.attributes["metaProperty"] = value;
            }
        }
        
        public object record
        {
            get
            {
                return this.attributes["record"];
            }
            set
            {
                this.attributes["record"] = value;
            }
        }
        
        public object root
        {
            get
            {
                return this.attributes["root"];
            }
            set
            {
                this.attributes["root"] = value;
            }
        }
        
        public object useSimpleAccessors
        {
            get
            {
                return this.attributes["useSimpleAccessors"];
            }
            set
            {
                this.attributes["useSimpleAccessors"] = value;
            }
        }
        
        public class MultiType_metaProperty
        {
        }
        
        public class MultiType_record
        {
        }
        
        public class MultiType_root
        {
        }
        
        public class MultiType_useSimpleAccessors
        {
        }
    }
}
