//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container
{
    using System;
    
    
    public partial class Border : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.Container
    {
        
        public string _itemCls_default = "[Ext.baseCSSPrefix + \'border-item\', Ext.baseCSSPrefix + \'box-item\']";
        
        public string _splitterResize_default = "true";
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object padding
        {
            get
            {
                return this.attributes["padding"];
            }
            set
            {
                this.attributes["padding"] = value;
            }
        }
        
        public object regionWeights
        {
            get
            {
                return this.attributes["regionWeights"];
            }
            set
            {
                this.attributes["regionWeights"] = value;
            }
        }
        
        public object split
        {
            get
            {
                return this.attributes["split"];
            }
            set
            {
                this.attributes["split"] = value;
            }
        }
        
        public object splitterResize
        {
            get
            {
                return this.attributes["splitterResize"];
            }
            set
            {
                this.attributes["splitterResize"] = value;
            }
        }
        
        public class MultiType_itemCls
        {
        }
        
        public class MultiType_padding
        {
        }
        
        public class MultiType_regionWeights
        {
        }
        
        public class MultiType_split
        {
        }
        
        public class MultiType_splitterResize
        {
        }
    }
}
