//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.panel
{
    using System;
    
    
    public partial class Panel : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.AbstractPanel
    {
        
        public string _closable_default = "false";
        
        public string _closeAction_default = "\'destroy\'";
        
        public string _collapseFirst_default = "true";
        
        public string _collapsed_default = "false";
        
        public string _collapsedCls_default = "\'collapsed\'";
        
        public string _constrain_default = "false";
        
        public string _constrainHeader_default = "false";
        
        public string _floatable_default = "true";
        
        public string _frame_default = "false";
        
        public string _frameHeader_default = "true";
        
        public string _headerPosition_default = "\'top\'";
        
        public string _hideCollapseTool_default = "false";
        
        public string _manageHeight_default = "true";
        
        public string _minButtonWidth_default = "75";
        
        public string _preventHeader_default = "false";
        
        public string _simpleDrag_default = "false";
        
        public string _title_default = "\'\'";
        
        public object animCollapse
        {
            get
            {
                return this.attributes["animCollapse"];
            }
            set
            {
                this.attributes["animCollapse"] = value;
            }
        }
        
        public object bbar
        {
            get
            {
                return this.attributes["bbar"];
            }
            set
            {
                this.attributes["bbar"] = value;
            }
        }
        
        public object buttonAlign
        {
            get
            {
                return this.attributes["buttonAlign"];
            }
            set
            {
                this.attributes["buttonAlign"] = value;
            }
        }
        
        public object buttons
        {
            get
            {
                return this.attributes["buttons"];
            }
            set
            {
                this.attributes["buttons"] = value;
            }
        }
        
        public object closable
        {
            get
            {
                return this.attributes["closable"];
            }
            set
            {
                this.attributes["closable"] = value;
            }
        }
        
        public object closeAction
        {
            get
            {
                return this.attributes["closeAction"];
            }
            set
            {
                this.attributes["closeAction"] = value;
            }
        }
        
        public object collapseDirection
        {
            get
            {
                return this.attributes["collapseDirection"];
            }
            set
            {
                this.attributes["collapseDirection"] = value;
            }
        }
        
        public object collapseFirst
        {
            get
            {
                return this.attributes["collapseFirst"];
            }
            set
            {
                this.attributes["collapseFirst"] = value;
            }
        }
        
        public object collapseMode
        {
            get
            {
                return this.attributes["collapseMode"];
            }
            set
            {
                this.attributes["collapseMode"] = value;
            }
        }
        
        public object collapsed
        {
            get
            {
                return this.attributes["collapsed"];
            }
            set
            {
                this.attributes["collapsed"] = value;
            }
        }
        
        public object collapsedCls
        {
            get
            {
                return this.attributes["collapsedCls"];
            }
            set
            {
                this.attributes["collapsedCls"] = value;
            }
        }
        
        public object collapsible
        {
            get
            {
                return this.attributes["collapsible"];
            }
            set
            {
                this.attributes["collapsible"] = value;
            }
        }
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object constrainHeader
        {
            get
            {
                return this.attributes["constrainHeader"];
            }
            set
            {
                this.attributes["constrainHeader"] = value;
            }
        }
        
        public object dockedItems
        {
            get
            {
                return this.attributes["dockedItems"];
            }
            set
            {
                this.attributes["dockedItems"] = value;
            }
        }
        
        public object fbar
        {
            get
            {
                return this.attributes["fbar"];
            }
            set
            {
                this.attributes["fbar"] = value;
            }
        }
        
        public object floatable
        {
            get
            {
                return this.attributes["floatable"];
            }
            set
            {
                this.attributes["floatable"] = value;
            }
        }
        
        public object frame
        {
            get
            {
                return this.attributes["frame"];
            }
            set
            {
                this.attributes["frame"] = value;
            }
        }
        
        public object frameHeader
        {
            get
            {
                return this.attributes["frameHeader"];
            }
            set
            {
                this.attributes["frameHeader"] = value;
            }
        }
        
        public object glyph
        {
            get
            {
                return this.attributes["glyph"];
            }
            set
            {
                this.attributes["glyph"] = value;
            }
        }
        
        public object header
        {
            get
            {
                return this.attributes["header"];
            }
            set
            {
                this.attributes["header"] = value;
            }
        }
        
        public object headerOverCls
        {
            get
            {
                return this.attributes["headerOverCls"];
            }
            set
            {
                this.attributes["headerOverCls"] = value;
            }
        }
        
        public object headerPosition
        {
            get
            {
                return this.attributes["headerPosition"];
            }
            set
            {
                this.attributes["headerPosition"] = value;
            }
        }
        
        public object hideCollapseTool
        {
            get
            {
                return this.attributes["hideCollapseTool"];
            }
            set
            {
                this.attributes["hideCollapseTool"] = value;
            }
        }
        
        public object icon
        {
            get
            {
                return this.attributes["icon"];
            }
            set
            {
                this.attributes["icon"] = value;
            }
        }
        
        public object iconCls
        {
            get
            {
                return this.attributes["iconCls"];
            }
            set
            {
                this.attributes["iconCls"] = value;
            }
        }
        
        public object lbar
        {
            get
            {
                return this.attributes["lbar"];
            }
            set
            {
                this.attributes["lbar"] = value;
            }
        }
        
        public object manageHeight
        {
            get
            {
                return this.attributes["manageHeight"];
            }
            set
            {
                this.attributes["manageHeight"] = value;
            }
        }
        
        public object minButtonWidth
        {
            get
            {
                return this.attributes["minButtonWidth"];
            }
            set
            {
                this.attributes["minButtonWidth"] = value;
            }
        }
        
        public object overlapHeader
        {
            get
            {
                return this.attributes["overlapHeader"];
            }
            set
            {
                this.attributes["overlapHeader"] = value;
            }
        }
        
        public object placeholder
        {
            get
            {
                return this.attributes["placeholder"];
            }
            set
            {
                this.attributes["placeholder"] = value;
            }
        }
        
        public object placeholderCollapseHideMode
        {
            get
            {
                return this.attributes["placeholderCollapseHideMode"];
            }
            set
            {
                this.attributes["placeholderCollapseHideMode"] = value;
            }
        }
        
        public object preventHeader
        {
            get
            {
                return this.attributes["preventHeader"];
            }
            set
            {
                this.attributes["preventHeader"] = value;
            }
        }
        
        public object rbar
        {
            get
            {
                return this.attributes["rbar"];
            }
            set
            {
                this.attributes["rbar"] = value;
            }
        }
        
        public object simpleDrag
        {
            get
            {
                return this.attributes["simpleDrag"];
            }
            set
            {
                this.attributes["simpleDrag"] = value;
            }
        }
        
        public object tbar
        {
            get
            {
                return this.attributes["tbar"];
            }
            set
            {
                this.attributes["tbar"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public object titleAlign
        {
            get
            {
                return this.attributes["titleAlign"];
            }
            set
            {
                this.attributes["titleAlign"] = value;
            }
        }
        
        public object titleCollapse
        {
            get
            {
                return this.attributes["titleCollapse"];
            }
            set
            {
                this.attributes["titleCollapse"] = value;
            }
        }
        
        public object tools
        {
            get
            {
                return this.attributes["tools"];
            }
            set
            {
                this.attributes["tools"] = value;
            }
        }
        
        public class MultiType_animCollapse
        {
        }
        
        public class MultiType_bbar
        {
        }
        
        public class MultiType_buttonAlign
        {
        }
        
        public class MultiType_buttons
        {
        }
        
        public class MultiType_closable
        {
        }
        
        public class MultiType_closeAction
        {
        }
        
        public class MultiType_collapseDirection
        {
        }
        
        public class MultiType_collapseFirst
        {
        }
        
        public class MultiType_collapseMode
        {
        }
        
        public class MultiType_collapsed
        {
        }
        
        public class MultiType_collapsedCls
        {
        }
        
        public class MultiType_collapsible
        {
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_constrainHeader
        {
        }
        
        public class MultiType_dockedItems
        {
        }
        
        public class MultiType_fbar
        {
        }
        
        public class MultiType_floatable
        {
        }
        
        public class MultiType_frame
        {
        }
        
        public class MultiType_frameHeader
        {
        }
        
        public class MultiType_glyph
        {
        }
        
        public class MultiType_header
        {
        }
        
        public class MultiType_headerOverCls
        {
        }
        
        public class MultiType_headerPosition
        {
        }
        
        public class MultiType_hideCollapseTool
        {
        }
        
        public class MultiType_icon
        {
        }
        
        public class MultiType_iconCls
        {
        }
        
        public class MultiType_lbar
        {
        }
        
        public class MultiType_manageHeight
        {
        }
        
        public class MultiType_minButtonWidth
        {
        }
        
        public class MultiType_overlapHeader
        {
        }
        
        public class MultiType_placeholder
        {
        }
        
        public class MultiType_placeholderCollapseHideMode
        {
        }
        
        public class MultiType_preventHeader
        {
        }
        
        public class MultiType_rbar
        {
        }
        
        public class MultiType_simpleDrag
        {
        }
        
        public class MultiType_tbar
        {
        }
        
        public class MultiType_title
        {
        }
        
        public class MultiType_titleAlign
        {
        }
        
        public class MultiType_titleCollapse
        {
        }
        
        public class MultiType_tools
        {
        }
    }
}
