//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.panel
{
    using System;
    
    
    public partial class Header : zzProject.ExtJSNet.ExtJS.Classes.Ext.container.Container
    {
        
        public string _componentLayout_default = "\'body\'";
        
        public string _defaultType_default = "\'tool\'";
        
        public string _renderTpl_default = "[\'<div id=\"{id}-body\" class=\"{headerCls}-body {baseCls}-body {bodyCls} {bodyTarge" +
            "tCls}\', \'<tpl for=\"uiCls\"> {parent.baseCls}-body-{parent.ui}-{.}</tpl>\"\', \'<tpl " +
            "if=\"bodyStyle\"> style=\"{bodyStyle}\"</tpl>>\', \'{%this.renderContainer(out,values)" +
            "%}\', \'</div>\']";
        
        public string _shrinkWrap_default = "3";
        
        public string _titlePosition_default = "0";
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object glyph
        {
            get
            {
                return this.attributes["glyph"];
            }
            set
            {
                this.attributes["glyph"] = value;
            }
        }
        
        public object icon
        {
            get
            {
                return this.attributes["icon"];
            }
            set
            {
                this.attributes["icon"] = value;
            }
        }
        
        public object iconCls
        {
            get
            {
                return this.attributes["iconCls"];
            }
            set
            {
                this.attributes["iconCls"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object shrinkWrap
        {
            get
            {
                return this.attributes["shrinkWrap"];
            }
            set
            {
                this.attributes["shrinkWrap"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public object titleAlign
        {
            get
            {
                return this.attributes["titleAlign"];
            }
            set
            {
                this.attributes["titleAlign"] = value;
            }
        }
        
        public object titlePosition
        {
            get
            {
                return this.attributes["titlePosition"];
            }
            set
            {
                this.attributes["titlePosition"] = value;
            }
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_glyph
        {
        }
        
        public class MultiType_icon
        {
        }
        
        public class MultiType_iconCls
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_shrinkWrap
        {
        }
        
        public class MultiType_title
        {
        }
        
        public class MultiType_titleAlign
        {
        }
        
        public class MultiType_titlePosition
        {
        }
    }
}
