//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.picker
{
    using System;
    
    
    public partial class Color : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _allowReselect_default = "false";
        
        public string _clickEvent_default = "\'click\'";
        
        public string _componentCls_default = "\'x-color-picker\'";
        
        public string _itemCls_default = "Ext.baseCSSPrefix + \'color-picker-item\'";
        
        public string _renderTpl_default = "[\'<tpl for=\"colors\">\', \'<a href=\"#\" class=\"color-{.} {parent.itemCls}\" hidefocus=" +
            "\"on\">\', \'<span class=\"{parent.itemCls}-inner\" style=\"background:#{.}\">&#160;</sp" +
            "an>\', \'</a>\', \'</tpl>\']";
        
        public string _selectedCls_default = "\'x-color-picker-selected\'";
        
        public object allowReselect
        {
            get
            {
                return this.attributes["allowReselect"];
            }
            set
            {
                this.attributes["allowReselect"] = value;
            }
        }
        
        public object clickEvent
        {
            get
            {
                return this.attributes["clickEvent"];
            }
            set
            {
                this.attributes["clickEvent"] = value;
            }
        }
        
        public object componentCls
        {
            get
            {
                return this.attributes["componentCls"];
            }
            set
            {
                this.attributes["componentCls"] = value;
            }
        }
        
        public object handler
        {
            get
            {
                return this.attributes["handler"];
            }
            set
            {
                this.attributes["handler"] = value;
            }
        }
        
        public object itemCls
        {
            get
            {
                return this.attributes["itemCls"];
            }
            set
            {
                this.attributes["itemCls"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object selectedCls
        {
            get
            {
                return this.attributes["selectedCls"];
            }
            set
            {
                this.attributes["selectedCls"] = value;
            }
        }
        
        public object value
        {
            get
            {
                return this.attributes["value"];
            }
            set
            {
                this.attributes["value"] = value;
            }
        }
        
        public class MultiType_allowReselect
        {
        }
        
        public class MultiType_clickEvent
        {
        }
        
        public class MultiType_componentCls
        {
        }
        
        public class MultiType_handler
        {
        }
        
        public class MultiType_itemCls
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_selectedCls
        {
        }
        
        public class MultiType_value
        {
        }
    }
}
