//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.draw
{
    using System;
    
    
    public partial class Surface : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object height
        {
            get
            {
                return this.attributes["height"];
            }
            set
            {
                this.attributes["height"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object width
        {
            get
            {
                return this.attributes["width"];
            }
            set
            {
                this.attributes["width"] = value;
            }
        }
        
        public class MultiType_height
        {
        }
        
        public class MultiType_items
        {
        }
        
        public class MultiType_width
        {
        }
    }
}
