//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tree
{
    using System;
    
    
    public partial class Panel : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Table
    {
        
        public string _deferRowRender_default = "false";
        
        public string _displayField_default = "\'text\'";
        
        public string _lines_default = "true";
        
        public string _rootVisible_default = "true";
        
        public string _rowLines_default = "false";
        
        public string _selType_default = "\'treemodel\'";
        
        public string _singleExpand_default = "false";
        
        public string _useArrows_default = "false";
        
        public string _viewType_default = "\'treeview\'";
        
        public object animate
        {
            get
            {
                return this.attributes["animate"];
            }
            set
            {
                this.attributes["animate"] = value;
            }
        }
        
        public object deferRowRender
        {
            get
            {
                return this.attributes["deferRowRender"];
            }
            set
            {
                this.attributes["deferRowRender"] = value;
            }
        }
        
        public object displayField
        {
            get
            {
                return this.attributes["displayField"];
            }
            set
            {
                this.attributes["displayField"] = value;
            }
        }
        
        public object folderSort
        {
            get
            {
                return this.attributes["folderSort"];
            }
            set
            {
                this.attributes["folderSort"] = value;
            }
        }
        
        public object hideHeaders
        {
            get
            {
                return this.attributes["hideHeaders"];
            }
            set
            {
                this.attributes["hideHeaders"] = value;
            }
        }
        
        public object lines
        {
            get
            {
                return this.attributes["lines"];
            }
            set
            {
                this.attributes["lines"] = value;
            }
        }
        
        public object root
        {
            get
            {
                return this.attributes["root"];
            }
            set
            {
                this.attributes["root"] = value;
            }
        }
        
        public object rootVisible
        {
            get
            {
                return this.attributes["rootVisible"];
            }
            set
            {
                this.attributes["rootVisible"] = value;
            }
        }
        
        public object rowLines
        {
            get
            {
                return this.attributes["rowLines"];
            }
            set
            {
                this.attributes["rowLines"] = value;
            }
        }
        
        public object selType
        {
            get
            {
                return this.attributes["selType"];
            }
            set
            {
                this.attributes["selType"] = value;
            }
        }
        
        public object singleExpand
        {
            get
            {
                return this.attributes["singleExpand"];
            }
            set
            {
                this.attributes["singleExpand"] = value;
            }
        }
        
        public object store
        {
            get
            {
                return this.attributes["store"];
            }
            set
            {
                this.attributes["store"] = value;
            }
        }
        
        public object useArrows
        {
            get
            {
                return this.attributes["useArrows"];
            }
            set
            {
                this.attributes["useArrows"] = value;
            }
        }
        
        public object viewType
        {
            get
            {
                return this.attributes["viewType"];
            }
            set
            {
                this.attributes["viewType"] = value;
            }
        }
        
        public class MultiType_animate
        {
        }
        
        public class MultiType_deferRowRender
        {
        }
        
        public class MultiType_displayField
        {
        }
        
        public class MultiType_folderSort
        {
        }
        
        public class MultiType_hideHeaders
        {
        }
        
        public class MultiType_lines
        {
        }
        
        public class MultiType_root
        {
        }
        
        public class MultiType_rootVisible
        {
        }
        
        public class MultiType_rowLines
        {
        }
        
        public class MultiType_selType
        {
        }
        
        public class MultiType_singleExpand
        {
        }
        
        public class MultiType_store
        {
        }
        
        public class MultiType_useArrows
        {
        }
        
        public class MultiType_viewType
        {
        }
    }
}
