//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class Field : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _defaultValue_default = "\"\"";
        
        public string _persist_default = "true";
        
        public string _sortDir_default = "\"ASC\"";
        
        public string _useNull_default = "false";
        
        public object convert
        {
            get
            {
                return this.attributes["convert"];
            }
            set
            {
                this.attributes["convert"] = value;
            }
        }
        
        public object dateFormat
        {
            get
            {
                return this.attributes["dateFormat"];
            }
            set
            {
                this.attributes["dateFormat"] = value;
            }
        }
        
        public object dateReadFormat
        {
            get
            {
                return this.attributes["dateReadFormat"];
            }
            set
            {
                this.attributes["dateReadFormat"] = value;
            }
        }
        
        public object dateWriteFormat
        {
            get
            {
                return this.attributes["dateWriteFormat"];
            }
            set
            {
                this.attributes["dateWriteFormat"] = value;
            }
        }
        
        public object defaultValue
        {
            get
            {
                return this.attributes["defaultValue"];
            }
            set
            {
                this.attributes["defaultValue"] = value;
            }
        }
        
        public object mapping
        {
            get
            {
                return this.attributes["mapping"];
            }
            set
            {
                this.attributes["mapping"] = value;
            }
        }
        
        public object name
        {
            get
            {
                return this.attributes["name"];
            }
            set
            {
                this.attributes["name"] = value;
            }
        }
        
        public object persist
        {
            get
            {
                return this.attributes["persist"];
            }
            set
            {
                this.attributes["persist"] = value;
            }
        }
        
        public object serialize
        {
            get
            {
                return this.attributes["serialize"];
            }
            set
            {
                this.attributes["serialize"] = value;
            }
        }
        
        public object sortDir
        {
            get
            {
                return this.attributes["sortDir"];
            }
            set
            {
                this.attributes["sortDir"] = value;
            }
        }
        
        public object sortType
        {
            get
            {
                return this.attributes["sortType"];
            }
            set
            {
                this.attributes["sortType"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object useNull
        {
            get
            {
                return this.attributes["useNull"];
            }
            set
            {
                this.attributes["useNull"] = value;
            }
        }
        
        public class MultiType_convert
        {
        }
        
        public class MultiType_dateFormat
        {
        }
        
        public class MultiType_dateReadFormat
        {
        }
        
        public class MultiType_dateWriteFormat
        {
        }
        
        public class MultiType_defaultValue
        {
        }
        
        public class MultiType_mapping
        {
        }
        
        public class MultiType_name
        {
        }
        
        public class MultiType_persist
        {
        }
        
        public class MultiType_serialize
        {
        }
        
        public class MultiType_sortDir
        {
        }
        
        public class MultiType_sortType
        {
        }
        
        public class MultiType_type
        {
        }
        
        public class MultiType_useNull
        {
        }
    }
}
