//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.property
{
    using System;
    
    
    public partial class Grid : zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.Panel
    {
        
        public string _columnLines_default = "true";
        
        public string _enableColumnMove_default = "false";
        
        public string _inferTypes_default = "true";
        
        public string _nameColumnWidth_default = "115";
        
        public string _nameField_default = "\'name\'";
        
        public string _valueField_default = "\'value\'";
        
        public object columnLines
        {
            get
            {
                return this.attributes["columnLines"];
            }
            set
            {
                this.attributes["columnLines"] = value;
            }
        }
        
        public object customEditors
        {
            get
            {
                return this.attributes["customEditors"];
            }
            set
            {
                this.attributes["customEditors"] = value;
            }
        }
        
        public object customRenderers
        {
            get
            {
                return this.attributes["customRenderers"];
            }
            set
            {
                this.attributes["customRenderers"] = value;
            }
        }
        
        public object enableColumnMove
        {
            get
            {
                return this.attributes["enableColumnMove"];
            }
            set
            {
                this.attributes["enableColumnMove"] = value;
            }
        }
        
        public object inferTypes
        {
            get
            {
                return this.attributes["inferTypes"];
            }
            set
            {
                this.attributes["inferTypes"] = value;
            }
        }
        
        public object nameColumnWidth
        {
            get
            {
                return this.attributes["nameColumnWidth"];
            }
            set
            {
                this.attributes["nameColumnWidth"] = value;
            }
        }
        
        public object nameField
        {
            get
            {
                return this.attributes["nameField"];
            }
            set
            {
                this.attributes["nameField"] = value;
            }
        }
        
        public object propertyNames
        {
            get
            {
                return this.attributes["propertyNames"];
            }
            set
            {
                this.attributes["propertyNames"] = value;
            }
        }
        
        public object source
        {
            get
            {
                return this.attributes["source"];
            }
            set
            {
                this.attributes["source"] = value;
            }
        }
        
        public object sourceConfig
        {
            get
            {
                return this.attributes["sourceConfig"];
            }
            set
            {
                this.attributes["sourceConfig"] = value;
            }
        }
        
        public object valueField
        {
            get
            {
                return this.attributes["valueField"];
            }
            set
            {
                this.attributes["valueField"] = value;
            }
        }
        
        public class MultiType_columnLines
        {
        }
        
        public class MultiType_customEditors
        {
        }
        
        public class MultiType_customRenderers
        {
        }
        
        public class MultiType_enableColumnMove
        {
        }
        
        public class MultiType_inferTypes
        {
        }
        
        public class MultiType_nameColumnWidth
        {
        }
        
        public class MultiType_nameField
        {
        }
        
        public class MultiType_propertyNames
        {
        }
        
        public class MultiType_source
        {
        }
        
        public class MultiType_sourceConfig
        {
        }
        
        public class MultiType_valueField
        {
        }
    }
}
