//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.action
{
    using System;
    
    
    public partial class Action : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _submitEmptyText_default = "true";
        
        public object failure
        {
            get
            {
                return this.attributes["failure"];
            }
            set
            {
                this.attributes["failure"] = value;
            }
        }
        
        public object form
        {
            get
            {
                return this.attributes["form"];
            }
            set
            {
                this.attributes["form"] = value;
            }
        }
        
        public object headers
        {
            get
            {
                return this.attributes["headers"];
            }
            set
            {
                this.attributes["headers"] = value;
            }
        }
        
        public object method
        {
            get
            {
                return this.attributes["method"];
            }
            set
            {
                this.attributes["method"] = value;
            }
        }
        
        public object _params
        {
            get
            {
                return this.attributes["params"];
            }
            set
            {
                this.attributes["params"] = value;
            }
        }
        
        public object reset
        {
            get
            {
                return this.attributes["reset"];
            }
            set
            {
                this.attributes["reset"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object submitEmptyText
        {
            get
            {
                return this.attributes["submitEmptyText"];
            }
            set
            {
                this.attributes["submitEmptyText"] = value;
            }
        }
        
        public object success
        {
            get
            {
                return this.attributes["success"];
            }
            set
            {
                this.attributes["success"] = value;
            }
        }
        
        public object timeout
        {
            get
            {
                return this.attributes["timeout"];
            }
            set
            {
                this.attributes["timeout"] = value;
            }
        }
        
        public object url
        {
            get
            {
                return this.attributes["url"];
            }
            set
            {
                this.attributes["url"] = value;
            }
        }
        
        public object waitMsg
        {
            get
            {
                return this.attributes["waitMsg"];
            }
            set
            {
                this.attributes["waitMsg"] = value;
            }
        }
        
        public object waitTitle
        {
            get
            {
                return this.attributes["waitTitle"];
            }
            set
            {
                this.attributes["waitTitle"] = value;
            }
        }
        
        public class MultiType_failure
        {
        }
        
        public class MultiType_form
        {
        }
        
        public class MultiType_headers
        {
        }
        
        public class MultiType_method
        {
        }
        
        public class MultiType_params
        {
        }
        
        public class MultiType_reset
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_submitEmptyText
        {
        }
        
        public class MultiType_success
        {
        }
        
        public class MultiType_timeout
        {
        }
        
        public class MultiType_url
        {
        }
        
        public class MultiType_waitMsg
        {
        }
        
        public class MultiType_waitTitle
        {
        }
    }
}
