//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data.association
{
    using System;
    
    
    public partial class Association : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _primaryKey_default = "\'id\'";
        
        public object associatedModel
        {
            get
            {
                return this.attributes["associatedModel"];
            }
            set
            {
                this.attributes["associatedModel"] = value;
            }
        }
        
        public object associationKey
        {
            get
            {
                return this.attributes["associationKey"];
            }
            set
            {
                this.attributes["associationKey"] = value;
            }
        }
        
        public object model
        {
            get
            {
                return this.attributes["model"];
            }
            set
            {
                this.attributes["model"] = value;
            }
        }
        
        public object ownerModel
        {
            get
            {
                return this.attributes["ownerModel"];
            }
            set
            {
                this.attributes["ownerModel"] = value;
            }
        }
        
        public object primaryKey
        {
            get
            {
                return this.attributes["primaryKey"];
            }
            set
            {
                this.attributes["primaryKey"] = value;
            }
        }
        
        public object reader
        {
            get
            {
                return this.attributes["reader"];
            }
            set
            {
                this.attributes["reader"] = value;
            }
        }
        
        public class MultiType_associatedModel
        {
        }
        
        public class MultiType_associationKey
        {
        }
        
        public class MultiType_model
        {
        }
        
        public class MultiType_ownerModel
        {
        }
        
        public class MultiType_primaryKey
        {
        }
        
        public class MultiType_reader
        {
        }
    }
}
