//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class Sortable : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _defaultSortDirection_default = "\"ASC\"";
        
        public object defaultSortDirection
        {
            get
            {
                return this.attributes["defaultSortDirection"];
            }
            set
            {
                this.attributes["defaultSortDirection"] = value;
            }
        }
        
        public object sortRoot
        {
            get
            {
                return this.attributes["sortRoot"];
            }
            set
            {
                this.attributes["sortRoot"] = value;
            }
        }
        
        public object sorters
        {
            get
            {
                return this.attributes["sorters"];
            }
            set
            {
                this.attributes["sorters"] = value;
            }
        }
        
        public class MultiType_defaultSortDirection
        {
        }
        
        public class MultiType_sortRoot
        {
        }
        
        public class MultiType_sorters
        {
        }
    }
}
