//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form
{
    using System;
    
    
    public partial class CheckboxGroup : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.FieldContainer
    {
        
        public string _allowBlank_default = "true";
        
        public string _blankText_default = "\"You must select at least one item in this group\"";
        
        public string _columns_default = "\'auto\'";
        
        public string _componentCls_default = "Ext.baseCSSPrefix + \'form-checkboxgroup\'";
        
        public string _defaultType_default = "\'checkboxfield\'";
        
        public string _layout_default = "\'checkboxgroup\'";
        
        public string _vertical_default = "false";
        
        public object allowBlank
        {
            get
            {
                return this.attributes["allowBlank"];
            }
            set
            {
                this.attributes["allowBlank"] = value;
            }
        }
        
        public object blankText
        {
            get
            {
                return this.attributes["blankText"];
            }
            set
            {
                this.attributes["blankText"] = value;
            }
        }
        
        public object columns
        {
            get
            {
                return this.attributes["columns"];
            }
            set
            {
                this.attributes["columns"] = value;
            }
        }
        
        public object componentCls
        {
            get
            {
                return this.attributes["componentCls"];
            }
            set
            {
                this.attributes["componentCls"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object vertical
        {
            get
            {
                return this.attributes["vertical"];
            }
            set
            {
                this.attributes["vertical"] = value;
            }
        }
        
        public class MultiType_allowBlank
        {
        }
        
        public class MultiType_blankText
        {
        }
        
        public class MultiType_columns
        {
        }
        
        public class MultiType_componentCls
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_items
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_vertical
        {
        }
    }
}
