//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Column : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series.Bar
    {
        
        public string _column_default = "true";
        
        public string _type_default = "\'column\'";
        
        public string _xPadding_default = "10";
        
        public string _yPadding_default = "0";
        
        public object axis
        {
            get
            {
                return this.attributes["axis"];
            }
            set
            {
                this.attributes["axis"] = value;
            }
        }
        
        public object column
        {
            get
            {
                return this.attributes["column"];
            }
            set
            {
                this.attributes["column"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object xPadding
        {
            get
            {
                return this.attributes["xPadding"];
            }
            set
            {
                this.attributes["xPadding"] = value;
            }
        }
        
        public object yPadding
        {
            get
            {
                return this.attributes["yPadding"];
            }
            set
            {
                this.attributes["yPadding"] = value;
            }
        }
        
        public class MultiType_axis
        {
        }
        
        public class MultiType_column
        {
        }
        
        public class MultiType_type
        {
        }
        
        public class MultiType_xPadding
        {
        }
        
        public class MultiType_yPadding
        {
        }
    }
}
