//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.dd
{
    using System;
    
    
    public partial class DragTracker : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _autoStart_default = "false";
        
        public string _preventDefault_default = "true";
        
        public string _stopEvent_default = "false";
        
        public string _tolerance_default = "5";
        
        public string _trackOver_default = "false";
        
        public object autoStart
        {
            get
            {
                return this.attributes["autoStart"];
            }
            set
            {
                this.attributes["autoStart"] = value;
            }
        }
        
        public object constrainTo
        {
            get
            {
                return this.attributes["constrainTo"];
            }
            set
            {
                this.attributes["constrainTo"] = value;
            }
        }
        
        public object _delegate
        {
            get
            {
                return this.attributes["delegate"];
            }
            set
            {
                this.attributes["delegate"] = value;
            }
        }
        
        public object overCls
        {
            get
            {
                return this.attributes["overCls"];
            }
            set
            {
                this.attributes["overCls"] = value;
            }
        }
        
        public object preventDefault
        {
            get
            {
                return this.attributes["preventDefault"];
            }
            set
            {
                this.attributes["preventDefault"] = value;
            }
        }
        
        public object stopEvent
        {
            get
            {
                return this.attributes["stopEvent"];
            }
            set
            {
                this.attributes["stopEvent"] = value;
            }
        }
        
        public object tolerance
        {
            get
            {
                return this.attributes["tolerance"];
            }
            set
            {
                this.attributes["tolerance"] = value;
            }
        }
        
        public object trackOver
        {
            get
            {
                return this.attributes["trackOver"];
            }
            set
            {
                this.attributes["trackOver"] = value;
            }
        }
        
        public class MultiType_autoStart
        {
        }
        
        public class MultiType_constrainTo
        {
        }
        
        public class MultiType_delegate
        {
        }
        
        public class MultiType_overCls
        {
        }
        
        public class MultiType_preventDefault
        {
        }
        
        public class MultiType_stopEvent
        {
        }
        
        public class MultiType_tolerance
        {
        }
        
        public class MultiType_trackOver
        {
        }
    }
}
