//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tip
{
    using System;
    
    
    public partial class QuickTip : zzProject.ExtJSNet.ExtJS.Classes.Ext.tip.ToolTip
    {
        
        public string _interceptTitles_default = "false";
        
        public string _title_default = "\'&#160;\'";
        
        public object interceptTitles
        {
            get
            {
                return this.attributes["interceptTitles"];
            }
            set
            {
                this.attributes["interceptTitles"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public class MultiType_interceptTitles
        {
        }
        
        public class MultiType_target
        {
        }
        
        public class MultiType_title
        {
        }
    }
}
