//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.button
{
    using System;
    
    
    public partial class Button : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _allowDepress_default = "true";
        
        public string _arrowAlign_default = "\'right\'";
        
        public string _arrowCls_default = "\'arrow\'";
        
        public string _baseCls_default = "\'x-btn\'";
        
        public string _clickEvent_default = "\'click\'";
        
        public string _componentLayout_default = "\'button\'";
        
        public string _disabled_default = "false";
        
        public string _enableToggle_default = "false";
        
        public string _focusCls_default = "\'focus\'";
        
        public string _frame_default = "true";
        
        public string _handleMouseEvents_default = "true";
        
        public string _hidden_default = "false";
        
        public string _hrefTarget_default = "\"_blank\"";
        
        public string _iconAlign_default = "\'left\'";
        
        public string _menuActiveCls_default = "\'menu-active\'";
        
        public string _menuAlign_default = "\'tl-bl?\'";
        
        public string _overCls_default = "\'over\'";
        
        public string _pressed_default = "false";
        
        public string _pressedCls_default = "\'pressed\'";
        
        public string _preventDefault_default = "true";
        
        public string _renderTpl_default = @"['<span id=""{id}-btnWrap"" class=""{baseCls}-wrap', '<tpl if=""splitCls""> {splitCls}</tpl>', '{childElCls}"" unselectable=""on"">', '<span id=""{id}-btnEl"" class=""{baseCls}-button"">', '<span id=""{id}-btnInnerEl"" class=""{baseCls}-inner {innerCls}', '{childElCls}"" unselectable=""on"">', '{text}', '</span>', '<span role=""img"" id=""{id}-btnIconEl"" class=""{baseCls}-icon-el {iconCls}', '{childElCls} {glyphCls}"" unselectable=""on"" style=""', '<tpl if=""iconUrl"">background-image:url({iconUrl});</tpl>', '<tpl if=""glyph && glyphFontFamily"">font-family:{glyphFontFamily};</tpl>"">', '<tpl if=""glyph"">&#{glyph};</tpl><tpl if=""iconCls || iconUrl"">&#160;</tpl>', '</span>', '</span>', '</span>', '<tpl if=""closable"">', '<span id=""{id}-closeEl"" class=""{baseCls}-close-btn"" title=""{closeText}"" tabIndex=""0""></span>', '</tpl>']";
        
        public string _repeat_default = "false";
        
        public string _scale_default = "\'small\'";
        
        public string _showEmptyMenu_default = "false";
        
        public string _shrinkWrap_default = "3";
        
        public string _tabIndex_default = "0";
        
        public string _textAlign_default = "\'center\'";
        
        public string _tooltipType_default = "\'qtip\'";
        
        public object allowDepress
        {
            get
            {
                return this.attributes["allowDepress"];
            }
            set
            {
                this.attributes["allowDepress"] = value;
            }
        }
        
        public object arrowAlign
        {
            get
            {
                return this.attributes["arrowAlign"];
            }
            set
            {
                this.attributes["arrowAlign"] = value;
            }
        }
        
        public object arrowCls
        {
            get
            {
                return this.attributes["arrowCls"];
            }
            set
            {
                this.attributes["arrowCls"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object baseParams
        {
            get
            {
                return this.attributes["baseParams"];
            }
            set
            {
                this.attributes["baseParams"] = value;
            }
        }
        
        public object clickEvent
        {
            get
            {
                return this.attributes["clickEvent"];
            }
            set
            {
                this.attributes["clickEvent"] = value;
            }
        }
        
        public object cls
        {
            get
            {
                return this.attributes["cls"];
            }
            set
            {
                this.attributes["cls"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object destroyMenu
        {
            get
            {
                return this.attributes["destroyMenu"];
            }
            set
            {
                this.attributes["destroyMenu"] = value;
            }
        }
        
        public object disabled
        {
            get
            {
                return this.attributes["disabled"];
            }
            set
            {
                this.attributes["disabled"] = value;
            }
        }
        
        public object enableToggle
        {
            get
            {
                return this.attributes["enableToggle"];
            }
            set
            {
                this.attributes["enableToggle"] = value;
            }
        }
        
        public object focusCls
        {
            get
            {
                return this.attributes["focusCls"];
            }
            set
            {
                this.attributes["focusCls"] = value;
            }
        }
        
        public object frame
        {
            get
            {
                return this.attributes["frame"];
            }
            set
            {
                this.attributes["frame"] = value;
            }
        }
        
        public object glyph
        {
            get
            {
                return this.attributes["glyph"];
            }
            set
            {
                this.attributes["glyph"] = value;
            }
        }
        
        public object handleMouseEvents
        {
            get
            {
                return this.attributes["handleMouseEvents"];
            }
            set
            {
                this.attributes["handleMouseEvents"] = value;
            }
        }
        
        public object handler
        {
            get
            {
                return this.attributes["handler"];
            }
            set
            {
                this.attributes["handler"] = value;
            }
        }
        
        public object hidden
        {
            get
            {
                return this.attributes["hidden"];
            }
            set
            {
                this.attributes["hidden"] = value;
            }
        }
        
        public object href
        {
            get
            {
                return this.attributes["href"];
            }
            set
            {
                this.attributes["href"] = value;
            }
        }
        
        public object hrefTarget
        {
            get
            {
                return this.attributes["hrefTarget"];
            }
            set
            {
                this.attributes["hrefTarget"] = value;
            }
        }
        
        public object icon
        {
            get
            {
                return this.attributes["icon"];
            }
            set
            {
                this.attributes["icon"] = value;
            }
        }
        
        public object iconAlign
        {
            get
            {
                return this.attributes["iconAlign"];
            }
            set
            {
                this.attributes["iconAlign"] = value;
            }
        }
        
        public object iconCls
        {
            get
            {
                return this.attributes["iconCls"];
            }
            set
            {
                this.attributes["iconCls"] = value;
            }
        }
        
        public object menu
        {
            get
            {
                return this.attributes["menu"];
            }
            set
            {
                this.attributes["menu"] = value;
            }
        }
        
        public object menuActiveCls
        {
            get
            {
                return this.attributes["menuActiveCls"];
            }
            set
            {
                this.attributes["menuActiveCls"] = value;
            }
        }
        
        public object menuAlign
        {
            get
            {
                return this.attributes["menuAlign"];
            }
            set
            {
                this.attributes["menuAlign"] = value;
            }
        }
        
        public object minWidth
        {
            get
            {
                return this.attributes["minWidth"];
            }
            set
            {
                this.attributes["minWidth"] = value;
            }
        }
        
        public object overCls
        {
            get
            {
                return this.attributes["overCls"];
            }
            set
            {
                this.attributes["overCls"] = value;
            }
        }
        
        public object overflowText
        {
            get
            {
                return this.attributes["overflowText"];
            }
            set
            {
                this.attributes["overflowText"] = value;
            }
        }
        
        public object _params
        {
            get
            {
                return this.attributes["params"];
            }
            set
            {
                this.attributes["params"] = value;
            }
        }
        
        public object pressed
        {
            get
            {
                return this.attributes["pressed"];
            }
            set
            {
                this.attributes["pressed"] = value;
            }
        }
        
        public object pressedCls
        {
            get
            {
                return this.attributes["pressedCls"];
            }
            set
            {
                this.attributes["pressedCls"] = value;
            }
        }
        
        public object preventDefault
        {
            get
            {
                return this.attributes["preventDefault"];
            }
            set
            {
                this.attributes["preventDefault"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object repeat
        {
            get
            {
                return this.attributes["repeat"];
            }
            set
            {
                this.attributes["repeat"] = value;
            }
        }
        
        public object scale
        {
            get
            {
                return this.attributes["scale"];
            }
            set
            {
                this.attributes["scale"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object showEmptyMenu
        {
            get
            {
                return this.attributes["showEmptyMenu"];
            }
            set
            {
                this.attributes["showEmptyMenu"] = value;
            }
        }
        
        public object shrinkWrap
        {
            get
            {
                return this.attributes["shrinkWrap"];
            }
            set
            {
                this.attributes["shrinkWrap"] = value;
            }
        }
        
        public object tabIndex
        {
            get
            {
                return this.attributes["tabIndex"];
            }
            set
            {
                this.attributes["tabIndex"] = value;
            }
        }
        
        public object text
        {
            get
            {
                return this.attributes["text"];
            }
            set
            {
                this.attributes["text"] = value;
            }
        }
        
        public object textAlign
        {
            get
            {
                return this.attributes["textAlign"];
            }
            set
            {
                this.attributes["textAlign"] = value;
            }
        }
        
        public object toggleGroup
        {
            get
            {
                return this.attributes["toggleGroup"];
            }
            set
            {
                this.attributes["toggleGroup"] = value;
            }
        }
        
        public object toggleHandler
        {
            get
            {
                return this.attributes["toggleHandler"];
            }
            set
            {
                this.attributes["toggleHandler"] = value;
            }
        }
        
        public object tooltip
        {
            get
            {
                return this.attributes["tooltip"];
            }
            set
            {
                this.attributes["tooltip"] = value;
            }
        }
        
        public object tooltipType
        {
            get
            {
                return this.attributes["tooltipType"];
            }
            set
            {
                this.attributes["tooltipType"] = value;
            }
        }
        
        public class MultiType_allowDepress
        {
        }
        
        public class MultiType_arrowAlign
        {
        }
        
        public class MultiType_arrowCls
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_baseParams
        {
        }
        
        public class MultiType_clickEvent
        {
        }
        
        public class MultiType_cls
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_destroyMenu
        {
        }
        
        public class MultiType_disabled
        {
        }
        
        public class MultiType_enableToggle
        {
        }
        
        public class MultiType_focusCls
        {
        }
        
        public class MultiType_frame
        {
        }
        
        public class MultiType_glyph
        {
        }
        
        public class MultiType_handleMouseEvents
        {
        }
        
        public class MultiType_handler
        {
        }
        
        public class MultiType_hidden
        {
        }
        
        public class MultiType_href
        {
        }
        
        public class MultiType_hrefTarget
        {
        }
        
        public class MultiType_icon
        {
        }
        
        public class MultiType_iconAlign
        {
        }
        
        public class MultiType_iconCls
        {
        }
        
        public class MultiType_menu
        {
        }
        
        public class MultiType_menuActiveCls
        {
        }
        
        public class MultiType_menuAlign
        {
        }
        
        public class MultiType_minWidth
        {
        }
        
        public class MultiType_overCls
        {
        }
        
        public class MultiType_overflowText
        {
        }
        
        public class MultiType_params
        {
        }
        
        public class MultiType_pressed
        {
        }
        
        public class MultiType_pressedCls
        {
        }
        
        public class MultiType_preventDefault
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_repeat
        {
        }
        
        public class MultiType_scale
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_showEmptyMenu
        {
        }
        
        public class MultiType_shrinkWrap
        {
        }
        
        public class MultiType_tabIndex
        {
        }
        
        public class MultiType_text
        {
        }
        
        public class MultiType_textAlign
        {
        }
        
        public class MultiType_toggleGroup
        {
        }
        
        public class MultiType_toggleHandler
        {
        }
        
        public class MultiType_tooltip
        {
        }
        
        public class MultiType_tooltipType
        {
        }
    }
}
