//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tree.plugin
{
    using System;
    
    
    public partial class TreeViewDragDrop : zzProject.ExtJSNet.ExtJS.Classes.Ext.AbstractPlugin
    {
        
        public string _allowContainerDrops_default = "false";
        
        public string _allowParentInserts_default = "false";
        
        public string _appendOnly_default = "false";
        
        public string _containerScroll_default = "false";
        
        public string _ddGroup_default = "\"TreeDD\"";
        
        public string _displayField_default = "\'text\'";
        
        public string _dragText_default = "\'{0} selected node{1}\'";
        
        public string _enableDrag_default = "true";
        
        public string _enableDrop_default = "true";
        
        public string _expandDelay_default = "1000";
        
        public string _nodeHighlightColor_default = "\'c3daf9\'";
        
        public string _sortOnDrop_default = "false";
        
        public object allowContainerDrops
        {
            get
            {
                return this.attributes["allowContainerDrops"];
            }
            set
            {
                this.attributes["allowContainerDrops"] = value;
            }
        }
        
        public object allowParentInserts
        {
            get
            {
                return this.attributes["allowParentInserts"];
            }
            set
            {
                this.attributes["allowParentInserts"] = value;
            }
        }
        
        public object appendOnly
        {
            get
            {
                return this.attributes["appendOnly"];
            }
            set
            {
                this.attributes["appendOnly"] = value;
            }
        }
        
        public object containerScroll
        {
            get
            {
                return this.attributes["containerScroll"];
            }
            set
            {
                this.attributes["containerScroll"] = value;
            }
        }
        
        public object ddGroup
        {
            get
            {
                return this.attributes["ddGroup"];
            }
            set
            {
                this.attributes["ddGroup"] = value;
            }
        }
        
        public object displayField
        {
            get
            {
                return this.attributes["displayField"];
            }
            set
            {
                this.attributes["displayField"] = value;
            }
        }
        
        public object dragGroup
        {
            get
            {
                return this.attributes["dragGroup"];
            }
            set
            {
                this.attributes["dragGroup"] = value;
            }
        }
        
        public object dragText
        {
            get
            {
                return this.attributes["dragText"];
            }
            set
            {
                this.attributes["dragText"] = value;
            }
        }
        
        public object dropGroup
        {
            get
            {
                return this.attributes["dropGroup"];
            }
            set
            {
                this.attributes["dropGroup"] = value;
            }
        }
        
        public object enableDrag
        {
            get
            {
                return this.attributes["enableDrag"];
            }
            set
            {
                this.attributes["enableDrag"] = value;
            }
        }
        
        public object enableDrop
        {
            get
            {
                return this.attributes["enableDrop"];
            }
            set
            {
                this.attributes["enableDrop"] = value;
            }
        }
        
        public object expandDelay
        {
            get
            {
                return this.attributes["expandDelay"];
            }
            set
            {
                this.attributes["expandDelay"] = value;
            }
        }
        
        public object nodeHighlightColor
        {
            get
            {
                return this.attributes["nodeHighlightColor"];
            }
            set
            {
                this.attributes["nodeHighlightColor"] = value;
            }
        }
        
        public object nodeHighlightOnDrop
        {
            get
            {
                return this.attributes["nodeHighlightOnDrop"];
            }
            set
            {
                this.attributes["nodeHighlightOnDrop"] = value;
            }
        }
        
        public object nodeHighlightOnRepair
        {
            get
            {
                return this.attributes["nodeHighlightOnRepair"];
            }
            set
            {
                this.attributes["nodeHighlightOnRepair"] = value;
            }
        }
        
        public object sortOnDrop
        {
            get
            {
                return this.attributes["sortOnDrop"];
            }
            set
            {
                this.attributes["sortOnDrop"] = value;
            }
        }
        
        public class MultiType_allowContainerDrops
        {
        }
        
        public class MultiType_allowParentInserts
        {
        }
        
        public class MultiType_appendOnly
        {
        }
        
        public class MultiType_containerScroll
        {
        }
        
        public class MultiType_ddGroup
        {
        }
        
        public class MultiType_displayField
        {
        }
        
        public class MultiType_dragGroup
        {
        }
        
        public class MultiType_dragText
        {
        }
        
        public class MultiType_dropGroup
        {
        }
        
        public class MultiType_enableDrag
        {
        }
        
        public class MultiType_enableDrop
        {
        }
        
        public class MultiType_expandDelay
        {
        }
        
        public class MultiType_nodeHighlightColor
        {
        }
        
        public class MultiType_nodeHighlightOnDrop
        {
        }
        
        public class MultiType_nodeHighlightOnRepair
        {
        }
        
        public class MultiType_sortOnDrop
        {
        }
    }
}
