//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.menu
{
    using System;
    
    
    public partial class CheckItem : zzProject.ExtJSNet.ExtJS.Classes.Ext.menu.Item
    {
        
        public string _checkChangeDisabled_default = "false";
        
        public string _checked_default = "false";
        
        public string _checkedCls_default = "Ext.baseCSSPrefix + \'menu-item-checked\'";
        
        public string _groupCls_default = "Ext.baseCSSPrefix + \'menu-group-icon\'";
        
        public string _hideOnClick_default = "false";
        
        public string _renderTpl_default = @"['<tpl if=""plain"">', '{text}', '<tpl else>', '{%var showCheckbox = values.showCheckbox,', '      rightCheckbox = showCheckbox && values.hasIcon && (values.iconAlign !== ""left""), textCls = rightCheckbox ? ""' + Ext.baseCSSPrefix + 'right-check-item-text"" : """";%}', '<a id=""{id}-itemEl"" class=""' + Ext.baseCSSPrefix + 'menu-item-link{childElCls}"" href=""{href}"" <tpl if=""hrefTarget"">target=""{hrefTarget}""</tpl> hidefocus=""true"" unselectable=""on""', '<tpl if=""tabIndex"">', ' tabIndex=""{tabIndex}""', '</tpl>', '>', '{%if (values.hasIcon && (values.iconAlign !== ""left"")) {%}', '<div role=""img"" id=""{id}-iconEl"" class=""' + Ext.baseCSSPrefix + 'menu-item-icon {iconCls}', '{childElCls} {glyphCls}"" style=""<tpl if=""icon"">background-image:url({icon});</tpl>', '<tpl if=""glyph && glyphFontFamily"">font-family:{glyphFontFamily};</tpl>"">', '<tpl if=""glyph"">&#{glyph};</tpl>', '</div>', '{%} else if (showCheckbox){%}', '<img id=""{id}-checkEl"" src=""{blank}"" class=""' + Ext.baseCSSPrefix + 'menu-item-icon{childElCls}"" />', '{%}%}', '<span id=""{id}-textEl"" class=""' + Ext.baseCSSPrefix + 'menu-item-text {[textCls]}{childElCls}"" <tpl if=""arrowCls"">style=""margin-right: 17px;""</tpl> >{text}</span>', '{%if (rightCheckbox) {%}', '<img id=""{id}-checkEl"" src=""{blank}"" class=""' + Ext.baseCSSPrefix + 'menu-item-icon-right{childElCls}"" />', '{%} else if (values.arrowCls) {%}', '<img id=""{id}-arrowEl"" src=""{blank}"" class=""{arrowCls}{childElCls}""/>', '{%}%}', '</a>', '</tpl>']";
        
        public string _uncheckedCls_default = "Ext.baseCSSPrefix + \'menu-item-unchecked\'";
        
        public object checkChangeDisabled
        {
            get
            {
                return this.attributes["checkChangeDisabled"];
            }
            set
            {
                this.attributes["checkChangeDisabled"] = value;
            }
        }
        
        public object checkHandler
        {
            get
            {
                return this.attributes["checkHandler"];
            }
            set
            {
                this.attributes["checkHandler"] = value;
            }
        }
        
        public object _checked
        {
            get
            {
                return this.attributes["checked"];
            }
            set
            {
                this.attributes["checked"] = value;
            }
        }
        
        public object checkedCls
        {
            get
            {
                return this.attributes["checkedCls"];
            }
            set
            {
                this.attributes["checkedCls"] = value;
            }
        }
        
        public object group
        {
            get
            {
                return this.attributes["group"];
            }
            set
            {
                this.attributes["group"] = value;
            }
        }
        
        public object groupCls
        {
            get
            {
                return this.attributes["groupCls"];
            }
            set
            {
                this.attributes["groupCls"] = value;
            }
        }
        
        public object hideOnClick
        {
            get
            {
                return this.attributes["hideOnClick"];
            }
            set
            {
                this.attributes["hideOnClick"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object uncheckedCls
        {
            get
            {
                return this.attributes["uncheckedCls"];
            }
            set
            {
                this.attributes["uncheckedCls"] = value;
            }
        }
        
        public class MultiType_checkChangeDisabled
        {
        }
        
        public class MultiType_checkHandler
        {
        }
        
        public class MultiType_checked
        {
        }
        
        public class MultiType_checkedCls
        {
        }
        
        public class MultiType_group
        {
        }
        
        public class MultiType_groupCls
        {
        }
        
        public class MultiType_hideOnClick
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_uncheckedCls
        {
        }
    }
}
