//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class File : zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field.Trigger
    {
        
        public string _buttonMargin_default = "3";
        
        public string _buttonOnly_default = "false";
        
        public string _buttonText_default = "\'Browse...\'";
        
        public string _clearOnSubmit_default = "true";
        
        public string _componentLayout_default = "\'triggerfield\'";
        
        public string _readOnly_default = "true";
        
        public object buttonConfig
        {
            get
            {
                return this.attributes["buttonConfig"];
            }
            set
            {
                this.attributes["buttonConfig"] = value;
            }
        }
        
        public object buttonMargin
        {
            get
            {
                return this.attributes["buttonMargin"];
            }
            set
            {
                this.attributes["buttonMargin"] = value;
            }
        }
        
        public object buttonOnly
        {
            get
            {
                return this.attributes["buttonOnly"];
            }
            set
            {
                this.attributes["buttonOnly"] = value;
            }
        }
        
        public object buttonText
        {
            get
            {
                return this.attributes["buttonText"];
            }
            set
            {
                this.attributes["buttonText"] = value;
            }
        }
        
        public object clearOnSubmit
        {
            get
            {
                return this.attributes["clearOnSubmit"];
            }
            set
            {
                this.attributes["clearOnSubmit"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object readOnly
        {
            get
            {
                return this.attributes["readOnly"];
            }
            set
            {
                this.attributes["readOnly"] = value;
            }
        }
        
        public class MultiType_buttonConfig
        {
        }
        
        public class MultiType_buttonMargin
        {
        }
        
        public class MultiType_buttonOnly
        {
        }
        
        public class MultiType_buttonText
        {
        }
        
        public class MultiType_clearOnSubmit
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_readOnly
        {
        }
    }
}
