//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.util
{
    using System;
    
    
    public partial class ComponentDragger : zzProject.ExtJSNet.ExtJS.Classes.Ext.dd.DragTracker
    {
        
        public object constrain
        {
            get
            {
                return this.attributes["constrain"];
            }
            set
            {
                this.attributes["constrain"] = value;
            }
        }
        
        public object constrainDelegate
        {
            get
            {
                return this.attributes["constrainDelegate"];
            }
            set
            {
                this.attributes["constrainDelegate"] = value;
            }
        }
        
        public object _delegate
        {
            get
            {
                return this.attributes["delegate"];
            }
            set
            {
                this.attributes["delegate"] = value;
            }
        }
        
        public class MultiType_constrain
        {
        }
        
        public class MultiType_constrainDelegate
        {
        }
        
        public class MultiType_delegate
        {
        }
    }
}
