//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.column
{
    using System;
    
    
    public partial class Column : zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.header.Container
    {
        
        public string _align_default = "\'left\'";
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'column-header\'";
        
        public string _componentLayout_default = "\'columncomponent\'";
        
        public string _detachOnRemove_default = "true";
        
        public string _draggable_default = "true";
        
        public string _editRenderer_default = "false";
        
        public string _emptyCellText_default = "undefined";
        
        public string _hideable_default = "true";
        
        public string _locked_default = "false";
        
        public string _menuDisabled_default = "false";
        
        public string _renderTpl_default = @"'<div id=""{id}-titleEl"" {tipMarkup}class=""' + Ext.baseCSSPrefix + 'column-header-inner"">' + '<span id=""{id}-textEl"" class=""' + Ext.baseCSSPrefix + 'column-header-text' + '{childElCls}"">' + '{text}' + '</span>' + '<tpl if=""!menuDisabled"">' + '<div id=""{id}-triggerEl"" class=""' + Ext.baseCSSPrefix + 'column-header-trigger' + '{childElCls}""></div>' + '</tpl>' + '</div>' + '{%this.renderContainer(out,values)%}'";
        
        public string _renderer_default = "false";
        
        public string _resizable_default = "true";
        
        public string _sortable_default = "true";
        
        public string _tdCls_default = "\'\'";
        
        public string _text_default = "\'&#160;\'";
        
        public string _tooltipType_default = "\"qtip\"";
        
        public object align
        {
            get
            {
                return this.attributes["align"];
            }
            set
            {
                this.attributes["align"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object columns
        {
            get
            {
                return this.attributes["columns"];
            }
            set
            {
                this.attributes["columns"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object dataIndex
        {
            get
            {
                return this.attributes["dataIndex"];
            }
            set
            {
                this.attributes["dataIndex"] = value;
            }
        }
        
        public object detachOnRemove
        {
            get
            {
                return this.attributes["detachOnRemove"];
            }
            set
            {
                this.attributes["detachOnRemove"] = value;
            }
        }
        
        public object draggable
        {
            get
            {
                return this.attributes["draggable"];
            }
            set
            {
                this.attributes["draggable"] = value;
            }
        }
        
        public object editRenderer
        {
            get
            {
                return this.attributes["editRenderer"];
            }
            set
            {
                this.attributes["editRenderer"] = value;
            }
        }
        
        public object editor
        {
            get
            {
                return this.attributes["editor"];
            }
            set
            {
                this.attributes["editor"] = value;
            }
        }
        
        public object emptyCellText
        {
            get
            {
                return this.attributes["emptyCellText"];
            }
            set
            {
                this.attributes["emptyCellText"] = value;
            }
        }
        
        public object field
        {
            get
            {
                return this.attributes["field"];
            }
            set
            {
                this.attributes["field"] = value;
            }
        }
        
        public object _fixed
        {
            get
            {
                return this.attributes["fixed"];
            }
            set
            {
                this.attributes["fixed"] = value;
            }
        }
        
        public object groupable
        {
            get
            {
                return this.attributes["groupable"];
            }
            set
            {
                this.attributes["groupable"] = value;
            }
        }
        
        public object header
        {
            get
            {
                return this.attributes["header"];
            }
            set
            {
                this.attributes["header"] = value;
            }
        }
        
        public object hideable
        {
            get
            {
                return this.attributes["hideable"];
            }
            set
            {
                this.attributes["hideable"] = value;
            }
        }
        
        public object lockable
        {
            get
            {
                return this.attributes["lockable"];
            }
            set
            {
                this.attributes["lockable"] = value;
            }
        }
        
        public object locked
        {
            get
            {
                return this.attributes["locked"];
            }
            set
            {
                this.attributes["locked"] = value;
            }
        }
        
        public object menuDisabled
        {
            get
            {
                return this.attributes["menuDisabled"];
            }
            set
            {
                this.attributes["menuDisabled"] = value;
            }
        }
        
        public object menuText
        {
            get
            {
                return this.attributes["menuText"];
            }
            set
            {
                this.attributes["menuText"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object renderer
        {
            get
            {
                return this.attributes["renderer"];
            }
            set
            {
                this.attributes["renderer"] = value;
            }
        }
        
        public object resizable
        {
            get
            {
                return this.attributes["resizable"];
            }
            set
            {
                this.attributes["resizable"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object sortable
        {
            get
            {
                return this.attributes["sortable"];
            }
            set
            {
                this.attributes["sortable"] = value;
            }
        }
        
        public object stateId
        {
            get
            {
                return this.attributes["stateId"];
            }
            set
            {
                this.attributes["stateId"] = value;
            }
        }
        
        public object tdCls
        {
            get
            {
                return this.attributes["tdCls"];
            }
            set
            {
                this.attributes["tdCls"] = value;
            }
        }
        
        public object text
        {
            get
            {
                return this.attributes["text"];
            }
            set
            {
                this.attributes["text"] = value;
            }
        }
        
        public object tooltip
        {
            get
            {
                return this.attributes["tooltip"];
            }
            set
            {
                this.attributes["tooltip"] = value;
            }
        }
        
        public object tooltipType
        {
            get
            {
                return this.attributes["tooltipType"];
            }
            set
            {
                this.attributes["tooltipType"] = value;
            }
        }
        
        public class MultiType_align
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_columns
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_dataIndex
        {
        }
        
        public class MultiType_detachOnRemove
        {
        }
        
        public class MultiType_draggable
        {
        }
        
        public class MultiType_editRenderer
        {
        }
        
        public class MultiType_editor
        {
        }
        
        public class MultiType_emptyCellText
        {
        }
        
        public class MultiType_field
        {
        }
        
        public class MultiType_fixed
        {
        }
        
        public class MultiType_groupable
        {
        }
        
        public class MultiType_header
        {
        }
        
        public class MultiType_hideable
        {
        }
        
        public class MultiType_lockable
        {
        }
        
        public class MultiType_locked
        {
        }
        
        public class MultiType_menuDisabled
        {
        }
        
        public class MultiType_menuText
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_renderer
        {
        }
        
        public class MultiType_resizable
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_sortable
        {
        }
        
        public class MultiType_stateId
        {
        }
        
        public class MultiType_tdCls
        {
        }
        
        public class MultiType_text
        {
        }
        
        public class MultiType_tooltip
        {
        }
        
        public class MultiType_tooltipType
        {
        }
    }
}
