//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.panel
{
    using System;
    
    
    public partial class Tool : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'tool\'";
        
        public string _disabledCls_default = "Ext.baseCSSPrefix + \'tool-disabled\'";
        
        public string _height_default = "15";
        
        public string _renderTpl_default = "[\'<img role=\"presentation\" id=\"{id}-toolEl\" src=\"{blank}\" class=\"{baseCls}-img {b" +
            "aseCls}-{type}\' + \'{childElCls}\" role=\"presentation\"/>\']";
        
        public string _stopEvent_default = "true";
        
        public string _tooltipType_default = "\'qtip\'";
        
        public string _width_default = "15";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object callback
        {
            get
            {
                return this.attributes["callback"];
            }
            set
            {
                this.attributes["callback"] = value;
            }
        }
        
        public object disabledCls
        {
            get
            {
                return this.attributes["disabledCls"];
            }
            set
            {
                this.attributes["disabledCls"] = value;
            }
        }
        
        public object handler
        {
            get
            {
                return this.attributes["handler"];
            }
            set
            {
                this.attributes["handler"] = value;
            }
        }
        
        public object height
        {
            get
            {
                return this.attributes["height"];
            }
            set
            {
                this.attributes["height"] = value;
            }
        }
        
        public object renderTpl
        {
            get
            {
                return this.attributes["renderTpl"];
            }
            set
            {
                this.attributes["renderTpl"] = value;
            }
        }
        
        public object scope
        {
            get
            {
                return this.attributes["scope"];
            }
            set
            {
                this.attributes["scope"] = value;
            }
        }
        
        public object stopEvent
        {
            get
            {
                return this.attributes["stopEvent"];
            }
            set
            {
                this.attributes["stopEvent"] = value;
            }
        }
        
        public object toolOwner
        {
            get
            {
                return this.attributes["toolOwner"];
            }
            set
            {
                this.attributes["toolOwner"] = value;
            }
        }
        
        public object tooltip
        {
            get
            {
                return this.attributes["tooltip"];
            }
            set
            {
                this.attributes["tooltip"] = value;
            }
        }
        
        public object tooltipType
        {
            get
            {
                return this.attributes["tooltipType"];
            }
            set
            {
                this.attributes["tooltipType"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object width
        {
            get
            {
                return this.attributes["width"];
            }
            set
            {
                this.attributes["width"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_callback
        {
        }
        
        public class MultiType_disabledCls
        {
        }
        
        public class MultiType_handler
        {
        }
        
        public class MultiType_height
        {
        }
        
        public class MultiType_renderTpl
        {
        }
        
        public class MultiType_scope
        {
        }
        
        public class MultiType_stopEvent
        {
        }
        
        public class MultiType_toolOwner
        {
        }
        
        public class MultiType_tooltip
        {
        }
        
        public class MultiType_tooltipType
        {
        }
        
        public class MultiType_type
        {
        }
        
        public class MultiType_width
        {
        }
    }
}
