//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.dd
{
    using System;
    
    
    public partial class DragZone : zzProject.ExtJSNet.ExtJS.Classes.Ext.dd.DragSource
    {
        
        public object containerScroll
        {
            get
            {
                return this.attributes["containerScroll"];
            }
            set
            {
                this.attributes["containerScroll"] = value;
            }
        }
        
        public object scrollEl
        {
            get
            {
                return this.attributes["scrollEl"];
            }
            set
            {
                this.attributes["scrollEl"] = value;
            }
        }
        
        public class MultiType_containerScroll
        {
        }
        
        public class MultiType_scrollEl
        {
        }
    }
}
