//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis
{
    using System;
    
    
    public partial class Radial : zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.axis.Numeric
    {
        
        public string _position_default = "\'radial\'";
        
        public string _steps_default = "10";
        
        public object maximum
        {
            get
            {
                return this.attributes["maximum"];
            }
            set
            {
                this.attributes["maximum"] = value;
            }
        }
        
        public object position
        {
            get
            {
                return this.attributes["position"];
            }
            set
            {
                this.attributes["position"] = value;
            }
        }
        
        public object steps
        {
            get
            {
                return this.attributes["steps"];
            }
            set
            {
                this.attributes["steps"] = value;
            }
        }
        
        public class MultiType_maximum
        {
        }
        
        public class MultiType_position
        {
        }
        
        public class MultiType_steps
        {
        }
    }
}
