//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.draw
{
    using System;
    
    
    public partial class Text : zzProject.ExtJSNet.ExtJS.Classes.Ext.draw.Component
    {
        
        public string _autoSize_default = "true";
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'surface \' + Ext.baseCSSPrefix + \'draw-text\'";
        
        public string _text_default = "\'\'";
        
        public string _viewBox_default = "false";
        
        public object autoSize
        {
            get
            {
                return this.attributes["autoSize"];
            }
            set
            {
                this.attributes["autoSize"] = value;
            }
        }
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object degrees
        {
            get
            {
                return this.attributes["degrees"];
            }
            set
            {
                this.attributes["degrees"] = value;
            }
        }
        
        public object styleSelector
        {
            get
            {
                return this.attributes["styleSelector"];
            }
            set
            {
                this.attributes["styleSelector"] = value;
            }
        }
        
        public object text
        {
            get
            {
                return this.attributes["text"];
            }
            set
            {
                this.attributes["text"] = value;
            }
        }
        
        public object viewBox
        {
            get
            {
                return this.attributes["viewBox"];
            }
            set
            {
                this.attributes["viewBox"] = value;
            }
        }
        
        public class MultiType_autoSize
        {
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_degrees
        {
        }
        
        public class MultiType_styleSelector
        {
        }
        
        public class MultiType_text
        {
        }
        
        public class MultiType_viewBox
        {
        }
    }
}
