//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.form.field
{
    using System;
    
    
    public partial class Base : zzProject.ExtJSNet.ExtJS.Classes.Ext.Component
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'field\'";
        
        public string _checkChangeBuffer_default = "50";
        
        public string _componentLayout_default = "\'field\'";
        
        public string _dirtyCls_default = "Ext.baseCSSPrefix + \'form-dirty\'";
        
        public string _fieldCls_default = "\'x-form-field\'";
        
        public string _focusCls_default = "\'x-form-focus\'";
        
        public string _inputType_default = "\'text\'";
        
        public string _invalidText_default = "\'The value in this field is invalid\'";
        
        public string _readOnly_default = "false";
        
        public string _readOnlyCls_default = "Ext.baseCSSPrefix + \'form-readonly\'";
        
        public string _validateOnBlur_default = "true";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object checkChangeBuffer
        {
            get
            {
                return this.attributes["checkChangeBuffer"];
            }
            set
            {
                this.attributes["checkChangeBuffer"] = value;
            }
        }
        
        public object checkChangeEvents
        {
            get
            {
                return this.attributes["checkChangeEvents"];
            }
            set
            {
                this.attributes["checkChangeEvents"] = value;
            }
        }
        
        public object componentLayout
        {
            get
            {
                return this.attributes["componentLayout"];
            }
            set
            {
                this.attributes["componentLayout"] = value;
            }
        }
        
        public object dirtyCls
        {
            get
            {
                return this.attributes["dirtyCls"];
            }
            set
            {
                this.attributes["dirtyCls"] = value;
            }
        }
        
        public object fieldCls
        {
            get
            {
                return this.attributes["fieldCls"];
            }
            set
            {
                this.attributes["fieldCls"] = value;
            }
        }
        
        public object fieldStyle
        {
            get
            {
                return this.attributes["fieldStyle"];
            }
            set
            {
                this.attributes["fieldStyle"] = value;
            }
        }
        
        public object focusCls
        {
            get
            {
                return this.attributes["focusCls"];
            }
            set
            {
                this.attributes["focusCls"] = value;
            }
        }
        
        public object inputAttrTpl
        {
            get
            {
                return this.attributes["inputAttrTpl"];
            }
            set
            {
                this.attributes["inputAttrTpl"] = value;
            }
        }
        
        public object inputId
        {
            get
            {
                return this.attributes["inputId"];
            }
            set
            {
                this.attributes["inputId"] = value;
            }
        }
        
        public object inputType
        {
            get
            {
                return this.attributes["inputType"];
            }
            set
            {
                this.attributes["inputType"] = value;
            }
        }
        
        public object invalidText
        {
            get
            {
                return this.attributes["invalidText"];
            }
            set
            {
                this.attributes["invalidText"] = value;
            }
        }
        
        public object name
        {
            get
            {
                return this.attributes["name"];
            }
            set
            {
                this.attributes["name"] = value;
            }
        }
        
        public object readOnly
        {
            get
            {
                return this.attributes["readOnly"];
            }
            set
            {
                this.attributes["readOnly"] = value;
            }
        }
        
        public object readOnlyCls
        {
            get
            {
                return this.attributes["readOnlyCls"];
            }
            set
            {
                this.attributes["readOnlyCls"] = value;
            }
        }
        
        public object tabIndex
        {
            get
            {
                return this.attributes["tabIndex"];
            }
            set
            {
                this.attributes["tabIndex"] = value;
            }
        }
        
        public object validateOnBlur
        {
            get
            {
                return this.attributes["validateOnBlur"];
            }
            set
            {
                this.attributes["validateOnBlur"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_checkChangeBuffer
        {
        }
        
        public class MultiType_checkChangeEvents
        {
        }
        
        public class MultiType_componentLayout
        {
        }
        
        public class MultiType_dirtyCls
        {
        }
        
        public class MultiType_fieldCls
        {
        }
        
        public class MultiType_fieldStyle
        {
        }
        
        public class MultiType_focusCls
        {
        }
        
        public class MultiType_inputAttrTpl
        {
        }
        
        public class MultiType_inputId
        {
        }
        
        public class MultiType_inputType
        {
        }
        
        public class MultiType_invalidText
        {
        }
        
        public class MultiType_name
        {
        }
        
        public class MultiType_readOnly
        {
        }
        
        public class MultiType_readOnlyCls
        {
        }
        
        public class MultiType_tabIndex
        {
        }
        
        public class MultiType_validateOnBlur
        {
        }
    }
}
