//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.button
{
    using System;
    
    
    public partial class Cycle : zzProject.ExtJSNet.ExtJS.Classes.Ext.button.Split
    {
        
        public string _prependText_default = "\'\'";
        
        public string _showText_default = "false";
        
        public object changeHandler
        {
            get
            {
                return this.attributes["changeHandler"];
            }
            set
            {
                this.attributes["changeHandler"] = value;
            }
        }
        
        public object forceGlyph
        {
            get
            {
                return this.attributes["forceGlyph"];
            }
            set
            {
                this.attributes["forceGlyph"] = value;
            }
        }
        
        public object forceIcon
        {
            get
            {
                return this.attributes["forceIcon"];
            }
            set
            {
                this.attributes["forceIcon"] = value;
            }
        }
        
        public object items
        {
            get
            {
                return this.attributes["items"];
            }
            set
            {
                this.attributes["items"] = value;
            }
        }
        
        public object prependText
        {
            get
            {
                return this.attributes["prependText"];
            }
            set
            {
                this.attributes["prependText"] = value;
            }
        }
        
        public object showText
        {
            get
            {
                return this.attributes["showText"];
            }
            set
            {
                this.attributes["showText"] = value;
            }
        }
        
        public class MultiType_changeHandler
        {
        }
        
        public class MultiType_forceGlyph
        {
        }
        
        public class MultiType_forceIcon
        {
        }
        
        public class MultiType_items
        {
        }
        
        public class MultiType_prependText
        {
        }
        
        public class MultiType_showText
        {
        }
    }
}
