//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.tip
{
    using System;
    
    
    public partial class ToolTip : zzProject.ExtJSNet.ExtJS.Classes.Ext.tip.Tip
    {
        
        public string _anchorOffset_default = "0";
        
        public string _anchorToTarget_default = "true";
        
        public string _autoHide_default = "true";
        
        public string _dismissDelay_default = "5000";
        
        public string _hideDelay_default = "200";
        
        public string _mouseOffset_default = "[15,18]";
        
        public string _showDelay_default = "500";
        
        public string _trackMouse_default = "false";
        
        public object anchor
        {
            get
            {
                return this.attributes["anchor"];
            }
            set
            {
                this.attributes["anchor"] = value;
            }
        }
        
        public object anchorOffset
        {
            get
            {
                return this.attributes["anchorOffset"];
            }
            set
            {
                this.attributes["anchorOffset"] = value;
            }
        }
        
        public object anchorToTarget
        {
            get
            {
                return this.attributes["anchorToTarget"];
            }
            set
            {
                this.attributes["anchorToTarget"] = value;
            }
        }
        
        public object autoHide
        {
            get
            {
                return this.attributes["autoHide"];
            }
            set
            {
                this.attributes["autoHide"] = value;
            }
        }
        
        public object _delegate
        {
            get
            {
                return this.attributes["delegate"];
            }
            set
            {
                this.attributes["delegate"] = value;
            }
        }
        
        public object dismissDelay
        {
            get
            {
                return this.attributes["dismissDelay"];
            }
            set
            {
                this.attributes["dismissDelay"] = value;
            }
        }
        
        public object hideDelay
        {
            get
            {
                return this.attributes["hideDelay"];
            }
            set
            {
                this.attributes["hideDelay"] = value;
            }
        }
        
        public object mouseOffset
        {
            get
            {
                return this.attributes["mouseOffset"];
            }
            set
            {
                this.attributes["mouseOffset"] = value;
            }
        }
        
        public object showDelay
        {
            get
            {
                return this.attributes["showDelay"];
            }
            set
            {
                this.attributes["showDelay"] = value;
            }
        }
        
        public object target
        {
            get
            {
                return this.attributes["target"];
            }
            set
            {
                this.attributes["target"] = value;
            }
        }
        
        public object trackMouse
        {
            get
            {
                return this.attributes["trackMouse"];
            }
            set
            {
                this.attributes["trackMouse"] = value;
            }
        }
        
        public class MultiType_anchor
        {
        }
        
        public class MultiType_anchorOffset
        {
        }
        
        public class MultiType_anchorToTarget
        {
        }
        
        public class MultiType_autoHide
        {
        }
        
        public class MultiType_delegate
        {
        }
        
        public class MultiType_dismissDelay
        {
        }
        
        public class MultiType_hideDelay
        {
        }
        
        public class MultiType_mouseOffset
        {
        }
        
        public class MultiType_showDelay
        {
        }
        
        public class MultiType_target
        {
        }
        
        public class MultiType_trackMouse
        {
        }
    }
}
