//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.draw
{
    using System;
    
    
    public partial class Sprite : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public object draggable
        {
            get
            {
                return this.attributes["draggable"];
            }
            set
            {
                this.attributes["draggable"] = value;
            }
        }
        
        public object fill
        {
            get
            {
                return this.attributes["fill"];
            }
            set
            {
                this.attributes["fill"] = value;
            }
        }
        
        public object font
        {
            get
            {
                return this.attributes["font"];
            }
            set
            {
                this.attributes["font"] = value;
            }
        }
        
        public object group
        {
            get
            {
                return this.attributes["group"];
            }
            set
            {
                this.attributes["group"] = value;
            }
        }
        
        public object height
        {
            get
            {
                return this.attributes["height"];
            }
            set
            {
                this.attributes["height"] = value;
            }
        }
        
        public object opacity
        {
            get
            {
                return this.attributes["opacity"];
            }
            set
            {
                this.attributes["opacity"] = value;
            }
        }
        
        public object path
        {
            get
            {
                return this.attributes["path"];
            }
            set
            {
                this.attributes["path"] = value;
            }
        }
        
        public object radius
        {
            get
            {
                return this.attributes["radius"];
            }
            set
            {
                this.attributes["radius"] = value;
            }
        }
        
        public object radiusX
        {
            get
            {
                return this.attributes["radiusX"];
            }
            set
            {
                this.attributes["radiusX"] = value;
            }
        }
        
        public object radiusY
        {
            get
            {
                return this.attributes["radiusY"];
            }
            set
            {
                this.attributes["radiusY"] = value;
            }
        }
        
        public object src
        {
            get
            {
                return this.attributes["src"];
            }
            set
            {
                this.attributes["src"] = value;
            }
        }
        
        public object stroke
        {
            get
            {
                return this.attributes["stroke"];
            }
            set
            {
                this.attributes["stroke"] = value;
            }
        }
        
        public object stroke_width
        {
            get
            {
                return this.attributes["stroke-width"];
            }
            set
            {
                this.attributes["stroke-width"] = value;
            }
        }
        
        public object text
        {
            get
            {
                return this.attributes["text"];
            }
            set
            {
                this.attributes["text"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public object width
        {
            get
            {
                return this.attributes["width"];
            }
            set
            {
                this.attributes["width"] = value;
            }
        }
        
        public object x
        {
            get
            {
                return this.attributes["x"];
            }
            set
            {
                this.attributes["x"] = value;
            }
        }
        
        public object y
        {
            get
            {
                return this.attributes["y"];
            }
            set
            {
                this.attributes["y"] = value;
            }
        }
        
        public class MultiType_draggable
        {
        }
        
        public class MultiType_fill
        {
        }
        
        public class MultiType_font
        {
        }
        
        public class MultiType_group
        {
        }
        
        public class MultiType_height
        {
        }
        
        public class MultiType_opacity
        {
        }
        
        public class MultiType_path
        {
        }
        
        public class MultiType_radius
        {
        }
        
        public class MultiType_radiusX
        {
        }
        
        public class MultiType_radiusY
        {
        }
        
        public class MultiType_src
        {
        }
        
        public class MultiType_stroke
        {
        }
        
        public class MultiType_stroke_width
        {
        }
        
        public class MultiType_text
        {
        }
        
        public class MultiType_type
        {
        }
        
        public class MultiType_width
        {
        }
        
        public class MultiType_x
        {
        }
        
        public class MultiType_y
        {
        }
    }
}
