//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.grid.locking
{
    using System;
    
    
    public partial class Lockable : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _scrollDelta_default = "40";
        
        public string _syncRowHeight_default = "true";
        
        public object lockedGridConfig
        {
            get
            {
                return this.attributes["lockedGridConfig"];
            }
            set
            {
                this.attributes["lockedGridConfig"] = value;
            }
        }
        
        public object lockedViewConfig
        {
            get
            {
                return this.attributes["lockedViewConfig"];
            }
            set
            {
                this.attributes["lockedViewConfig"] = value;
            }
        }
        
        public object normalGridConfig
        {
            get
            {
                return this.attributes["normalGridConfig"];
            }
            set
            {
                this.attributes["normalGridConfig"] = value;
            }
        }
        
        public object normalViewConfig
        {
            get
            {
                return this.attributes["normalViewConfig"];
            }
            set
            {
                this.attributes["normalViewConfig"] = value;
            }
        }
        
        public object scrollDelta
        {
            get
            {
                return this.attributes["scrollDelta"];
            }
            set
            {
                this.attributes["scrollDelta"] = value;
            }
        }
        
        public object subGridXType
        {
            get
            {
                return this.attributes["subGridXType"];
            }
            set
            {
                this.attributes["subGridXType"] = value;
            }
        }
        
        public object syncRowHeight
        {
            get
            {
                return this.attributes["syncRowHeight"];
            }
            set
            {
                this.attributes["syncRowHeight"] = value;
            }
        }
        
        public class MultiType_lockedGridConfig
        {
        }
        
        public class MultiType_lockedViewConfig
        {
        }
        
        public class MultiType_normalGridConfig
        {
        }
        
        public class MultiType_normalViewConfig
        {
        }
        
        public class MultiType_scrollDelta
        {
        }
        
        public class MultiType_subGridXType
        {
        }
        
        public class MultiType_syncRowHeight
        {
        }
    }
}
