//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.chart.series
{
    using System;
    
    
    public partial class Series : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _showInLegend_default = "true";
        
        public object highlight
        {
            get
            {
                return this.attributes["highlight"];
            }
            set
            {
                this.attributes["highlight"] = value;
            }
        }
        
        public object listeners
        {
            get
            {
                return this.attributes["listeners"];
            }
            set
            {
                this.attributes["listeners"] = value;
            }
        }
        
        public object renderer
        {
            get
            {
                return this.attributes["renderer"];
            }
            set
            {
                this.attributes["renderer"] = value;
            }
        }
        
        public object shadowAttributes
        {
            get
            {
                return this.attributes["shadowAttributes"];
            }
            set
            {
                this.attributes["shadowAttributes"] = value;
            }
        }
        
        public object showInLegend
        {
            get
            {
                return this.attributes["showInLegend"];
            }
            set
            {
                this.attributes["showInLegend"] = value;
            }
        }
        
        public object tips
        {
            get
            {
                return this.attributes["tips"];
            }
            set
            {
                this.attributes["tips"] = value;
            }
        }
        
        public object title
        {
            get
            {
                return this.attributes["title"];
            }
            set
            {
                this.attributes["title"] = value;
            }
        }
        
        public object type
        {
            get
            {
                return this.attributes["type"];
            }
            set
            {
                this.attributes["type"] = value;
            }
        }
        
        public class MultiType_highlight
        {
        }
        
        public class MultiType_listeners
        {
        }
        
        public class MultiType_renderer
        {
        }
        
        public class MultiType_shadowAttributes
        {
        }
        
        public class MultiType_showInLegend
        {
        }
        
        public class MultiType_tips
        {
        }
        
        public class MultiType_title
        {
        }
        
        public class MultiType_type
        {
        }
    }
}
