//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.container
{
    using System;
    
    
    public partial class ButtonGroup : zzProject.ExtJSNet.ExtJS.Classes.Ext.panel.Panel
    {
        
        public string _baseCls_default = "Ext.baseCSSPrefix + \'btn-group\'";
        
        public string _defaultType_default = "\'button\'";
        
        public string _frame_default = "true";
        
        public string _layout_default = "{type: \'table\'}";
        
        public string _titleAlign_default = "\'center\'";
        
        public object baseCls
        {
            get
            {
                return this.attributes["baseCls"];
            }
            set
            {
                this.attributes["baseCls"] = value;
            }
        }
        
        public object columns
        {
            get
            {
                return this.attributes["columns"];
            }
            set
            {
                this.attributes["columns"] = value;
            }
        }
        
        public object defaultButtonUI
        {
            get
            {
                return this.attributes["defaultButtonUI"];
            }
            set
            {
                this.attributes["defaultButtonUI"] = value;
            }
        }
        
        public object defaultType
        {
            get
            {
                return this.attributes["defaultType"];
            }
            set
            {
                this.attributes["defaultType"] = value;
            }
        }
        
        public object frame
        {
            get
            {
                return this.attributes["frame"];
            }
            set
            {
                this.attributes["frame"] = value;
            }
        }
        
        public object layout
        {
            get
            {
                return this.attributes["layout"];
            }
            set
            {
                this.attributes["layout"] = value;
            }
        }
        
        public object titleAlign
        {
            get
            {
                return this.attributes["titleAlign"];
            }
            set
            {
                this.attributes["titleAlign"] = value;
            }
        }
        
        public class MultiType_baseCls
        {
        }
        
        public class MultiType_columns
        {
        }
        
        public class MultiType_defaultButtonUI
        {
        }
        
        public class MultiType_defaultType
        {
        }
        
        public class MultiType_frame
        {
        }
        
        public class MultiType_layout
        {
        }
        
        public class MultiType_titleAlign
        {
        }
    }
}
