//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.data
{
    using System;
    
    
    public partial class AbstractStore : zzProject.ExtJSNet.ExtJS.Classes.Ext.Base
    {
        
        public string _autoSync_default = "false";
        
        public string _batchUpdateMode_default = "\'operation\'";
        
        public string _filterOnLoad_default = "true";
        
        public string _remoteFilter_default = "false";
        
        public string _remoteSort_default = "false";
        
        public string _sortOnLoad_default = "true";
        
        public string _statefulFilters_default = "false";
        
        public object autoLoad
        {
            get
            {
                return this.attributes["autoLoad"];
            }
            set
            {
                this.attributes["autoLoad"] = value;
            }
        }
        
        public object autoSync
        {
            get
            {
                return this.attributes["autoSync"];
            }
            set
            {
                this.attributes["autoSync"] = value;
            }
        }
        
        public object batchUpdateMode
        {
            get
            {
                return this.attributes["batchUpdateMode"];
            }
            set
            {
                this.attributes["batchUpdateMode"] = value;
            }
        }
        
        public object fields
        {
            get
            {
                return this.attributes["fields"];
            }
            set
            {
                this.attributes["fields"] = value;
            }
        }
        
        public object filterOnLoad
        {
            get
            {
                return this.attributes["filterOnLoad"];
            }
            set
            {
                this.attributes["filterOnLoad"] = value;
            }
        }
        
        public object filters
        {
            get
            {
                return this.attributes["filters"];
            }
            set
            {
                this.attributes["filters"] = value;
            }
        }
        
        public object model
        {
            get
            {
                return this.attributes["model"];
            }
            set
            {
                this.attributes["model"] = value;
            }
        }
        
        public object proxy
        {
            get
            {
                return this.attributes["proxy"];
            }
            set
            {
                this.attributes["proxy"] = value;
            }
        }
        
        public object remoteFilter
        {
            get
            {
                return this.attributes["remoteFilter"];
            }
            set
            {
                this.attributes["remoteFilter"] = value;
            }
        }
        
        public object remoteSort
        {
            get
            {
                return this.attributes["remoteSort"];
            }
            set
            {
                this.attributes["remoteSort"] = value;
            }
        }
        
        public object sortOnLoad
        {
            get
            {
                return this.attributes["sortOnLoad"];
            }
            set
            {
                this.attributes["sortOnLoad"] = value;
            }
        }
        
        public object statefulFilters
        {
            get
            {
                return this.attributes["statefulFilters"];
            }
            set
            {
                this.attributes["statefulFilters"] = value;
            }
        }
        
        public object storeId
        {
            get
            {
                return this.attributes["storeId"];
            }
            set
            {
                this.attributes["storeId"] = value;
            }
        }
        
        public class MultiType_autoLoad
        {
        }
        
        public class MultiType_autoSync
        {
        }
        
        public class MultiType_batchUpdateMode
        {
        }
        
        public class MultiType_fields
        {
        }
        
        public class MultiType_filterOnLoad
        {
        }
        
        public class MultiType_filters
        {
        }
        
        public class MultiType_model
        {
        }
        
        public class MultiType_proxy
        {
        }
        
        public class MultiType_remoteFilter
        {
        }
        
        public class MultiType_remoteSort
        {
        }
        
        public class MultiType_sortOnLoad
        {
        }
        
        public class MultiType_statefulFilters
        {
        }
        
        public class MultiType_storeId
        {
        }
    }
}
