//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.boxOverflow
{
    using System;
    
    
    public partial class Scroller : zzProject.ExtJSNet.ExtJS.Classes.Ext.layout.container.boxOverflow.None
    {
        
        public string _animateScroll_default = "false";
        
        public string _scrollDuration_default = "400";
        
        public string _scrollIncrement_default = "20";
        
        public string _scrollRepeatInterval_default = "60";
        
        public string _scrollerCls_default = "\'x-box-scroller\'";
        
        public string _wheelIncrement_default = "10";
        
        public object afterCtCls
        {
            get
            {
                return this.attributes["afterCtCls"];
            }
            set
            {
                this.attributes["afterCtCls"] = value;
            }
        }
        
        public object afterScrollerCls
        {
            get
            {
                return this.attributes["afterScrollerCls"];
            }
            set
            {
                this.attributes["afterScrollerCls"] = value;
            }
        }
        
        public object animateScroll
        {
            get
            {
                return this.attributes["animateScroll"];
            }
            set
            {
                this.attributes["animateScroll"] = value;
            }
        }
        
        public object beforeCtCls
        {
            get
            {
                return this.attributes["beforeCtCls"];
            }
            set
            {
                this.attributes["beforeCtCls"] = value;
            }
        }
        
        public object beforeScrollerCls
        {
            get
            {
                return this.attributes["beforeScrollerCls"];
            }
            set
            {
                this.attributes["beforeScrollerCls"] = value;
            }
        }
        
        public object scrollDuration
        {
            get
            {
                return this.attributes["scrollDuration"];
            }
            set
            {
                this.attributes["scrollDuration"] = value;
            }
        }
        
        public object scrollIncrement
        {
            get
            {
                return this.attributes["scrollIncrement"];
            }
            set
            {
                this.attributes["scrollIncrement"] = value;
            }
        }
        
        public object scrollRepeatInterval
        {
            get
            {
                return this.attributes["scrollRepeatInterval"];
            }
            set
            {
                this.attributes["scrollRepeatInterval"] = value;
            }
        }
        
        public object scrollerCls
        {
            get
            {
                return this.attributes["scrollerCls"];
            }
            set
            {
                this.attributes["scrollerCls"] = value;
            }
        }
        
        public object wheelIncrement
        {
            get
            {
                return this.attributes["wheelIncrement"];
            }
            set
            {
                this.attributes["wheelIncrement"] = value;
            }
        }
        
        public class MultiType_afterCtCls
        {
        }
        
        public class MultiType_afterScrollerCls
        {
        }
        
        public class MultiType_animateScroll
        {
        }
        
        public class MultiType_beforeCtCls
        {
        }
        
        public class MultiType_beforeScrollerCls
        {
        }
        
        public class MultiType_scrollDuration
        {
        }
        
        public class MultiType_scrollIncrement
        {
        }
        
        public class MultiType_scrollRepeatInterval
        {
        }
        
        public class MultiType_scrollerCls
        {
        }
        
        public class MultiType_wheelIncrement
        {
        }
    }
}
